apps/ideas/views.py
The a4 core permission view does not redirect to login, if permissions are denied.
=> use a4 permission view

apps/contrib/templates/meinberlin_contrib/includes/pagination.html, apps/contrib/templates/meinberlin_contrib/includes/sort.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/ideas/views.py, meinberlin/assets/scss/components/_pagination.scss, meinberlin/assets/scss/style.scss
Note that ddfdf04 uses the `contrast-color()` function from #31. There is no build error, but the styling looks a bit off without it.
The UI can be expanded later (e.g. previous/next links) but I went with a minimal solution for now.
To test, it is easiest to reduce `IdeaListView.paginate_by` to 1.
=> pagination

webpack.config.js
when using `npm link`, dependencies are resolved against the linked
folder by default. This may result in dependencies being included twice.
Setting `resolve.root` forces webpack to resolve all dependencies
against the local directory.
=> Fix webpack development resolution

apps/cms/templates/meinberlin_cms/home_page.html, apps/documents/templates/meinberlin_documents/document_detail.html, apps/documents/templates/meinberlin_documents/document_form.html, apps/documents/templates/meinberlin_documents/paragraph_detail.html, apps/ideas/templates/meinberlin_ideas/idea_confirm_delete.html, apps/ideas/templates/meinberlin_ideas/idea_create_form.html, apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/ideas/templates/meinberlin_ideas/idea_update_form.html, apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/components/_comments.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_resource_header.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/base.html, meinberlin/templates/base_errors.html
This makes first steps in implementing a new layout where many parts of the UI stretch the full width of the UI. This style requires that layout is not only handled in the base.html file, but scattered throughout the application. So the main challange here is maintainability.
The new layout consists of rows that stretch the full width of the screen. Inside of each row, there is a `div.l-wrapper` that sets the general width. Inside of that, you can optionally use the grid (e.g. using the `.l-center-8` or `.l-center-6` classes). Finally, the content is added inside of that.
The rows tend to have limited semantic value and are mostly used to supply a different background color or a large image. A classic example of a row would be the resource header with a full-width image.
=> Implement full-width layout

apps/ideas/rules.py
Used by the comment widget in `react_comments.py:30`
=> Add missing permission rule to allow user comments

.stylelintrc.json, package.json
The use of `^` in `package.json` is currently inconsitent. I changed it so that all dependencies are pinned and all devDependencies are not pinned.
You can update all devDependencies by simply running `npm update`.
I also updated our stylelint config to remove deprected keywords.
=> (un-)pin js dependencies

apps/documents/templates/meinberlin_documents/document_detail.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/projects/templates/meinberlin_projects/project_detail.html
I already found the frist bug related to the new layout system (#40)!
To reproduce, notice that the comments on the [document detail page](https://meinberlin-dev.liqd.net/projects/text/) are to narrow.
This will probably have a git conflict with #49, but that should be easy to fix.
=> Fix document detail layout

apps/dashboard/templates/meinberlin_dashboard/includes/project_form.html, apps/documents/assets/ParagraphBox.jsx, apps/ideas/templates/meinberlin_ideas/idea_confirm_delete.html, apps/ideas/templates/meinberlin_ideas/includes/idea_form.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/components/_button.scss
I removed the type based button selectors, so now we use classes exclusively. This is a good idea in general, but the trigger to do this now was the mis-styling of the logout button.
=> refactor buttons

apps/projects/templates/meinberlin_projects/includes/phase_indicator.html, apps/projects/templates/meinberlin_projects/includes/phase_popover.html, meinberlin/assets/js/app.js, meinberlin/static/js/popover.js
Fixup for #56:
- small fixes
- use dedicated `popover.js` that is loaded only when needed
- close popover on a click somewhere else on page
=> phase indicator fixup

apps/dashboard/forms.py
Removes the `is_public` field from the project form such that the model default (`True`) is used.
=> make projects created via dashboard public

apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, apps/dashboard/templates/meinberlin_dashboard/dashboard_base.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_list_tile.html, apps/dashboard/templates/meinberlin_dashboard/project_create_form.html, apps/dashboard/templates/meinberlin_dashboard/project_list.html, apps/dashboard/templates/meinberlin_dashboard/project_update_form.html, apps/documents/assets/Paragraph.jsx, apps/documents/templates/meinberlin_documents/document_detail.html, apps/documents/templates/meinberlin_documents/paragraph_detail.html, apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/ideas/templates/meinberlin_ideas/includes/idea_list_tile.html, apps/projects/templates/meinberlin_projects/includes/phase_indicator.html, apps/projects/templates/meinberlin_projects/includes/phase_popover.html, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_commenting.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_menu_layout.scss, meinberlin/assets/scss/components/_phases.scss, meinberlin/assets/scss/components/_popover.scss, meinberlin/assets/scss/components/_resource_header.scss, meinberlin/templates/base.html
There are plenty of conventions for naming classes:
-   [code guide by mdo](http://codeguide.co/#css-classes)
-   [smacss](https://smacss.com/book/categorizing)
-   [bem](http://getbem.com/naming/)
-   [suit](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md)
We use a lot of the bootstrap class names which do not follow strict rules. My goal was to use a more strict system that is still mostly compatible with bootstrap.
The existing code mostly uses something a lot like suit:
.myComponent-element--modifier.is-active
.l-some-layout
I now think that the camelCase is actually doing more harm than good and propose to switch something more like bem:
.my-component__element--modifier.is-active
.l-some-layout
As you can see the only changes are that elements are now prefixed …
=> switch to BEM CSS naming convention

apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, apps/dashboard/templates/meinberlin_dashboard/includes/blueprint_list_tile.html, apps/projects/templates/a4projects/includes/project_list_tile.html, apps/projects/templates/a4projects/project_list.html, meinberlin/assets/scss/_layout.scss
The flex implementation head the issue that the layout in incomplete lines was broken:
1 2 3 4
5     6
1 2 3 4
5  6  7
We thought about using the bootstrap grid which does not have that issue. That would have meant to move all layout into the template, which we ultimately decided against (or at least postponed for now).
This new implementation uses `display: grid`. This is even newer than flex: The [candiate recommendation](https://www.w3.org/TR/css-grid-1/) has been published few weeks ago and the feature is not enabled in any major browser (though [it soon will be](http://caniuse.com/#search=grid)).
To test this, you should enable the experimental feature via a browser flag.
=> refactor tiles

apps/projects/templates/a4projects/includes/project_list_tile.html, meinberlin/assets/scss/components/_tile.scss
right now with placeholder images, obviously they should be replaced when we have project images.
=> proper project tiles

apps/contrib/templates/meinberlin_contrib/widgets/dropdown_link.html, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_filter_bar.scss
This adds a new button modifier `.button--form` which looks like something between a button and an input (specifically, `select`).
This new kind of button is used for the filter dropdowns.
=> Use button styles for filters

apps/dashboard/templates/meinberlin_dashboard/project_list.html, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss
In 497c8d84 I tried to make it possible to use button styles for a dropdown-toggle.
The solution I used there relied on source order: `.button` sets a margin-bottom, `.dropdown-toggle` removes it again. This is fragile because seemingly unrelated code changes could potentially break this.
The underlying issue seems to be that `.button` mixes [structure and skin](https://github.com/stubbornella/oocss/wiki#separate-structure-and-skin). So here I propose to remove the margin-bottom from `.button` instead.
I found only one place where this causes issues and fixed it by wrapping the button in a `<p>` element. There may be more tough.
=> Refactor: Remove margin-bottom from buttons

apps/contrib/mixins.py, apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, apps/ideas/views.py, tests/conftest.py, tests/factories.py
Depends on https://github.com/liqd/adhocracy4/pull/46.
The brainstorming blueprint does not allow rating in its phases. In this case the rating element are not shown.
=> Do not show rating elements if feature is not enabled

meinberlin/static/embed.js
See https://stackoverflow.com/questions/18619186/#18631501
Note that this is also triggered on the initial page load, so the first item in the tab order is always inside of the main area. The header (login/logout) is skipped. I am not sure if this is an issue.
=> embed: jump to top after navigation

webpack.config.js
Webpack does not find dependencies for `npm link`ed modules
that are available in the currently build module.
This is documented at
http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-
don-t-find-their-dependencies
If modules are available in the linked module, as well as the
currently build module, dependencies may be included twice if
the proposed `fallback` option is used.
Setting resolve[Loader].root forces webpack to resolve all
dependencies only once against the local directory.
=> Fix webpack development dependency resolving

docs/embed.md
Adhocracy4 does not itself depend in wagtail. I rephrased the embed docs to point out an alternative if wagtail is not available.
@MagdaN do you think this explains your remark?
=> rephrase embed richtext restriction

apps/contrib/templates/meinberlin_contrib/includes/map_filter_and_sort.html, apps/contrib/templates/meinberlin_contrib/includes/pagination.html, apps/contrib/templates/meinberlin_contrib/widgets/dropdown_link.html, apps/contrib/templatetags/contrib_tags.py, apps/dashboard/templates/meinberlin_dashboard/includes/phase_form.html, apps/dashboard/templatetags/form_tags.py, apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, apps/mapideas/views.py, apps/projects/templates/meinberlin_projects/includes/phase_indicator.html, meinberlin/assets/scss/components/_button.scss
Most importantly, this allows to switch between list and map mode. All filters, ordering, and pagination are preserved. The pagination is ignored in map mode. The default mode is list.
Note that as part of this pull request, I refactored the button styling, notably the `button--select` modifier.
Some possible next steps:
-   define filters
-   when changing view, jump directly back to the list/map
-   zoom buttons on the map are missing
-   the leaftlet popups need styling
-   the filterbar should overlap the map (see #166)
=> Fix map list UI

apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/assets/scss/components/_map.scss
I would like to refactor how this is handled in core, but for now I just added the missing controls here.
=> add missing zoom controls to map list

requirements/dev.txt
Currently flake8-docstrings is broken with pydocstyle 2.0.0
This prevents pyup from updating pydocstyle. This is only temporary
required until the bug is fixed in flake8-docstrings
[0] https://gitlab.com/pycqa/flake8-docstrings/issues/19
=> Fix pydocstyle for pyup until flake8-docstrings is fixed

.stylelintrc.json, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_fixed_side.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_hero_unit.scss, meinberlin/assets/scss/components/_resource_header.scss
In media queries, we sometimes use `min-width` and sometimes `max-width`. This results in issues like #259. This pull request fixes this by using `min-width` wherever possible. i chose `min-width` rather than `max-width` according to the "mobile first" approach.
The notable exception is `.main-header__user .dropdown`. I have no clue how we can fix that case because the mobile and desktop styles are so different.
Media Queries Level 4 (working draft) adds [a new syntax](https://drafts.csswg.org/mediaqueries-4/#mq-range-context) that would fix this issue. But it is not widely available yet.
=> mobile first media queries

apps/budgeting/rules.py, apps/budgeting/views.py, apps/dashboard/mixins.py, apps/dashboard/views.py, apps/mapideas/rules.py, apps/mapideas/views.py, apps/organisations/rules.py, apps/polls/views.py, apps/topicprio/views.py
We have decided on permission naming in core. See https://github.com/liqd/adhocracy4/pull/79
Changes:
- use  `add_project` core permission in dashboard
- use  `add` instead of `create`
=> Permission naming

meinberlin/assets/scss/components/_alert.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_menu_layout.scss
I gave the header a generic `margin-bottom` now, which added some necessary space underneath the header. This allowed me to remove the `margin-top` for the dashboard layout, following the logic that we prefer `margin-bottom` over `margin-top`. 
This fixes #82.
=> tackle header margin problem

meinberlin/settings/base.py, meinberlin/templates/email_base.html, requirements/base.txt
This introduces a new content_html block to the mail templates which can
be used to explictly define HTML emails.
If this block is not defined a fallback is used, that captures the
output of the standard text content and converts linebreaks to html.
For this feature a new dependency to django-capture-tag is introduced.
=> Mails: Add content_html block with a fallback that converts linebreaks

apps/bplan/templates/meinberlin_bplan/statement_create_form.html, apps/bplan/templates/meinberlin_bplan/statement_sent.html
Improve line length on large displays (e.g. when used on the platform).
Note that I did not use `l-center-6` because it would not use all available space on small screens (e.g. small iframes).
side node: with all possible error messages displayed, the embed needs a height of ~1024px on my system in order not to require scrollbars.
=> limit bplan width

apps/contrib/static/js/Alert.jsx, apps/polls/assets/PollManagement.jsx, apps/polls/assets/Question.jsx
-   do not close alerts automatically after timeout
-   allow users to close alert manually (like in embed shell)
-   the alerts in the document app should be adapted in a similar way
-   the poll alerts (both in mgmt and detail) should have a margin-bottom. I could not think of a quick way to do this.
https://en.wikipedia.org/wiki/Issus,_Cilicia
=> tweak poll alert closing behavior

apps/polls/models.py
SQL does *not* give any guarantees on the row order, so an explicit order command is required even to sort on the primary key / id.
Unfortunately i can't reproduce the ordering problem on my local system with sqlite, as it does sort by default on the the. But the explicit order should fix the problem with postgres.
Fixes #373
=> Add default ordering by id to poll choices

webpack.config.js
fixes #334
Before this, webpack would generate the following (invalid) code:
var leaflet.draw = …
Now, the it will be more like this:
this['leaflet.draw'] = …
Since this code is executed in the global scope (and this therefore refers to `window`), it should result in the same thing, just with valid syntax.
=> fix broken variable name in webpack

meinberlin/assets/scss/components/_embed_layout.scss
This avoids changing the available width when navigating or changing tabs.
=> always show vertical scrollbar in embed shell

webpack.config.js
The docu states, that the output directory has to be an absolute path.
see https://webpack.github.io/docs/configuration.html#output-path
=> Webpack: Use absolute output path

apps/budgeting/forms.py, apps/budgeting/migrations/0002_proposal_point_label.py, apps/budgeting/templates/meinberlin_budgeting/includes/proposal_form.html, apps/budgeting/templates/meinberlin_budgeting/includes/proposal_list_item.html, apps/budgeting/templates/meinberlin_budgeting/proposal_detail.html, apps/mapideas/forms.py, apps/mapideas/migrations/0002_mapidea_point_label.py, apps/mapideas/models.py, apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_form.html, apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_list_item.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_detail.html
The point label is an optional text field that can be used to describe the point selected on the map. for example "Alexanderplatz", "Rollbergstr. 15", "Liqd Büro" etc.
=> Add point_label field to mapideas

meinberlin/assets/scss/components/_comments.scss
a3 did, opin does it, so we should do it too!
I did not find any other places where we use a single TextField for something that is actually visible in the UI.
=> preserve newlines in comment text

meinberlin/assets/scss/components/_hero_unit.scss
note that the bottom-alignment (and therefore the color contrast) now depends on flexbox.
=> avoid overflow in hero unit (fixes #371)

apps/account/templates/meinberlin_account/account_dashboard.html, apps/account/urls.py, apps/account/views.py, meinberlin/assets/scss/_shame.scss, meinberlin/settings/base.py, meinberlin/templates/account/base.html, meinberlin/templates/account/email.html, meinberlin/templates/account/email_confirm.html, meinberlin/templates/account/password_change.html, meinberlin/urls.py
Followup to #429
Use the allauth default routes and overwrite the allauth templates
instead of using a new view. The templates relevant for the account-
dashboard are inheriting from the account_dashboard.html to display the
navigation.
=> Use allauth routes and overwrite templates

apps/dashboard/blueprints.py, apps/dashboard/forms.py, apps/dashboard/mixins.py, apps/dashboard/templates/meinberlin_dashboard/includes/external_project_list_item.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_list_item.html, apps/dashboard/templatetags/dashboard_tags.py, apps/dashboard/views.py, apps/projects/templates/meinberlin_projects/project_detail.html, apps/projects/views.py
We currently store `blueprint.title` as `project.typ` when creating a
project. Unfortunately, this will write the translation that is used for
the creator into the database.
This pull request adds a filter that maps a blueprint key to the
translated title. This way, we can store the key into the database and
get the ranslation in the template where it is displayed.
=> use template filter to get translated blueprint name

apps/users/templates/meinberlin_users/user_detail.html, apps/users/urls.py, apps/users/views.py, meinberlin/urls.py
This adds a simple user profile. Its main purpose is to fix the broken links on comments.
The information that is shown is username, join date and followed projects. Is this ok or should we keep some of that information private?
The implementation is based on a4-opin. I am not completely sure whether the selection of projects is useful in our context. Maybe it would also be good to ignore archived projects to not end up with hundrets o projects over time.
=> simple user profile

apps/cms/models.py
fixes #422
While working on this, I found a bug in wagtail: When leaving the project choice widget empty, you will get a 500 error on submit. I was not yet able to reproduce that issue in an isolated unit test though.
This issue is relevant because with this pull request a project that was once available for selection may become unavailable. Users that try to edit the frontpage after that will run into the described issue.
=> Filter wagtail project choice options

apps/contrib/templates/meinberlin_contrib/includes/form_checkbox_field.html, apps/contrib/templates/meinberlin_contrib/includes/form_field.html, apps/contrib/templates/meinberlin_contrib/includes/form_field_with_addon.html, apps/dashboard/templates/meinberlin_dashboard/includes/phase_form.html, apps/dashboard/templates/meinberlin_dashboard/project_moderators.html
This is more of a proposal.
I think that translating variables can mask missing translations in other places. It is better to translate string literals directly. A common case is verbose names on model fields (see https://github.com/liqd/adhocracy4/pull/101)
=> avoid to translate variables

apps/account/views.py, apps/budgeting/views.py, apps/dashboard/filtersets.py, apps/dashboard/forms.py, apps/dashboard/mixins.py, apps/dashboard/views.py, apps/ideas/views.py, apps/kiezkasse/views.py, apps/mapideas/forms.py, apps/mapideas/views.py, apps/topicprio/views.py, apps/users/fields.py, apps/users/forms.py
Class properties may be evaluated on module load time when the users
locale is not available yet. Thus it is necessary to use ugettext_lazy
to show a correct translation.
For consistency the ugettext_lazy method is imported as `_` if it is
required in a single case. This is in accordance with the django docs
[1,2].
ugettext_lazy can be used as a replacement of ugettext in most cases, as it acts like a **unicode** string object. But it can't be used if the string is handled as a _bytestring_ (**str** object). 
In templates string operations on lazily translated strings can be used as usual.
*Attention*: If a default `LANGUAGE_CODE="de-de"` is set in the `local.py` settings, the failures may not be reproducible.
[1] https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#standard-tran …
=> Import ugettext_lazy as _ if used as a class property

apps/embed/templates/meinberlin_embed/embed.html, apps/embed/views.py
note that the criterium is whether the project is external, not if it is a bplan. This should work for now, but we may have to change it later on.
=> hide platform link and user indicator for bplan embed

apps/documents/templates/meinberlin_documents/document_detail.html
this allows to link to individual paragraphs
I would have liked to have semi-human-readable ids that are generated from the paragraph title, but I could not find a utility function that does the conversion just yet.
=> add ids to paragraphs

meinberlin/assets/scss/_base.scss
example: https://mein.berlin.de/paragraphs/192/
=> overwrite inline styles of richtext images

locale/de/LC_MESSAGES/django.po
The msgid has to be exactly the same in all translations.
And unfortunatly it is not possible to have the origin of the translated
string to end on a newline while the actual translation does not. Thus
it is necessary to add an empty line to translation.
=> Fix signup terms of use translation

apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, apps/contrib/templates/meinberlin_contrib/includes/filter_and_sort.html, apps/contrib/templates/meinberlin_contrib/includes/map_filter_and_sort.html, apps/documents/models.py, apps/documents/templates/meinberlin_documents/chapter_detail.html, apps/documents/templates/meinberlin_documents/includes/nextprev.html, apps/documents/views.py, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, apps/polls/templates/meinberlin_polls/poll_detail.html, apps/topicprio/templates/meinberlin_topicprio/topic_list.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_list.html, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_document.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_module.scss, meinberlin/assets/scss/style.scss
builds on #522 
This implements both the new document detail styling and styling for chapter navigation. Still to do: The table of content should be in an accordion.
Note that there was some styling-related refactoring, so @vellip should have a look.
=> chapter styling

meinberlin/templates/account/login.html, meinberlin/templates/socialaccount/connections.html, meinberlin/templates/socialaccount/snippets/provider_list.html
This is my porposal for service konto styling. The idea is to make it as simple as possible because service konto is currently our only SSO option. Note that I removed the possibility to add more account connections once the servicekonto is connected.
@damusp what do you think?
=> style service konto login

apps/actions/apps.py, apps/actions/signals.py, apps/contrib/signals.py
There is 9 year old bug report where the problem is discussed:
https://code.djangoproject.com/ticket/9318
=> Connect all signals from a Proxy model to its parent

apps/actions/models.py, apps/notifications/emails.py, apps/notifications/signals.py
Moderators did not get any emails as there was a regression bug
introduced with the default email language.
This commit also enforces the use of the meinBerlin Action proxy when
using signals.
Note, that signals for Actions are not automatically bubbled down to
proxies, as discussed in https://code.djangoproject.com/ticket/9318
=> Fix email notifications

apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/assets/scss/components/_document.scss
This makes the chapter TOC collapsible and collapses it on all chapter detail
pages, except for the first one.
It uses bootstrap's [collapse component](https://v4-alpha.getbootstrap.com/components/collapse/).
=> collapse chapter TOC

apps/actions/blocks.py, apps/actions/models.py
Add a custom QuerySet that allows to filter public actions.
An action is public if it is either not connected to a project or the
project is published and public.
=> Filter public actions

apps/contrib/management/commands/makemessages.py
Fixes #560
Most importantly, this avoids importing strings from adhocracy4/node_modules.
=> Only inlcude js strings from a4 apps

apps/organisations/admin.py, apps/projects/admin.py
With a large user base (>20000) the multi choice widget from django
admin gets unresponsive.
=> Use raw_id_field for user selection

apps/budgeting/migrations/0011_allow_blank.py, apps/kiezkasse/migrations/0007_allow_blank.py, apps/moderatorfeedback/models.py, apps/organisations/admin.py
While moderator statements had been optional (null=True) they had been
marked as required in forms, because the (blank=True) option was not
set.
Fixes #575
=> Allow blank moderator statements

apps/projects/templates/meinberlin_projects/project_detail.html
Used permission does not exist.
Button was working only for admin users, as there permissions are not checked.
=> Fix project edit button

apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, apps/topicprio/templates/meinberlin_topicprio/includes/topic_list_item.html, apps/topicprio/templates/meinberlin_topicprio/topic_detail.html, meinberlin/assets/scss/components/_item_detail.scss
As topics are created by the same initiator at one time, having this information shown looks weird and is not interesting for the users.
=> Do not show user and date of topics

apps/budgeting/views.py, apps/dashboard/templates/meinberlin_dashboard/includes/project_list_item.html, apps/dashboard/templatetags/dashboard_tags.py, apps/dashboard/views.py, apps/exports/apps.py, apps/exports/urls.py, apps/exports/views.py, apps/ideas/views.py, apps/kiezkasse/views.py, apps/mapideas/views.py, apps/topicprio/views.py, meinberlin/settings/base.py, meinberlin/urls.py, tests/conftest.py, tests/exports/conftest.py, tests/exports/factories.py, tests/exports/test_csv_export.py, tests/exports/test_item_exports.py, tests/factories.py
The export framework is designed with extensibility in mind, while the current implementation only allows for exporting "anything which looks like a item list"
Furthermore until now it is only allowed to have on export view per project. In the future it may be possible to select different exports for a project. For example for different modules.
=> Add an export framework and item export functionality

apps/exports/views.py, requirements/base.txt
This is using xlsx instead of csv for data exports. This should allow for Microsoft Excel to import the data on all platforms.
Unfortunately the exported data is not perfect, as it is still tailored to the flat CSV structure. So comments are remaining in a single field and dates are emitted as strings. 
The main purpose of this PR is to allow for easier opening of exports. Reformatting the export for example to multiple spreadsheets etc. would be a new user story
=> Use xlsx format for data exports

apps/contrib/views.py
CreateViews provide the a failing get_object method which should not be called when validating the object project.
=> Fix project dispatcher for bplan projects

package.json
The information is mostly copied from a4-core. It is useful in case we
ever publish this project to npm.
=> Extend package.json

locale/de/LC_MESSAGES/django.po, meinberlin/apps/account/templates/meinberlin_account/account_dashboard.html, meinberlin/apps/account/templates/meinberlin_account/actions.html, meinberlin/apps/account/templates/meinberlin_account/profile.html, meinberlin/apps/account/urls.py, meinberlin/apps/account/views.py, meinberlin/apps/actions/templates/meinberlin_actions/blocks/platform_activity_block.html, meinberlin/apps/actions/templates/meinberlin_actions/includes/action.html
This adds an activity stream to the user dashboard. The purpose is *not* to be a public record of a user's activities, but to allow users to see what happened in the projects (or other resources) they follow.
Note:
-   Someone should double check that no private information is leaking via actions (e.g. private projects).
-   If I am not logged in the page currently throws an error. I did not find out why.
-   The UI still needs some work.
-   Filtering actions by follows could be moved to core. But it will also get more complicated once it is possible to follow resources other than projects.
=> user activity stream

meinberlin/apps/initiators/apps.py, meinberlin/apps/initiators/emails.py, meinberlin/apps/initiators/forms.py, meinberlin/apps/initiators/templates/meinberlin_initiators/emails/initiator_request.de.email, meinberlin/apps/initiators/templates/meinberlin_initiators/emails/initiator_request.en.email, meinberlin/apps/initiators/templates/meinberlin_initiators/request.html, meinberlin/apps/initiators/urls.py, meinberlin/apps/initiators/views.py, meinberlin/config/settings/base.py, meinberlin/config/urls.py
This adds a simple form at http://localhost:8000/initiators/request/ which can be used by regular users to request initiator permissions. An email will be send to `settings.CONTACT_EMAIL`.
Note that currently there is only an informal `organisation_name` field. We could change this to a select box of all existing organisations. This would provide us with enough information to allow admins to accept the request with a single click of a button. I am not sure though whether that is desirable/required.
=> initiator request

meinberlin/apps/topicprio/views.py
Adds a free text filter to topic prioritization projects so you (as a user) are able to search for specific topics.
=> Add free text filter to topic prioritization projects

meinberlin/apps/cms/templates/meinberlin_cms/blocks/projects_block.html, meinberlin/assets/scss/_layout.scss
After talking to @damusp about it, we found it's nicer to have the `.l-center-6` 100% wide on mobile. Otherwise it looks more like a bug than desired.
=> mobile layout

meinberlin/apps/embed/middleware.py, meinberlin/config/settings/base.py, meinberlin/config/settings/dev.py
* Update to django 1.11 middlewares (see https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware)
* Disable django debug toolbar until wagtail 1.12 is released (see jazzband/django-debug-toolbar#950 for reference)
=> Update to django 1.11 middlewares and disable debug toolbar

meinberlin/assets/scss/components/_alert.scss
there was a margin that did not belong
=> fix tablist after alert message

meinberlin/apps/dashboard2/__init__.py, meinberlin/apps/dashboard2/components.py, meinberlin/apps/dashboard2/dashboard.py, meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/mixins.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard_project.html, meinberlin/apps/dashboard2/views.py
This PR introduces a `get_progress(project_or_module)` method on the DashboardComponent Interface. 
This get_progress is used to show error notes in the menu and display the progress bar. 
During the development specialized abstract Components for forms were introduces.
The progress / error counting has to be done on the models as it is not possible to reliably convert a model object to a POST data dict.
For example: phase.start_date may be split into two fields by the datetimepicker widget. Thus two separate values are expected in the POST data dict, which will be merged after the initial validation. But fields/widgets are not holding any information about the expected POST data fields.
=> Add dashboard error count and set form fields to required for published projects

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard_project.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/progress.html, meinberlin/apps/dashboard2/urls.py, meinberlin/apps/dashboard2/views.py
This PR adds a separate view that acts as the target of the form containing the (un) publish button inat the progress indicator.
It ensures each required field of a project and its modules is present. 
*Note: Currently this is done by checking the progress explicitly. But this could be replaces by some kind of signal/callback functionality that would be called prior to publishing. This callback could also check more complicated conditions like: allow publishing only if phases are non overlapping*
The view redirect to the previous page. Or the default project-update page if the previous page can not be detected.
=> Allow to (un)publish projects

meinberlin/apps/dashboard2/mixins.py, meinberlin/templates/meinberlin_dashboard2/base_dashboard.html
ToDo:
@xi, @vellip could you please take a look at the issue with the dropdown?
=> Show other_organisations_of_user in dashboard top menu

meinberlin/apps/polls/views.py
This is a temporary workaround. Longterm we should define the module in the URL directly.
=> fix poll management with multi module

requirements/base.txt
Pip apparently needs an egg for vcs. https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
=> add egg for multiform

meinberlin/apps/initiators/emails.py, meinberlin/config/settings/base.py
Add SUPERVISOR_EMAIL setting
Supervisors should e.g. receive notifications about initiator requests.
Note that supervisor-berlin@liqd.net is not set yet. Before deployment it should be set up and redirected to the correct supervisor addresses.
Note also, that this is an ugly hack, as we should define the role supervisor on the User model if we'd really need them and then adapt get_receivers to return the users with the supervisor role.
=> Fix missing initiator request emails for the supervisor

meinberlin/apps/dashboard2/components.py, meinberlin/apps/dashboard2/contents.py, meinberlin/apps/dashboard2/dashboard.py, meinberlin/apps/offlineevents/dashboard.py
If the weight is the same, the identifier is used to get a constant order.
If this will be required some day it would be possible to use a weight @property which determines the weight from a setting.
=> Sort components by weight

meinberlin/apps/dashboard/forms.py, meinberlin/apps/dashboard2/views.py
Set valid module name and description from project.
Will be replaced by module type and user input in the new dashboard.
=> Temporary set single module name and description

meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_field_with_addon.html, meinberlin/apps/dashboard/templates/meinberlin_dashboard/includes/users_from_email_form.html, meinberlin/apps/polls/assets/ChoiceForm.jsx, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/_mixins.scss, meinberlin/assets/scss/components/_addon.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_datepicker.scss, meinberlin/assets/scss/components/_input_group.scss, meinberlin/assets/scss/components/_upload.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/a4filters/widgets/free_text_filter.html, meinberlin/templates/a4images/image_upload_widget.html
fixes #469
-   `input-addon` is renamed to `input-group`
-   `btn-group` and `input-group` are still separate
-   `input-group` does no longer require `btn-group` if buttons are involved
-   image upload uses `input-group`
-   datepicker uses `input-group`
Note that `input-group` is the same name that is also used in bootstrap, but the element classes (e.g. `input-group__input`) is not compatible.
=> refactor input-group

meinberlin/assets/scss/_form.scss
This colors the border of input on focus blue, on all browsers. Additionally we can now show focus for the ckeditor.
fixes #705
=> streamline input focus styling

meinberlin/apps/dashboard2/dashboard.py, meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/module_areasettings_form.html, meinberlin/apps/dashboard2/views.py
As FormSets won't work with OneToOne relations AreaSettings now have a custom form which is replacing the forms instance with the modules settings_instance. 
Note: The settings concept is still broken as OneToOne makes no sense at all. But this brings back the current functionality. Settings should be discussed at SoS
=>  Add Area Settings component 

meinberlin/apps/dashboard2/__init__.py, meinberlin/apps/dashboard2/components/__init__.py, meinberlin/apps/dashboard2/components/forms/__init__.py, meinberlin/apps/dashboard2/dashboard.py, meinberlin/apps/documents/dashboard.py, meinberlin/apps/exports/dashboard.py, meinberlin/apps/offlineevents/dashboard.py, meinberlin/apps/polls/dashboard.py, meinberlin/apps/topicprio/dashboard.py
Everything on a component (get_menu_label and get_progress ...) may only be called if is_effective is True.
This allows effectively to replace get_menu_label(project_or_module) with a fixed label property.
Furthermore it prevents to have to double check on module types at many places
=> Add explicit is_effective check to components

meinberlin/apps/dashboard2/apps.py, meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/mixins.py, meinberlin/apps/dashboard2/signals.py, meinberlin/apps/dashboard2/views.py
Note that the project_pre_publish signal may be used to prevent from publishing if
any connected handler returns an error message.
The create signals are derived directly from the db signals. Unfortunately this is not easily possible for the other cases as they require a before/after knowledge.
=> Add dashboard signals

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
After talking to PMs we decided not to show the result tab automatically when the project is over.
=> Do not show result tab automatically

meinberlin/apps/users/models.py
we got the feedback that the connection between "email", "notification", and "follow" is not completely clear.
@janaba what do you think of this change?
=> clearify connection between "notification" and "follow"

meinberlin/assets/scss/components/_button.scss
=> avoid double borders on button groups

meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_fixed_side.scss
fixes #518
We already did hide the feedback button on small screens. But there was a rather large area in which we could not be reasonably sure that nothing is covered. This is fixed now.
Note that the feedback form is already linked in the footer, so the information is still available.
=> only show feedback button on large screens

meinberlin/assets/scss/_form.scss
The default focus style in chromium (a light blue outline) was removed in #732. I believe that consistency across pages is more important than consistency across browsers (because users rarely change their browser but spend a lot of time with the same browser on other people's pages).
So I propose to restore the outline.
=> restore default browser focus style

meinberlin/assets/scss/components/_datepicker.scss
=> fix huge focus box on datepicker in firefox

meinberlin/assets/scss/_shame.scss
our buttons were renamed to `.btn` in #699, so the styling already applies.
=> remove unnecessary @extend from follow styling

meinberlin/apps/dashboard2/forms.py
The category form always displays 3 empty fields. This is confusing, especially when I remove them and submit, just to find that they are back.
I talked to @damusp and we thought that it would be nice to show the 3 empty fields only when there are no categories.
When trying to implement this, I only found the `min_num` parameter which would lead to strange results when trying to create less then 3 categories (if I manually remove the fields it works fine, but not if I leave them empty).
In the end I simply reduced the number of extra fields to 1. @damusp what do you think?
=> reduce number of extra category fields to 1

meinberlin/apps/dashboard/templatetags/dashboard_tags.py, meinberlin/apps/dashboard2/blueprints.py, meinberlin/apps/dashboard2/mixins.py, meinberlin/apps/dashboard2/views.py, meinberlin/apps/projects/views.py
`get_blueprints()` dashboard2/blueprints.py is importing the module from the settings (in our case dashboard/blueprints.py) which is importing `ProjectBlueprint` from dashboard2/blueprints.py
```
dashboard2/blueprints.py 
[ blueprints = _get_blueprints()  ->  importlib.import_module ]
dashboard/blueprints.py 
[ from meinberlin.apps.dashboard2.blueprints import ProjectBlueprint ]
dasboard2/blueprints.py
```
I am not sure why this has not been a problem yet. Maybe because only some metehods/classes are imported?  @2e2a  @xi  do you have any idea how python resolves this?
=> Remove potential circular import

.gitignore, Makefile
Fixes #799
I am not relatlivly sure that `npm install` is what we want. I am not
sure whether it is bug-free, but that is another question.
package-lock.json should not do any harm, but I do not see any benefit
in committing it to the repo. We did not have trouble with different
versions on different systems so far and it might cause issues when
using `npm link`. So I added it to .gitignore.
=> Revert to npm install

meinberlin/apps/contrib/static/js/ajax_modal.js
Fixes #795 
The fix is duplicated from embed.js: The content of the embed is loaded via ajax. Apart from the content, we also need to extract the script elements from the downloaded page and add them to the current one.
=> load new scripts in ajax modal

meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_field.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_field_with_addon.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/form_field.html
fixes #406
There was the feeling that not all forms should have the asterisks (e.g. login). It was not clear though how to differeenciate the two cases. The decision was to just add it everywhere for now and add exceptions later (if required).
=> add asterisk to required fields

meinberlin/apps/contrib/static/js/ajax_modal.js
The core problem was a missing `overflow-y: auto;` on the modal.
It was missing because the body was missing the `modal-open` class which
is set via the Bootstrap javascript when a modal is opened. As we did
not initialize the modal via javascript but rather tried to simply use
the classes directly on the html elements the scrolling has not been
enabled.
Using the javascript initialization also fixes the need for the custom
creation of a backdrop, as this will created and removed automatically
by bootstrap.
Furthermore the modal was not added to the body but rather somewhere in
the dom tree which is advised against by the bootstrap docs:
> Modals use position: fixed, which can sometimes be a bit particular
> about its rendering. Whenever possible, place your modal HTML in a
> top-level …
=> Enable scrolling in long modals

meinberlin/apps/documents/assets/DocumentManagement.jsx
Fixes #754
CKEDITOR does not fire change events in the DOM when the field is
modified. This is the simplest but kinda hacky solution to fix #754.
It requires knowledge about the child components inner structure.
Fixing the problem at its core would be possible if we'd handle change
events on the CKEDITOR editor instance, adapt the textarea accordingly
and fire change events manually. For example like:
```
window.CKEDITOR.on('instanceReady', (e) => {
e.editor.on('change', (e2) =>  {
$textarea.value = e2.value
$textarea.change()
})
})
```
But this is out of the scope of this issue
=> Remove alerts on CKEDITOR fields change

meinberlin/templates/meinberlin_dashboard2/includes/project_list_item.html
Fixes #817
As the duplication code will be part of the a4 dashboard it would be
very complex to make the duplication code extensible and allow for
correct duplication of external and bplan projects.
Duplication of external and bplan projects is still possible but the
duplicated project looses its "type".
This PR simply hides the duplication from the user.
=> Hide dropdown menu and disable button for external projects

meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html
fixes #559
the document is shown on the project detail page where the project title
is `h1`. So it needs to start at `h2`.
=> fix heading hierarchy for documents

meinberlin/assets/scss/_form.scss
We have general styling for input elements. This is meant for input elements which look roughly like text input (which is most of them: password, url, date, email, number, …). However, there are also few input elements that are very different, notably checkbox and radio.
Chromium mostly ignores our styling for these elements, but IE adds a boirder and padding around it. This pull request removes them.
I did it this way instead of excluding checkboxes and radios from the initial styling to keep the selectors short and simple.
=> avoid styling checkboxes

meinberlin/assets/scss/_form.scss
placeholders were often confused for actual input
=> lighter placeholders

meinberlin/apps/bplan/management/commands/bplan_auto_archive.py
After a bplan is archived it's related statements may be deleted.
For simpler development/deployment the auto_archive script is extended
to delete the statements, altough it may have been possible to add
another command.
To prevent from loosing statements that are created just before the
participation ends, the deletion is delayed for 48 hours.
(In rare cases a statement may not have been sent due to the async
nature of our email interface, when the project is already archived)
=> Delete statements from archived bplans

meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/includes/container_detail.html, meinberlin/assets/scss/components/_project_header.scss, meinberlin/config/settings/base.py
the logos should be in a square box. In most cases we crop images, but
here we add a white background to make it fit.
=> add logo to container detail page

meinberlin/apps/maps/management/commands/import_geodata.py
There were two problems fixed
1. The berlin WFS service changed its default interface version >2.0 and
the outdated gdal lib on our servers only supported version 1.1.0.
Thus it was neccessary to add the VERSION parameter to the url
2. The Feature keys have changed (BEZIRK was renames to BEZNAME)
=> Fix geo import from berlin fisbroker (fixes #863)

meinberlin/apps/budgeting/views.py, meinberlin/apps/contrib/filters.py, meinberlin/apps/contrib/mixins.py, meinberlin/apps/contrib/views.py, meinberlin/apps/ideas/views.py, meinberlin/apps/kiezkasse/views.py, meinberlin/apps/mapideas/views.py, meinberlin/apps/maptopicprio/views.py, meinberlin/apps/topicprio/views.py
This adapts meinBerlin to liqd/adhocracy4#193 
It furthermore refactors the ChoicesRequestMixin in the same way to get rid of the necessity to add project / module to the request.
=> Adapt to core category filters

meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_detail.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_detail.html, meinberlin/config/settings/base.py
The configuration option was missing.
Reporting was disabled for map|topicprio as the content is generated by the trusted initiators.
=> Enable categories and disable reporting for map|topicprio 

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
The wording is the same as in the timeline, but as bplan projects don't have an info etc. the default project detail (which is shown prior to phases) looked broken.
=> Show a simple notice on bplan embeds if participation has not started yet

meinberlin/apps/contrib/widgets.py, meinberlin/apps/projectcontainers/forms.py, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_select2.scss, meinberlin/assets/scss/style.scss, package.json, webpack.config.js
This is a proposal to add [select2](https://select2.org/getting-started/basic-usage) as a dependency. It greatly improves usability of select elements, especially for multi-selects and if there are many options. It even has decent accessibility!
On the downside, it depends on jquery and adds about 200kb to our frontend bundles (increase by 12% for js/css).
I have been thinking about adding this for a while. The trigger to do this now is the bad usability of the multi select element that is used to select projects in containers. We tried to imrpove that in 91470562b by adding resizing, but that is not enough and actually not supported in IE and safari.
=> add select2

meinberlin/apps/projects/forms.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html, meinberlin/apps/projects/views.py, meinberlin/apps/users/fields.py
The uploaded file has to be a utf8 compatible text file that may contain emails. 
The addresses are scraped without further regard to a maybe existent logical document structure. 
While everything that looks like an email is found only valid emails are returned.
=> Allow user invites via file upload

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_alert.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/base.html
I also took the time to change the styling of our alerts. Before, alerts were often made up ad-hoc and were very inconsistent. With this PR they now look a lot like the [bootstrap alerts](https://getbootstrap.com/docs/4.0/components/alerts/). This includes adjusting some colors, most notably `$brand-danger` which is now a bit darker and therefore more distinguishable from our `$brand-primary` magenta.
=> show warning on draft project detail

meinberlin/apps/users/templates/meinberlin_users/indicator.html, meinberlin/templates/account/email.html, meinberlin/templates/account/login.html, meinberlin/templates/account/logout.html, meinberlin/templates/account/signup.html
We had a problem in the user profiles in ae and opin: https://github.com/liqd/a4-advocate-europe/issues/527
Currently there shouldn't be a problem in meinBerlin, but just to make sure, this PR urlencodes all next-parameters.
=> make sure next parameters are urlencoded

meinberlin/apps/users/templates/meinberlin_users/indicator.html, meinberlin/templates/account/login.html, meinberlin/templates/account/logout.html, meinberlin/templates/account/signup.html
This is a fixup to #942
Steps to reproduce the issue:
-   Go to http://localhost:8000/?foo
-   Log in/out
-   With this path you will end up back on http://localhost:8000/?foo
-   Without this patch, you will end up on http://localhost:8000/%3Ffoo because the URL was encoded twice
=> Revert part of 3d8b15e

meinberlin/apps/users/admin.py
This allows to see which users are actually active.
The default django date filter is surprisingly good for our purpose here.
=> allow to filter user list in admin by last login

Makefile
-   use uglify
-   no sourcemaps (also see https://github.com/liqd/adhocracy4/issues/86)
-   activate react optimization by setting NODE_ENV to "production"
With these optimizations, the bundles shrink significantly:
before      after
adhocracy4.js     295 kB     134 kB
datepicker.js     158 kB    56.6 kB
leaflet.draw.js    67.7 kB    64.3 kB
leaflet.js     429 kB     137 kB
select2.js     162 kB    65.5 kB
embed.js    6.33 kB     2.8 kB
vendor.js     1.1 MB     301 kB
adhocracy4.css    84.8 kB    67.4 kB
vendor.css    50.6 kB    41.4 kB
leaflet.css      14 kB    11.1 kB
datepicker.css    18.4 kB    16.3 kB
leaflet.draw.css    6.25 kB    5.43 kB
Note that these are file sizes. The effect could be less if you count in gzip.
I am not sure what we need to do in order to get this into the …
=> add webpack make target for production

meinberlin/apps/projects/views.py
as found out when investigating #953 pending email invites had not been filtered by project. thus an email could be invited only to a single project. this pr fixes this by filtering the invite on the project.
=> Filter pending emails on project

meinberlin/apps/projectcontainers/models.py, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/includes/container_detail.html, meinberlin/apps/projects/query.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, meinberlin/apps/projects/views.py
The project list within containers will be filtered by the permission of
the currently logged in users. Only projects that may be viewed by the
user are listed.
Furthermore this adapts the number of active and total projects.
For public containers it only counts published projects that are public
and not archived.
In the future (if containers may be private) the count for private
containers should reflect the total number of published, not archived
projects.
Furthermore this makes  the ORM project list filtering reusable.
=>  List container projects only if user may view them

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
-   If you embed a project that is inside of a container, the link back to the container should be treated as an external link.
-   If you embed a container, the link from a project back to the container should be handled as an internal link.
As we do show embed code for projects but not for containers, I think it is reasonable to ignore the second case.
=> open link to container outside of embed

meinberlin/apps/maptopicprio/dashboard.py
fixes #970
This may not be the best approach from a usability perspective, but it is simple and better than just showing a broken map widget.
=> maptopicprio: hide places dashboard component if polygon is not set

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, meinberlin/assets/scss/_shame.scss
I am not totally convinced of this one. The candidates are.
-   http://fontawesome.io/icon/folder-open/ - what we use now
-   http://fontawesome.io/icon/clone/ - doesn't really work semantically
-   http://fontawesome.io/icon/th-large/ - looks like the windows logo
-   http://fontawesome.io/icon/th/ - okayish
I went with `th`, but it does not really looks centered in chromium (it looks fine in firefox).
=> change container icon

package.json, webpack.config.js
babel-preset-env is similar to autoprefixer in that it will configure babel to only apply transformations that are necessary for your target browsers.
This fixes a warning on npm install:
```
WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```
=> switch from babel-preset-2015 to babel-perset-env

webpack.config.js
Without this, the call to `require('shariff')` in app.js will pull in the es6 sources of shariff. We tell babel to ignore most stuff from node_modules (due to issues in the past), so it will not be transpiled.
The fix is to pull in the pre-build file instead.
=> alias shariff in webpack config

meinberlin/assets/scss/components/_map.scss, webpack.config.js
The styling is analogues to the bplan map: https://github.com/liqd/django_zbp/blob/master/bplan/static/scss/components/_markers.scss
=> Style markercluster and improve printing of plans

meinberlin/apps/contrib/staticfiles.py, meinberlin/config/settings/production.py
Trying out cachebusting provided by djangos `ManifestStaticFilesStorage`  as suggested in https://github.com/liqd/a4-meinberlin/issues/948.
Notes:
-  `collectstatic` needs to be called twice. Once with the default storage and once with  the ManifestStaticFilesStorage.
- The strict standard ManifestStaticFilesStorage did not work. As far I understood, this works only when the manifest file is predefined.
- Worked for CSS, Images and JS, but did break our react components.
=> ManifestStaticFilesStorage Cachebusting

meinberlin/apps/contrib/templatetags/contrib_tags.py
The `date` and `time` template filters expect the value in localtime.
=> Fix html_date template tag timezone handling

meinberlin/assets/scss/components/_button.scss
Explicitly setting height fixes cases where line-height is ignored (e.g.
select) but breaks cases where the padding or line-height is changed.
I am not sure which is the best solution. For now I went with setting
the height every time the padding is overwritten.
=> Fixup 5591ddc28

meinberlin/apps/plans/assets/plans_map.jsx
The original base marker is currently shown too
otherwise it's weird that the active marker is shown besides the cluster where the base cluster is counted in. for example with a cluster of two markers if one of it is selected it is not clear if there are 3 vorhaben (2 in the cluster, 1 selected) or two
It may be better to just hide the base marker though
=> Show the selected/active marker supplementary

meinberlin/assets/scss/components/_filter_bar.scss
The float is set for larger screen to position the filter to the right.
The grid does not work as expected if the element does not float.
As grid-position does not include grid-cell automatically it is required
to include it manually to reset the correct grid floating and margins.
fixes #1052
=> Fix grid for right aligned filters within control bars

meinberlin/assets/scss/components/_comments.scss
fixes #435
Note that we had actually just forgotten to style `comment-deleted-author`.
=> improve comment-author styling

meinberlin/apps/actions/templates/meinberlin_actions/includes/action.html, meinberlin/apps/adminlog/templates/meinberlin_adminlog/includes/logentry_list_item.html, meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/assets/scss/components/_action.scss
This makes the current default styling with a date a variant `action--withdate`
=> Hide date from adminlog 

locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/extprojects/dashboard.py, meinberlin/apps/extprojects/forms.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_list_tile.html
This allows to keep the start and end date of the external project clear. Either both or none of the dates is allowed to be given.
If no date is given the project tile won't show the 'Participation is possible until / starting from' text
=> Allow external projects without participation phase dates

meinberlin/apps/dashboard2/forms.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html
This is due to a requirement from beteiligung.in
This kind of depends on liqd/adhocracy4#223 which increases the module description char limit
=> Use textarea for module description input

webpack.config.js
Probably starting from version 16 react is using the filename
`react.production.min.js` which was excluded from parsing.
Thus the `require` was not replaced correctly as [mentioned in the webpack docs](https://webpack.js.org/configuration/module/#module-noparse)
This PR fixes the problem by allowing files ending on `.min.js` to
be parsed again. 
I tested if everything^TM works on the local site and could not find any problems. But still i am not 100% sure why this line was added to the webpack.config and if it is really safe to remove it. 
There are some other `*.min.js` files as can be seen from the verbose weboack output:
```
info/bower_components/smooth-scroll/dist/js/smooth-scroll.min.js    5.01 kB          [emitted]         
[28] ./node_modules/timeago.js/dist/timeago.min.js 2.13 kB …
```
=> Stop excluding *.min.js files from parsing

meinberlin/apps/documents/templates/meinberlin_documents/react_documents.html, meinberlin/apps/documents/templatetags/react_documents.py
CKeditor calls ckeditor-init.js from its Media.js to set the
window.CKEDITOR_BASEPATH
The fallback tries to guess the basepath by comparing every `<script>`
tags src with `ckeditor.js`. Since we are using cachebusting the file
was renamed to `ckeditor.0151.js` and the basepath could not be found
automatically.
This commit fixes the problem of broken richtextfields from within react
components like used for documents.
(Or at least i hope so, as i can't test cache busting locally)
=> Use CKeditor widgets media attribute to initialize js

meinberlin/apps/plans/views.py
On the development server there is an extra polygon for the border of berlin in mappresets, which does not get loaded when running 'import_geodata'. Because of this, on the plans map not only the district borders but also the city are displayed and therefore added twice which looks strange. 
To remove the district borders on the map I excluded the Berlin map preset from the query.
=> don't add berlin polygon to the list of district polygons

meinberlin/apps/contrib/filters.py, meinberlin/apps/projects/views.py, package.json, requirements/base.txt
Uses the distinct ordering filters from a4.
I searched for ListViews with pagination not using the ordering filter. I found:
- Actions -- use timestamp for ordering
- LogEntry -- also timestamp
- Dashboard2 -- uses a filterset, but currently without ordering filter. I guess, we will remember for a wile that we have to be careful if we add one, but should we put that down somewhere as well? or hope, that django filters fixes it before it can go wrong? To order, it uses created
- ProjectContainers -- uses pagination, but I couldn't find an ordering. But this is shown in the normal project list view and ordered?! I can only find how the projects from the containers are filtered out of the project list view, not how the containers are put into the list.
=> Ka 2018 01 use distinct ordering filter

meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js
readAsText is not standardized yet, but it is in working draft state and
supported by most browsers.
we assume an utf8 encoding, as is defined by the geojson standard
=> Fix geojson import by using readAsText with utf8 encoding

meinberlin/apps/documents/assets/ChapterForm.jsx, meinberlin/apps/documents/assets/ChapterNav.jsx, package.json, requirements/base.txt
Not sure why, but it flip-move does not work with `require` anymore. Using `import` is fine though and works with babel.
=> Greenkeeper/react flip move 3.0.1

meinberlin/apps/documents/exports.py
not the biggest issue, but we forgot to unescape the initiator entered text.
=> Unescape document export texts

meinberlin/config/settings/base.py
As meinBerlin is directed to a german speaking audiency and the user generated contents (for example project descriptions etc.) are not translateable the default language will be changes to german and the users browser settings ignored.
This change has been approved by the pm and the po
=> Enforce german l18n

meinberlin/apps/maps/management/commands/import_geodata.py, meinberlin/apps/plans/models.py, meinberlin/apps/plans/views.py
Note that i changed the category containing bezirke on dev and stage to "Bezirke - Berlin" in accordance with prod. On the local machines the table should be cleared and the import script run again.
This is a really hacky solution that should be replaces as soon as possible by a more geo way.
For example separate table for bezirke and bezirksregionen which could then be used for the mappresetcategory instead of the other way around
=> Set MapPreset category containing the region to "Bezirke - Berlin"

meinberlin/apps/plans/assets/plans_map.jsx
the scrollTo breaks the code completely in IE 11 (map disappears) and  as I could not really figure out why and when this is actually needed, I removed it.
=> remove scrollTo from code as it breaks in IE

meinberlin/config/settings/base.py, requirements/base.txt
This enables the http2 feature of pushing files before they get
requested by the browser. It can speed up browser rendering,
especially on on cold caches/first page landings.
Important to note: this does NOT disable browser caching and
browsers do cancel unnessecary file transmissions. But in cases
where the push is faster than the cache (which does happen quite
often, even on SSDs but more often on HDDs), some browsers
rather redownload the file. The network overhead should be
negitable, as media images make up for most of the traffic and
the pushes use streams instead of new connections (HTTP2, yeah!)
=> Enable HTTP2-push for static files

meinberlin/assets/scss/components/_dropdown.scss
fixes #1281 
This gives dropdowns the highest z-index(es), we have in the whole project. IMHO that should be fine as normally dropdowns should open on top of other stuff.
=> increase z-index for dropdown menu

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_new_item.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_new_item.en.email
I am actually not so happy with this solution.
We use similar code in other templates: https://github.com/liqd/a4-meinberlin/tree/master/meinberlin/apps/notifications/templates/meinberlin_notifications/emails
And it's too much logic in the template. But somehow I did'nt came up with a better solution for this one.
=> More fine grained call to action in notifications, closes #1250

meinberlin/config/settings/dev.py
With this we see if there are errors handling tasks.
It would be nice to also have it in the other projects
=> Print tracebacks that happened in tasks

meinberlin/assets/scss/components/_timeline.scss
The z-index was added here: https://github.com/liqd/a4-meinberlin/commit/6da1c202d7aff231666b870dee173ea2c038533c
fixes #1258
=> z-index for phase bulltes auto on desktop

meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/assets/scss/utility.scss
This PR removes the ability to hide/show phases in the project view. If there is just one phase the grey borders are not shown
=> always display phases and remove borders if there is just one phase

tests/ideas/test_item_tags.py, tests/mapideas/test_item_tags.py, tests/maptopicprio/test_item_tags.py, tests/topicprio/test_item_tags.py
Some tests, unluckily the tags from the item tags are not actually all in use. I'd propose, we merge nonetheless and do a rewrite (or at least some deleting) at some points it fits.
=> Ka 2018 05 add item tag tests

meinberlin/apps/contrib/management/commands/errored_task_notification.py
The idea behind this, is to make this a cron job. So in addition to this PR #1394 which makes sure that a task is not restarted after an error, admins would also be notified via email that a task failed. 
Adding better exception handling for sending emails (with a log that displays all the emails that failed) should be added in a separate user story.
=> add management script to display failed tasks

meinberlin/assets/scss/components/_idea_remark.scss
Added a width to the box, comparable to the button, fine in chrome, firefox, IE and on responsive, I know you said something about only using min-width? can't work with percentage. Added a min height to text area as Carolin requested it be larger, specially as IE cannot resize.
=> css for IE11

meinberlin/templates/403.html, meinberlin/templates/500.html, meinberlin/templates/base_errors.html
fixes #1361 
also does not use the base template for server errors anymore
to test:  
-  set DEBUG=False and add ALLOWED_HOSTS = ['localhost'] in/to settings/dev.py
- start server with: python manage.py runserver --insecure
=> Ka 2018 05 error pages

meinberlin/config/settings/base.py, meinberlin/config/settings/dev.py, meinberlin/config/settings/production.py, requirements/base.txt
One small behavioral side effect: `python manage.py process_tasks` now makes more output in production.
The local settings then should be something like this:
```
RAVEN_CONFIG = {
'dsn': 'https://username:password@server.io/something',
'release': git_commit_hash,
}
```
@treba123 will take care of a self hosted sentry server.
=> Configure sentry

meinberlin/apps/plans/assets/plans_map.jsx, package.json, webpack.common.js
Fixes #1587 
Works fine in firefox and chrome (scrolls smoothly), works in IE and edge, but not smoothly. Not tested in Safari.
=> use browser method scrollIntoView

renovate.json
As the hash (for A4) also has to be updated in the python requirements, it seems to be a bad idea to do that automatically in the node modules.
This rule also needs to be updated in the other projects if it is working.
=> disable automatic git hash updates by renovate

meinberlin/apps/bplan/management/commands/bplan_get_location.py, requirements/dev.txt
This gets the districts and the point info from the bplan api with the identifier, that can now be added to the bplan.
There might be some error handling left to do. I thought of:
- unreachable or wrong URLs. They either thow a HTTPError  `urllib.error.HTTPError: HTTP Error 404: Not Found` or an URLError `urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>`
- wrong identifiers. They just pass without returning a feature and leave the bplans untouched.
- characters that can't be put into a url in the URL (like 'ü'). They would throw an UnicodeEncodeError, which I catch and pass, so that the other bplans will still get their location.
- admin districts, that are on the bplan-map, but not in our database. They get a 'None', so the bplans with that district just don't …
=> Ka 2018 10 get bplan point

meinberlin/apps/plans/views.py
currently only works when all projects have a point.
=> add the list of projects to the plans map

meinberlin/apps/plans/views.py
It finds the future phases that do not yet have a date.
But it still needs to work with the very strange escaped empty string in the point field, that gets saved when an external project is added via the django admin
=> fix external projects on participation list

meinberlin/config/settings/dev.py
This gives me better output in the terminal and silences csp warnings in dev mode.
=> dev.py: enable console logging and silence csp

meinberlin/config/settings/base.py
Set them in salt-config instead (needed in the future to support production service konto)
**Edit:** the config via salt is already deployed on dev, so this is save to merge
=> remove hard-coded settings for service konto

package.json
Reverts liqd/a4-meinberlin#1828
=> Revert "Update dependency autoprefixer to v9.4.6"

meinberlin/apps/plans/assets/MapListSwitch.jsx, meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_radio.scss
is it ok to leave the btn class names as we want them to look like that? 
Also added tiny fix quick to accordions which I think I broke with map teaser styling
=> restructure mobile btn group to be radio btns for a11y

meinberlin/apps/plans/assets/FilterOptions.jsx
=> display desktop filter options in four columns, last one empty

tests/conftest.py, tests/plans/conftest.py, tests/plans/test_serializer.py, tests/projects/test_serializer.py
while writing the tests I noticed that the participation_string method in plan serializer behaves a bit strange when there are no projects and when the projects are over: it will always return the the participation field value of the plan.
=> Mn 2019 02 test serializers

meinberlin/apps/users/adapters.py
fixes #2168 and hopefully doesn't destroy anything else. I think, I checked all account-emails: register and password-reset still go to the right addresses!
=> send account-emails to right address

meinberlin/templates/account/email/email_confirmation_signup.de.email, meinberlin/templates/account/email/email_confirmation_signup.en.email
This current email also works because user has the email as string method, but in this version it's more robust!
=> Ka 2019 04 another tiny email fix

meinberlin/assets/js/app.js, requirements/base.txt
This allows us to remove a workaround again and fixes the editor in
the admin panel
Should fix https://github.com/liqd/a4-meinberlin/issues/2216
=> requirements: Update to ckeditor 5.7.1

meinberlin/apps/plans/models.py, meinberlin/apps/projects/serializers.py, tests/projects/test_serializer.py
From the commit message:
```
The 'date()' function is not timezone aware, giving us the UTC date
rather than the date of the current timezone. Projects that start
at 0:00 CET will therefore counted as 22:00 of the previous day,
leading to a wrong date.
```
=> apps: Stop using 'date()'

webpack.common.js
The same list is already set in `packages.json` and the new version
of autoprefixer throws a warning about that.
=> webpack: Remove the 'browsers' argument from autoprefixer

meinberlin/apps/users/adapters.py
This was made a requirement in django 2.1. Passing 'None' means we must
stay on our site, which is what currently always do.
Fixes https://github.com/liqd/a4-meinberlin/issues/2276
=> apps/users: Add new required argument allowed_hosts to is_safe_url

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/assets/PopUp.jsx, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/includes/container_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_module_tile.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_participation_tile.scss, meinberlin/assets/scss/components/_status_bar.scss, meinberlin/assets/scss/style.scss
To whoever reviews: Firstly sorry about lack of commits, I wanted to do one for each change of class name but then I forgot that was what I was going to do and just did most of it in one because they kind of bled into each other. 
I ended up swapping out quite a few class names to be used across the 3 different tile types that we use, basic, maplist and popup, ideally I would like 'participation-tile' to be the basic tile that we base all the rest off, however as a class name i wonder if it is too long? also it does not entirely relate to the other tile types that are based off of it.
=> project module tile: adding template for module styles

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_module_tile.html, package.json, requirements/base.txt
depends on https://github.com/liqd/adhocracy4/pull/355
It's currently using that branch, but should not be merged like that. Merge the a4-PR first, then update the last commit to the new hash and then merge. 
While doing this stuff, I noticed our all the inconsitencies how we use the phases again. I think we should update the stuff that is used in the mB projects to use the new running module logic.
=> Ka 2019 06 add status bar info to modules

meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_tabs.scss, meinberlin/assets/scss/components/_timeline-carousel.scss, package.json
can currently tab through all the slides, it's not perfect as previous slides remain off screen but I think it's fine as they will be read out, and arrow has a previous aria label on so should make sense.
=> Pm 2019 06 ally timeline

meinberlin/assets/js/app.js
tested on different browser sizes and seems to work
=> timeline arrows: reducing tiels shown to 1 so arrows always visible

meinberlin/apps/budgeting/exports.py, meinberlin/apps/documents/exports.py, meinberlin/apps/ideas/exports.py, meinberlin/apps/kiezkasse/exports.py, meinberlin/apps/mapideas/exports.py, meinberlin/apps/maptopicprio/exports.py, meinberlin/apps/polls/exports.py, meinberlin/apps/projects/views.py, meinberlin/apps/topicprio/exports.py
As of Django 2.2, it's not callable anymore but a bool.
Forgot that during the update (was done in AE). Found when debugging https://github.com/liqd/a4-cookiecutter/pull/90
=> apps: Use is_authenticated instead of is_authenticated()

meinberlin/apps/contrib/mixins.py, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/views.py
The offlineevent-check is still missing, but we can add that before moving it to a4.
fixes #2349
=> apps/projects/modules: move module/timeline logic to mixin

Makefile, meinberlin/assets/js/app.js, package.json, webpack.common.js
Lets also lint `meinberlin/assets`. And make `make lint` not check for migrations.
=>  ci: Some linting improvements

.eslintrc, meinberlin/apps/contrib/static/js/ajax_modal.js, meinberlin/apps/contrib/static/js/unload_warning.js, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/assets/js/app.js, meinberlin/assets/js/embed.js, meinberlin/assets/js/map-address.js, meinberlin/assets/js/popup-close.js, package.json, webpack.common.js
Revert the revert and fix what's broken. Apparently it was broken by a react update - they choose to require some ES6 functionality now. So add ES6 promise package (again?) and properly provide it via webpack.
Now works fine again on IE11
=> apps/plans: Remember closing the infobox on sticky map - take two

meinberlin/apps/contrib/sitemaps/static_sitemap.py, meinberlin/apps/organisations/models.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_module_tile.html, package.json, requirements/base.txt
Should fix this: https://sentry.liqd.net/sentry/meinberlin-prod/issues/815/
And the issue with the index @MagdaN found yesterday: https://github.com/liqd/adhocracy4/pull/373
=> Ka 2019 08 make sure project list not used anymore

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_event_upcomming.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_event_upcomming.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_phase_over_soon.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_phase_over_soon.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_phase_started.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_phase_started.en.email, meinberlin/apps/offlineevents/models.py, meinberlin/templates/email_base.html, tests/offlineevents/test_views_integration.py
- templates: remove unused blocks from email base
- use right wording in reason of notify creator emails
- fixes #2546 
- fixes #2548 
- fixes #2547
=> notification issues: use right links to events and modules

meinberlin/apps/actions/assets/timestamps.js
This broke in 6d9a62232895d2cba or the commit before.
=> apps/actions: Fix timeago call

meinberlin/apps/bplan/phases.py, meinberlin/apps/bplan/templates/meinberlin_bplan/dashboard_bplan_list.html, meinberlin/apps/bplan/views.py, meinberlin/apps/dashboard/blueprints.py, meinberlin/apps/dashboard/urls.py, meinberlin/apps/dashboard/views.py, meinberlin/apps/extprojects/phases.py, meinberlin/apps/extprojects/templates/meinberlin_extprojects/dashboard_extproject_list.html, meinberlin/apps/extprojects/templates/meinberlin_extprojects/external_project_create_form.html, meinberlin/apps/extprojects/views.py, meinberlin/templates/a4dashboard/base_project_list.html
Alright, while there is still much more to do, this is good point to review and merge, I think. 
This adds separate lists for the projects, bplans, and external projects. The individual create-buttons work and make it possible to add bpland and external projects again.
=> dashboard: make separate lists for participation projects, external projects, and bplans

meinberlin/config/settings/base.py
It was introduced in django 2 and by default blocks cookies being send on
cross origin request. Unfortunately the servicekonto account connection,
when a user already has an account and is logged in and wants to connect
her account to the servicekonto, requires us to send the cookie on login
callback.
Note: This is not necessary for oauth2 and other more sophisticated
social login techniques. Further more the allauth `draugiem` provider, on
which the `servicekonto` provider is based on, is the only provider in allauth
requiring a `@csrf_exempt`. Using OAuth2 would be much saver and easier.
=> settings: Disable SESSION_COOKIE_SAMESITE to allow servicekonto connections

meinberlin/apps/projects/serializers.py
We treat this case as valid, so lets not print messages, they are distracting.
=> apps/projects: Do not print errors on valid data

meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html, meinberlin/templates/base.html
If some JS code is not needed for page rendering, lets defer it so
initial rendering gets faster. Add a block in the base template for
that.
This gets dev from the 2Xs to 4Xs on pagespeed, helps with https://github.com/liqd/a4-meinberlin/issues/2030
=> templates/base: Add a block for deferred js and use it for plans_list

meinberlin/apps/dashboard/assets/init_accordeons_cookie.js, meinberlin/apps/dashboard/templatetags/meinberlin_dashboard_tags.py, meinberlin/apps/dashboard/views.py, meinberlin/apps/projects/templatetags/meinberlin_project_tags.py, meinberlin/assets/js/app.js, meinberlin/templates/a4dashboard/base_dashboard_project.html
Properly save the list as JSON, fixing a bug with the previous
splitting and making it much easier to work with. Also use the
chance to move the js code into its own file, into the same app
where the template tag using it resides.
=> apps/projects: Move and fix accordeon cookie

meinberlin/apps/users/models.py, meinberlin/apps/users/urls.py, meinberlin/apps/users/views.py, meinberlin/config/urls.py, package.json, requirements/base.txt, tests/users/test_models.py, tests/users/test_views.py
depends on this PR: https://github.com/liqd/adhocracy4/pull/457
With this there won't be a link to the users profile (which does not exist anymore also) near a comment. Only the username is shown.
=> remove user profile

meinberlin/apps/embed/templates/meinberlin_embed/embed.html, meinberlin/apps/embed/templates/meinberlin_embed/login_popup_close.html, meinberlin/apps/embed/urls.py, meinberlin/apps/embed/views.py, meinberlin/templates/base.html
This moves the popup close handling out of the base template into an
own simplistic view. While this one could still be smaller (it inherits
the base view), it is much faster than the landing page.
=> apps/embed: Speed up login by not loading landing page

meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js, meinberlin/apps/plans/assets/FilterSecondary.jsx
To be forward compatible with future versions of `react-bootstrap-typeahead`.
Fixes the warning:
```
Warning: [react-bootstrap-typeahead] The `id` prop will be required in future versions to make the component accessible for users of assistive technologies such as screen readers.
```
=>  plans/assets: Add 'id' to 'Typeahead' blocks 

meinberlin/apps/embed/assets/embed.js, meinberlin/apps/maps/assets/map-address.js, meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js, meinberlin/assets/js/app.js, package.json, requirements/base.txt
When using multple webpack endpoints we do not get a global jQuery
object but instead one for each endpoint. These do not see each others
signals, thus do not fire.
Use standard js events instead - they don't suffer from that problem and
we should get rid of jQuery anyway over time.
Also use the chance to clean up the init syntax.
Depends on https://github.com/liqd/adhocracy4/pull/519
Fixes https://github.com/liqd/a4-meinberlin/issues/2781
**Needs to get tested with IE11** :(
=> assets: Replace jQuery 'a4.embed.ready' listeners with vanilla js

meinberlin/templates/a4reports/emails/report_moderators.en.email, meinberlin/templates/email_base.html, meinberlin/templates/email_base.txt, requirements/base.txt
Closes https://github.com/liqd/a4-meinberlin/issues/2860
Context: we now force a `de` browser header in our nginx settings
=> templates: Remove hacks to force german language

package.json
Reverts liqd/a4-meinberlin#2894
above update breaks header dropdown on mobile, seems to be a bootstrap issue
=> Revert "fix(deps): update dependency jquery to v3.5.0"

package.json
Reverts liqd/a4-meinberlin#2913 until jquery or bootstrap release a fix we will stay at
=> Revert "Update dependency jquery to v3.5.0"

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/assets/plans_map.jsx
From the main commit:
```
`LazyBackground` does not use the image url property directly but
instead has an internal state - to not directly load images when the
property appears, but only when they first become visible.
Thus, we must listen on property changes and update the state accordingly.
Also, remove an unused variable.
```
Closes #2911
=> plans/assets: Update state of LazyBackground when props change

meinberlin/assets/js/app.js, meinberlin/templates/a4dashboard/base_dashboard_project.html, webpack.common.js
This reverts parts of 80fe4e69d996f360025751535af06b40dfbf6d6f as it caused
us to warn e.g. when having filters set in the project overview.
Closes #2910
=> assets/js: Move onload_warning out of global assets again

meinberlin/apps/bplan/emails.py, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_notification.de.email, meinberlin/templates/email_base.html
In the mail template, that @CarolingerSeilchenspringer gave us, the headline and subheadline were also left aligned, but this would mean 2 more extra left aligned blocks.. thats why I left it centered for now, bc I dont think it makes a difference for the length of the printouts.. do you think this is ok?
=> Ks 2020 05 redesign blan new statement mail

meinberlin/apps/cms/models/email_form.py
This was accidentally removed during debugging, resulting in the captcha
data send along in the email.
=> cms/email_form: Remove captcha data from mail

meinberlin/config/urls.py, tests/users/test_views.py
Note: in order to keep old urls working we need to adapt our nginx config.
=> config/urls: Use 'projekte' instead 'projects' in project urls

meinberlin/apps/bplan/signals.py, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_update_confirmation.de.email
Long explanation in the first commit!
To test locally, just start watch and backround and add or change a bplan via the dashboard like you are used to or via the terminal:
`curl -d '{"name":"Katharinenblock Ost - Bebauungsplan 4-83", "identifier": "4-83", "description": "Test", "url": "https://mein.berlin.de", "office_worker_email": "<YOUR EMAIL>", "start_date": "2020-01-01T00:00", "end_date": "2022-01-01T00:00"}' -H "Content-Type: application/json" -X POST "url": "http://localhost:8003/api/organisations/1/bplan/" --user 'admin@liqd.net':'password'`
=> Ka 2020 07 bplan update email

meinberlin/apps/contrib/templates/meinberlin_contrib/matomo/tracking_code.html, meinberlin/apps/contrib/templatetags/contrib_tags.py
In order to avoid having to show a cookie banner.
---
This is actually for a+, but as meinberlin-dev is already set up on matomo, lets test the code here first.
=> apps/contrib: Add option to disable Matomo cookies

webpack.common.js
As we use our own fork and there's no clear way to rebuild the optimized files, don't use them. Instead, lets optimize it in webpack for now.
=> Revert "webpack: Use optimized static files for dsgvo-embed"

.editorconfig, Makefile
fixes #3234 
https://github.com/PyCQA/isort/issues/885#issuecomment-552069021
https://pycqa.github.io/isort/docs/configuration/options/#skip-glob
https://github.com/PyCQA/isort/issues/885
=> editorconfig: skip migrations for isort

meinberlin/apps/contrib/management/commands/cleanup_unverified_users.py
Strictly speaking we should check for the email verified status here,
but if a user never logged in that pretty much implies the same.
Prints a list of deleted users, which we'll recieve as mail from
a cron job.
See also https://github.com/liqd/adhocracy-plus/pull/991
=> contrib/management: Add command to clean up unverified users

meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/livequestions/assets/QuestionForm.jsx
Directly fire a update request and reset the timer, so the own question
is shown faster.
Port of https://github.com/liqd/adhocracy-plus/pull/1017
=> livequestions/assets: Restart polling interval when adding question

meinberlin/apps/maps/assets/map-address.js, meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js, meinberlin/apps/plans/assets/PlansMap.jsx, package.json, requirements/base.txt, webpack.common.js
Instead of relying on webpack to provide the common map file, properly
import it (requires new a4). Also rely less on global jQuery.
Depends on https://github.com/liqd/adhocracy4/pull/670
=> assets: js cleanups

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, package.json, requirements/base.txt
Together with the a4 update this makes us properly show the attribution everywhere.
=> plans/assets: Properly pipe through the attribution

meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js, package.json, requirements/base.txt
`select2` is a jQuery extension, thus we need to use the window-global
jQuery instance instead of the webpack provided one.
Depends on https://github.com/liqd/adhocracy4/pull/673
=> maps/assets: Fix select2 for polygon areasetting

webpack.common.js
The old `flatten` syntax was dropped, however we still rely on its
effect. Use the common syntax to archive the same.
=> webpack: Readd flattening with proper syntax

requirements/base.txt
From the release notes:
- Pin django-treebeard to <4.5 to prevent migration conflicts
=> deps: Update wagtail

webpack.common.js
We implicitly assume that adhocracy4.[js|css] and vendor.[js|css]
are always present. Make this dependency explicit in Webpack,
so entry point that import the same dependencies don't need to include
the same code.
This appears to slim down our overall js load quite a bit.
=> webpack: Explicitly declare chunk dependencies

meinberlin/assets/js/app.js
And set `window.adhocracy4.getCurrentPath` like we do in `embed.js`.
I'm not sure how this worked in the past, but it appears to be
something implicit we shouldn't rely on.
=> assets/apps.js: Explicitely initialize window.adhocracy4

meinberlin/apps/embed/assets/embed.js
This affects cases when people login from the login-link shown
e.g. above comments.
=> apps/embed/assets: Work around login popup not closing

meinberlin/apps/embed/templates/meinberlin_embed/embed.html, meinberlin/assets/js/app.js, meinberlin/templates/500.html, meinberlin/templates/base.html, webpack.common.js
Using the vendor chunk is, IIUC, a leftover from Webpack <= 3 times.
Webpack >= 4 promote a different kind of chunk splitting. This is
a step into that direction.
The probably biggest benefit is that there's now a single big `adhocracy4`
entry point which includes all base dependencies, avoid odd ordering issues
and making it clearer where to add stuff to.
Port of some improvements found in https://github.com/liqd/adhocracy-plus/pull/1128, which again was a port of https://github.com/liqd/a4-meinberlin/pull/3440
=> webpack: Remove vendor chunk

meinberlin/apps/bplan/serializers.py
I found a much better and easier way! :partying_face:
=> apps/bplans: validate image filename length in serializer - fixes #3500

meinberlin/apps/plans/assets/PlansList.jsx
The list of active projects can get quite long, resulting in high
client cpu load. Skip rendering until the tile becomes visible.
This will need some testing. Also it might make sense to set the interval number slightly higher as otherwise we rist to not initially show enough tiles on big screens.
=> WIP plans/assets: Render project tiles on demand

meinberlin/assets/scss/components/_blocks.scss
Adding css selector h2 and p for .block--map-teaser_background
fixes #3547
Note:
I have to move the entire class, because of css specificity (what a word!)
stylelint complaint about it.
https://stylelint.io/user-guide/rules/no-descending-specificity
=> Center title and wording text

requirements/base.txt
move to the newer sentry-sdk as raven has been deprecated for
a while now.
=> jd 2021 06 requirements/base.txt: upgrade from raven to sentry-sdk

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
I only added the translations, I don't want to forget. Maybe we can add the translations, we already have by everyone adding translations they know where to find (and being careful to not do that at the same time :p).
I get this warning when I makemessages for the js files, but they still seem to be fine and I couldn't find why it's there:
```
/home/katharina/a4-meinberlin/venv/bin/python manage.py makemessages -d djangojs
/home/katharina/a4-meinberlin/node_modules/adhocracy4/adhocracy4/polls/assets/PollOpenQuestion.jsx:22: warning: RegExp literal terminated too early
/home/katharina/adhocracy4/adhocracy4/polls/assets/PollOpenQuestion.jsx:22: warning: RegExp literal terminated too early
processing locale en_GB
processing locale de_DE
```
=> translations: first round

package.json, webpack.common.js
recommended with the css-mini-extract-plugin, one external dependency less
=> webpack: use new inbuilt asset modules instead of file-loader

meinberlin/apps/polls/migrations/0006_copy_poll_data_to_a4_polls.py
The order of the choices stays the same like that.
We have to change it in this migration, because we cannot make sure, that this is run before
the migration in a4 adding the weight to the poll. And for projects where this migration is already run, it is no problem that it changed.
I also got the error locally when I used an older database. This fixed it and the order of the choices stayed the same.
=> apps/polls: also fill weight field for choices

meinberlin/apps/plans/models.py, meinberlin/apps/plans/serializers.py
This adds the tile-image and its copyright if it exists, otherwise it adds the image used on the detail page.
This is the same as for the projects.
=> apps/plans: add tile image to API

meinberlin/apps/dashboard/views.py, meinberlin/apps/plans/views.py, tests/dashboard/test_dashboard_views_module_delete.py, tests/dashboard/test_dashboard_views_module_publish.py, tests/plans/test_dashboard_views_publish.py
How to do the delete stuff, I found here: https://stackoverflow.com/questions/54467081/how-to-send-error-message-from-django-deleteview
To test the delete locally on the site instead of in the tests, change the [if around the module delete button](https://github.com/liqd/a4-meinberlin/blob/488edf5ecb1bee5be7067eb49211bf8a6277ef52/meinberlin/templates/a4dashboard/includes/nav_modules_item.html#L54) to `{% if True %}`
=> Kl 2021 09 more publish tests

meinberlin/config/settings/base.py
=> config/settings/base.py: rm embed from config of default ckeditor

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/serializers.py, meinberlin/config/urls.py
The url to get the proposals is `reverse('proposals-list', kwargs={'module_pk': $module_pk})` or `/api/modules/$module_pk/proposals/` which we then probably need to add to context of ProposalListView
=> [#4987]budgeting: add proposal serializer and api

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/Pagination.jest.jsx, meinberlin/apps/budgeting/assets/Pagination.jsx, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/assets/scss/components/_pagination.scss, meinberlin/config/settings/base.py
Some notes, that might help to understand what was intended :) 
This react pagination should behave like the old one (rather than what is in the current design)
I am not sure if i utilized the pagination django part correctly, any suggestions appreciated.
You might expect it a bit different, but:
page_size = 0 won't show all, but 0 --> edge case (we should use rather a large number)
=> Kt 2021 11 pagination

meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_create_form.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_update_form.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_create_form.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_update_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_create_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_update_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_create_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_update_form.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_create_form.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_update_form.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_create_form.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_update_form.html, meinberlin/apps/plans/templates/meinberlin_plans/includes/plan_form.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_create_form.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_update_form.html, meinberlin/templates/a4dashboard/base_form_module.html, meinberlin/templates/a4dashboard/base_form_project.html
A general error message at the top of the form was added to all the forms **except** the Bplans, because this form doesn't use the errorlist box on fields:
, but instead the 'Missing field for publication'-icons: 
This solution is based on the a+ use of the top error fields with the exception of the ideas form, which has a missing top error message:
The mB idea form has this missing message.
**QUESTION**: does this implementation make sense? It seems there are about 3 different ways that error messages are displayed for the user in mB.
This PR still needs translation once everything else is reviewed.
=> meinberlin/templates: added general error message on top of all forms

meinberlin/apps/budgeting/api.py
to get the same results as in the original list, please add
ordering=-created or ordering=-comment_count or ordering=-positive_rating_count
as parameter to the API url.
You can already merge and use this. I will open a new PR for the other filter stuff, because I have to fix all the rest API filtering where we use `filter_fields`.
=> apps/budgeting: add ordering filter to API

meinberlin/apps/budgeting/api.py, meinberlin/apps/contrib/filters.py, meinberlin/config/settings/base.py
This does the filtering. But we need to know which categories to display (and their icons). 
What is the best way to add that? I think previously we either added that to the template tag or to the serializer. But I guess the best option would be to add it to the response.data of the API, which should be possible? What do you think @Rineee ?
=> Kl 2021 11 more propsal api filters

meinberlin/apps/budgeting/rules.py, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/budgeting/templatetags/react_proposals.py, meinberlin/apps/budgeting/views.py, meinberlin/apps/votes/forms.py, meinberlin/apps/votes/models.py, package.json, requirements/base.txt
This adds a form for the voting token to the proposal list. When the token is there, it simply displayed for now, we will then need a react component for showing the left votes (I will next add that to the api). 
Oh, and we also need a widget for the token, so that it can be entered with 3 x 4 characters.
=> Ks 2021 11 add token form to proposal list view

webpack.common.js
I could not figure out, why it needs adhocracy4 as dependency. Maybe because otherwise jQuery is not there? But the unload warning works without it...
=> assets/js: fix initialisation of blueprint-picker - fixes #4022

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html
This fixes #4023. 
In **1st Commit:** error messages were consolidated in styling.
In **2nd Commit**: new phrases are pulled in.
In **3rd Commit**: translations are added to new error message text and new wording of existing error messages. This thus also fixes #4024.
=> Sm 2021 12 03 inconsistent error messages issue

meinberlin/apps/contrib/templates/meinberlin_contrib/includes/proposal_list_item.html, meinberlin/apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_list_item.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
**Commit 2** in Pull Request https://github.com/liqd/a4-meinberlin/pull/4041 broke the template for plan detail. This is because multiline tags in django template language are not possible (see https://code.djangoproject.com/ticket/8652).
=> apps/plans/templates: fix for PR #4041 syntax error

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/apps/livequestions/templates/meinberlin_livequestions/includes/module_affiliations_form.html, meinberlin/apps/plans/templates/meinberlin_plans/project_plans_form.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, meinberlin/apps/projects/templates/meinberlin_projects/participantinvite_form.html, meinberlin/apps/servicekonto/templates/meinberlin_servicekonto/login.html, meinberlin/templates/a4categories/includes/module_categories_form.html, meinberlin/templates/a4dashboard/includes/module_phases_form.html, meinberlin/templates/a4labels/includes/module_labels_form.html, meinberlin/templates/account/email_confirm.html, meinberlin/templates/account/signup.html, meinberlin/templates/socialaccount/signup.html
Translations in po-files from blocktrans blocks contain linebreaks with \n in them, if they are not in 1 line in the templates.
Thus, in this PR, all blocktrans blocks in the project were checked to see whether they ran over more than one line. 
In the 1st commit, these were refactored to close on the same line. In addition, in order to _reinstate_ a necessary blocktranslate in the **cms//storefronts template**, the html_date tag was removed, as it is not possible to use this in a blocktrans block.
The 2nd and 3rd commits are the refactored as well as new translations.
=> templates: blocktrans blocks refactored in all apps where these were not in 1 line

meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/votes/forms.py, meinberlin/assets/scss/_form.scss
This produces three instead of one input field for the voting token. Each field requires 4 characters.
Still to do
@phillimorland would you check out the styling when you get the chance? 
@Rineee I added comments for the form validation that I can't get to work well, maybe you can check if you have time? I think the decompress and value_from_dict functions work.
=> apps/votes: added widget to voting form

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/serializers.py, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html
@khamui I think that is all the info we need in the API now! :) And quite a lot of refactoring for the frontend, then...
=> apps/budgeting/api: more info in API and serializer

meinberlin/apps/projects/rules.py, tests/polls/test_poll_export_overwrites.py, tests/projects/dashboard_components/test_views_project_moderators.py, tests/projects/dashboard_components/test_views_project_participants.py
This PR is in regard to [US 50499](https://taiga.liqd.net/project/liqd-liquid-software/us/5049?milestone=290).
The meinBerlin-specific rules for changing projects were removed, leaving the original a4 permissions that do not specify moderators.
The tests were changed according to this new permission setup.
=> [#50499] restrict moderation to not change projects

meinberlin/apps/budgeting/api.py
To make the filters displayed in the same order as in the django template list
fixes #4094
=> apps/budgeting: switch category and archived filters

meinberlin/apps/budgeting/assets/FilterBar.jsx, meinberlin/apps/budgeting/assets/FilterBarDropdown.jsx
=> apps/budgeting/filters: make initial fetch with defaults (querystring)

meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx, meinberlin/apps/budgeting/predicates.py, meinberlin/apps/budgeting/rules.py, meinberlin/apps/budgeting/serializers.py, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_detail.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/budgeting/templatetags/react_proposals.py, meinberlin/apps/budgeting/templatetags/react_proposals_vote.py, meinberlin/apps/votes/api.py, meinberlin/apps/votes/routers.py, package.json, requirements/base.txt, tests/budgeting/rules/test_rules_vote.py
I did some more research and decided to not use rules for the token voting api permissions as rules are dependent on users and arent really useful here. 
I instead introduced a new Permission class, called TokenVotePermission that checks manually the relevant requirements on the token for create and destroy actions.
Also, I added a check in TokenVoteMixin to make sure that the token is valid before anything else is checked.
=> Ks 2021 12 token voting permissions

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
Translation task for US #5042 prepare release.
This also fixes #4096
=> [#5042] release translations

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx
This is in reference to https://github.com/liqd/a4-meinberlin/pull/4126#discussion_r777473157
This change consolidates the wording use for the new react proposal list to use the same wording as is used in this context everywhere else (commit 1), and adds the corresponding translation (commits 2 & 3).
=> [#4126 (comment)] apps/budgeting: consolidate wording proposal list

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/plans/assets/PlansList.jsx
=> apps/plans: fix plan list translations by moving strings to variables in PlansList.jsx

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/livequestions/assets/CategorySelect.jsx, meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/livequestions/assets/QuestionForm.jsx, meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/apps/plans/assets/PopUp.jsx, meinberlin/apps/plans/assets/Toggles.jsx
Fixes Issues #4150  and #4149 as caused by PR #4126
Leaving this in WIP until [question](https://github.com/liqd/a4-meinberlin/pull/4126/files#r783143986) is resolved, i.e. if there is another PR besides #4126 that deleted translations that are actually still needed.
=> apps/livequestions apps/plans: fixed missing translations by moving translation strings into variables at top of files in all affected jsx files

meinberlin/apps/activities/admin.py, meinberlin/apps/offlineevents/admin.py, meinberlin/apps/plans/admin.py, meinberlin/apps/projects/admin.py
Similar as fix for [#1656 in a+](https://github.com/liqd/adhocracy-plus/issues/1656), done [here](https://github.com/liqd/adhocracy-plus/pull/1664/commits/6c9be35bb186c8cd504f492255f866dd224ff95c). In meinBerlin, this fix was required for the django-admin forms for
- Projects
- Activities
- Offline Events
- Plans.
=> django-admin: fix custom CK editor fields

meinberlin/templates/403_csrf.html
Not super sure about this approach.. the request is aborted, so not there if csrf fails, thats why I had to add that check in userindicator. Also, because request is not there, it then shows the 'anmelden/register' button, even though the user is still logged in.. Not sure if we need (or even can) change that behaviour? Should I investigate more, what do you think @fuzzylogic2000 ?
fixes #4170
=> Ks 2022 02 csrf failure template

meinberlin/assets/scss/components/_a4-comments.scss
=> style glitches bugfix4252

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.en.email
fixes #4257 
@sabinammm You are the only one assigned for testing again. :smile:  If you don't get it to work locally, just ask and/or assign the others to test.
=> apps/notifications: take absolute url of comment, not item commented on

meinberlin/apps/plans/exports.py, tests/plans/test_export.py
I used mB with Node 16 and the legacy-install.
=> [5929] apps/plans: add explanation to export

requirements/base.txt
This works! 
I would rather use a tag instead of the master branch, but I couldn't think of one (that we will then also use in all projects). Is there a convention @goapunk ?
=> deps: use own version of django-autoslug with fix - fixes #4366

Makefile, package.json, requirements/base.txt
fixes #4383
I needed ridicilously long to get a4 right, because last time I creteated a tag, that I then didn't use. :roll_eyes: But I think, this is fine now! I used the a4 version from the last release (v2203.1) and cherry-picked the a4 fix onto that. I didn't do that on main, because I thought, we will properly update a4 there next.
=> deps: update a4 to hotfix tag mB-v2206.1

Makefile
main is not building without that. So, maybe we can add it and then remove once we don't need it anymore?
=> makefile: make relase and install with npm legacy-peer-deps

meinberlin/apps/bplan/views.py, meinberlin/apps/dashboard/blueprints.py, meinberlin/apps/dashboard/views.py, meinberlin/apps/extprojects/views.py, meinberlin/apps/projectcontainers/views.py, meinberlin/apps/projects/migrations/0003_determine_and_add_blueprint_types_to_modules.py, meinberlin/config/settings/base.py, tests/dashboard/test_dashboard_views_module_create.py
Also see https://github.com/liqd/adhocracy4/pull/1207, which should be merged first. This PR is not really dependent on it, but without the A4 changes, new external projects/project containers/bplans wont get a type when saving.
=> Ks 2022 09 add module types

.github/workflows/django.yml, Makefile
* remove the way to slow frontend coverage report
* switch to node 18
* remove the `legacy-peer-deps` workaround
=> ci: remove frontend coverage app

meinberlin/apps/budgeting/dashboard.py, meinberlin/apps/documents/dashboard.py, meinberlin/apps/ideas/dashboard.py, meinberlin/apps/kiezkasse/dashboard.py, meinberlin/apps/mapideas/dashboard.py, meinberlin/apps/maptopicprio/dashboard.py, meinberlin/apps/topicprio/dashboard.py, meinberlin/apps/votes/dashboard.py, meinberlin/apps/votes/views.py, meinberlin/templates/a4dashboard/includes/nav_modules_item.html, package.json, requirements/base.txt, tests/votes/dashboard_components/test_token_generation.py
I am unhappy with how I did it and with the naming, but I couldn't think of a better (and not also overly complex) way. It should work better with the permissions from the view somehow, but as we don't have the user in the dashboard components, and I didn't want to add that complexity, I did it like that. :woman_shrugging: And I thought, if we ever need more and other perms in the dashboard, we can still improve from here.
Depending on https://github.com/liqd/adhocracy4/pull/1216
Right, and the two first commits are from https://github.com/liqd/a4-meinberlin/pull/4477
So, these both need to be merged first and this cleaned up then.
=> Kl 2022 09 dashboard token perms

meinberlin/apps/budgeting/api.py, meinberlin/apps/ideas/models.py
I am not very happy with all of the cases in the annotation, but I think there is no way to use a python function in an annotation, so this is the solution I came up with.. happy for any improvements!
@khamui I did not (yet) add the search filter to the other filters in the api as there is no real information, right? 
The search works with url/?search=my+search+term, so spaces work with '+'. You can just look at the filtered list in the browser, eg. http://localhost:8003/api/modules/$moduleId/proposals/?search=something+here should work.
=> Ks 2022 09 budgeting search filter

meinberlin/apps/votes/tasks.py, meinberlin/apps/votes/views.py, tests/votes/dashboard_components/test_token_generation.py
We did add the management command to notify us of failed tasks. https://github.com/liqd/a4-meinberlin/pull/1408 And we did add the MAX_ATTEMPTS in the server settings. I think we need to keep the MAX_ATTEMPTS at 1 because we don't want to have emails fail multiple times.
Unluckily there is no way of having different MAX_ATTEMPTS for different tasks (https://github.com/arteria/django-background-tasks/issues/256) and the package seems unmaintained by now (https://github.com/arteria/django-background-tasks/issues/267). So, I would say we leave it like that for now.
=> apps/votes: add more info to task

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx, meinberlin/apps/budgeting/assets/ListItemStats.jsx, meinberlin/apps/budgeting/assets/SupportBox.jsx, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalList.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalListItem.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/ListItemStats.jest.jsx, meinberlin/apps/budgeting/assets/react_support_init.jsx, meinberlin/apps/budgeting/phases.py, meinberlin/apps/budgeting/predicates.py, meinberlin/apps/budgeting/rules.py, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_detail.html, meinberlin/apps/budgeting/templatetags/react_support.py, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/dashboard/blueprints.py, webpack.common.js
@fuzzylogic2000 Maybe you already want to have a look, especially the rules (left it all in mb for now), but there a still some todos:
Not even sure about the 'adding support' part of the first two here, is that included in the story? Not explicitly at least :)
=> Ks 2022 09 support phase

locale/de_DE/LC_MESSAGES/django.po
Translations update from [LIQD Weblate](https://trans.liqd.net) for [meinBerlin/main](https://trans.liqd.net/projects/meinberlin/main/).
It also includes following components:
* [meinBerlin/js](https://trans.liqd.net/projects/meinberlin/js/)
Current translation status:
=> Translations update from LIQD Weblate

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/SupportBox.jsx, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalList.jest.jsx, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_detail.html, meinberlin/apps/budgeting/templatetags/react_proposals.py, meinberlin/apps/budgeting/templatetags/react_proposals_vote.py, meinberlin/apps/budgeting/templatetags/react_support.py, meinberlin/apps/budgeting/views.py, tests/budgeting/test_proposals_api_filtering.py
This is supposed to implement the following behaviour:
- show support (on, list, map and detail) during support phase and btw support and voting phase
- support button only active during support phase 
- add 'most support' to ordering filter during support phase and btw support and voting phase
- make 'most support' default ordering filter only btw support and voting phase
Notes: 
- do not test as admin
- old participatory budgeting with rating phase doesnt fully work anymore (map pop up does not show rating), but ok with Caro
I did not add the tests yet as did not want to test unapproved code..
fixes #4109
fixes #4597
=> [6609 ]Ks 2022 10 support btw phases

meinberlin/apps/budgeting/predicates.py, meinberlin/apps/budgeting/rules.py, tests/budgeting/rules/test_rules_support.py, tests/budgeting/rules/test_rules_view_support.py, tests/budgeting/test_proposals_api_filtering.py, tests/budgeting/test_views_integration.py
@fuzzylogic2000 I changed the is_allowed_view_support predicate to also consider project access and live context. But I am not sure if the moderator/initiator permissions are all good there?
=> Ks 2022 11 support phase tests

meinberlin/apps/votes/dashboard.py, meinberlin/apps/votes/exports.py, meinberlin/apps/votes/views.py, tests/votes/dashboard_components/test_token_export.py
Without the laziness :), the translation.override does not work.. https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#lazy-translation
=> apps/votes/views: use gettext_lazy instead of gettext to fix tests

meinberlin/assets/scss/components/_details.scss
=> assets/details: hide the default arrow on safari fixes #4720

meinberlin/apps/budgeting/assets/ControlBarSearch.jsx, meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_commenting.scss, meinberlin/assets/scss/components/_input_group.scss, meinberlin/assets/scss/components/_participation_tile.scss, meinberlin/assets/scss/components/_poll.scss, meinberlin/assets/scss/components/_switch.scss, meinberlin/assets/scss/components/_upload.scss, meinberlin/templates/a4filters/widgets/free_text_filter.html, meinberlin/templates/a4images/image_upload_widget.html
=> [issues/updates] small fixes still from planifolia rm

package.json, webpack.common.js
* breaks compatibility with older browsers (especially IE)
* makes maplibre-gl work again
=> remove pollyfills for fetch and promise

meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_update_form.html, meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/utility.scss, meinberlin/templates/a4dashboard/includes/nav_modules.html, meinberlin/templates/a4dashboard/includes/nav_modules_item.html, meinberlin/templates/a4dashboard/includes/progress.html, package.json, requirements/base.txt
=> [#6951]scss/modal: styling modal to match design (depending on a4)

changelog/7697.md, meinberlin/apps/documents/views.py, tests/documents/test_document_api.py
Add project and chapter in paragraph context so breadcrumb template block can be abstracted for all templates.
=> [7697] add extra context in paragraph detail view

Makefile, README.md, changelog/2222.md, docs/celery.md, docs/celerybeat.md, meinberlin/config/settings/base.py, requirements/base.txt
Celery tasks can become scheduled/periodic. Periodic tasks can be enabled via django admin
@goapunk salt has celerybeat enabled via the settings, so it should work directly without additional celery beat command:
https://github.com/liqd/admin/blob/13c6c912272de9b208a257c735397ac1fbbc38a7/salt/weblate/settings.py#L925
=> Celery beat

meinberlin/apps/contrib/tasks.py
**Tasks**
I found out that we cannot have both django admin dashboard configured tasks and from the settings. Also if we switch to settings configuration of periodic tasks, the following files will be created. So if we want to switch to that configuration, we need to update the celerybeat command with a path to save the following files in the admin repo. Let me know your preferences, knowing that:
- from django admin dashboard is more accessible, and can add it immediately, but need to add them manually in every environments.  
- for settings configuration, we need to update admin repo, and then only devs can add these tasks in django settings.py
```
celerybeat-schedule.bak
celerybeat-schedule.dat
celerybeat-schedule.dir
```
=> periodic task fix for footer update

changelog/_7770.md, meinberlin/react/contrib/ModeratorStatus.jsx
removing the warning message, since it gets triggered every time ModeratorStatus receives no props. This will trigger warnings every time a card has no status assigned to it.
=> remove warning message from ModeratorStatus

changelog/7760.md, meinberlin/apps/topicprio/api.py, meinberlin/apps/topicprio/filters.py, meinberlin/apps/topicprio/serializers.py, meinberlin/apps/topicprio/templates/meinberlin_topicprio/includes/topic_list_item.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_list.html, meinberlin/apps/topicprio/templatetags/react_topics.py, meinberlin/assets/scss/components/_card.scss, meinberlin/config/urls.py, meinberlin/react/contrib/Card.jsx, meinberlin/react/contrib/CardStats.jsx, meinberlin/react/contrib/__tests__/Card.jest.jsx, meinberlin/react/contrib/__tests__/CardStats.jest.jsx, meinberlin/react/topicprio/TopicPrioList.jsx, meinberlin/react/topicprio/__tests__/TopicPrioList.jest.jsx, meinberlin/react/topicprio/react_topics_init.jsx, tests/topicprio/test_topic_api.py, tests/topicprio/test_topic_api_filtering.py, tests/topicprio/test_topics_api_pagination.py, webpack.common.js
**Tasks**
As topics are different to ideas and have less things I didn't extend the idea view set but gave topics it's own that can also be used in topic maps, but if this isn't correct please let me know!
=> [7760] add topic prio list with viewset

.eslintrc, package.json
=> deps: remove obsolete eslint-n as no node.js only npm used

meinberlin/config/settings/base.py
- remove blockquote as we don't have styling for it
- make image insertion smarter, which allows inserting images inline instead of always as block
- fix broken list properties
- remove unused customColorPalette
**Tasks**
=> settings/base: update ckeditor5 config

changelog/_9876.md, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_create_form.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_moderate_form.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_update_form.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/breadcrumb.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/documents/templates/meinberlin_documents/paragraph_detail.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_create_form.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_moderate_form.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_update_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_create_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_moderate_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_update_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_create_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_moderate_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_update_form.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_detail.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_bplan_detail.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_detail.html
**Tasks**
Go to module and create an idea if you don't already have one locally then after creation click on the idea to see the detail view, there should only be 1 set of breadcrumbs, the old should be gone, also removed on all other list based modules (check template locations for names). To check the moderate detail view find 3 dots and click bearbeiten in the menu.
=> [7861] templates/*_detail: cleaning out old code and old classes from detail pages

.github/pull_request_template.md, changelog/_6473.md
Updating our PR template for clearer communication and easier review.
At the moment, it's challenging to understand the goal of a PR and how to test it without having to ask the author. The suggested changes aim to improve the workflow for PR reviewers.
**Tasks**
=> update pr template

meinberlin/config/settings/base.py
Set the language for the ckeditor to de / german. The ckeditor interface should now be translated into german. For example in the project information settings in the dashboard.
fixes #5392 
**Tasks**
=> settings/base.py: set ckeditor5 language to de

changelog/_7762.md, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_list.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/extra_css/_swiper.scss, meinberlin/assets/js/swiper_phases.js, meinberlin/assets/scss/components_user_facing/_phase_info.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_dashboard/_variables.scss, meinberlin/assets/scss/styles_user_facing/_variables.scss, meinberlin/templates/a4modules/includes/module_detail_phase.html, meinberlin/templates/a4modules/includes/module_detail_phase_info.html, meinberlin/templates/a4modules/includes/module_detail_phase_swiper.html, meinberlin/templates/a4modules/module_detail.html, package.json
`projekte/module/module-title` (e.g., [Participatory Budgeting Phase 3](http://127.0.0.1:8003/projekte/module/participatory-budgeting-3-phase-3/))
- Implemented redesign for the Phase Info Panel component. Uses [Servicepanel](https://styleguide.berlin.de/patterns/09-vertical_marketing-page-modul-servicepanel/09-vertical_marketing-page-modul-servicepanel.html) and custom style overwrites for the swiper.
- Enhanced for both desktop and mobile views with Swiper integration.
- Desktop: ![PhaseInfo-Desktop](https://github.com/liqd/a4-meinberlin/assets/8156337/17c92f56-57f3-44a2-8a9d-3f5b451bd927)
- Mobile: <div><img src="https://github.com/liqd/a4-meinberlin/assets/8156337/0f638796-9686-45ad-a6ea-4483340abdd7" width="250"></div>
**Tasks**
=> redesign phase info component

meinberlin/apps/dashboard/templates/meinberlin_dashboard/module_blueprint_list_dashboard.html, meinberlin/assets/scss/components_user_facing/_phase_info.scss
had to copy the fullwidth styling from BO for the phase_info for the single module project pages as the page structure is different so opinionated fullwidth styling not applied (this it's either the tabs)
**Tasks**
=> Pm 2024 01 project detail

.github/workflows/django.yml, changelog/2223.md, changelog/7275.md, docs/api_caching.md, meinberlin/apps/__init__.py, meinberlin/apps/bplan/tasks.py, meinberlin/apps/extprojects/api.py, meinberlin/apps/extprojects/apps.py, meinberlin/apps/extprojects/signals.py, meinberlin/apps/plans/api.py, meinberlin/apps/plans/apps.py, meinberlin/apps/plans/signals.py, meinberlin/apps/projects/api.py, meinberlin/apps/projects/apps.py, meinberlin/apps/projects/filters.py, meinberlin/apps/projects/signals.py, meinberlin/apps/projects/tasks.py, meinberlin/config/settings/dev.py, meinberlin/config/settings/production.py, meinberlin/config/settings/test.py, meinberlin/config/settings/travis.py, requirements/prod.txt, tests/conftest.py, tests/projects/test_api_caching.py, tests/projects/test_tasks_caching.py
=> [7806] plans and projects api caching

changelog/_9993.md, meinberlin/templates/email_base.txt
Use the standarized dash dash space to allow email software to auto-detect the signature, reference (https://datatracker.ietf.org/doc/html/rfc3676#section-4.3)
**Tasks**
=> templates/email_base.txt: fix non-standard signature delimiter

meinberlin/assets/scss/components/_a4-comments.scss, package.json, requirements/base.txt
Noticed a few structural issues on main, I believe from some small refactoring done some time ago so have added a few fixes, it's a4 dependent: https://github.com/liqd/adhocracy4/pull/1522
**Tasks**
Broken version when editing comment:
what it should look like on stage:
=> assets/a4-comments: small styling fixes after functional re-write

tests/livequestions/test_livequestion_templatetags.py
Tests would occasionally fail if the category name containes a character which is escaped in html (e.g. an apostrophe)
**Tasks**
=> tests/livequestions: fix flaky templatetag tests

changelog/_5220.md, meinberlin/apps/projects/templatetags/meinberlin_project_tags.py, tests/helpers.py, tests/projects/conftest.py, tests/projects/test_project_tags.py
Change the template tag which calculates the number of contributions in a module to include the child comments
fixes #5220
Testing:
Add comments and child comments to an idea/proposal/... and check that the count is correct on the module tile (only is shown in a multimodule project)
**Tasks**
=> apps/projects: fix comment count not including child comments

meinberlin/config/settings/production.py
=> settings,prod: set redis cache timeout to 24hrs

package.json, requirements/base.txt
Update a4 tag in dependencies, preparing for new release.
tag is pushed in a4.
@goapunk 
**Tasks**
=> dependencies: update a4 tag

changelog/_8012.md, meinberlin/apps/contrib/templates/meinberlin_contrib/components/moderator_feedback.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/assets/scss/components_user_facing/_moderator_feedback.scss, meinberlin/assets/scss/components_user_facing/_moderator_status.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/_variables.scss, meinberlin/react/contrib/ModeratorStatus.jsx
**Description:**
Redesign the _moderator feedback_ element on the item detail page:
The moderator feedback can be tested on [/budgeting/2024-00014/](http://localhost:8003/budgeting/2024-00014/)
**Tasks**
=> [#8012] redesign moderator feedback

changelog/_8038.md, meinberlin/apps/contrib/templates/meinberlin_contrib/components/moderator_notes.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/assets/scss/components/_details.scss, meinberlin/assets/scss/components_user_facing/_moderator_notes.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/_variables.scss
**Description**
Redesign the moderator notes element on the item detail page:
The moderator notes can be tested on [/budgeting/2024-00014/](http://localhost:8003/budgeting/2024-00014/)
**Tasks**
=> [#8038] redesign moderator notes

changelog/_8039.md, meinberlin/apps/contrib/assets/dropdown.js, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/item_detail_dropdown.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/item_detail_labels.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_item_detail.scss, meinberlin/assets/scss/components_user_facing/_dropdown.scss, meinberlin/assets/scss/style_user_facing.scss
**Description**
Refactor and cleanup item detail section (except dropdown on a different pr)
Can be tested on [localhost:8003/budgeting/2024-00014/](http://localhost:8003/budgeting/2024-00014/)
- please make sure to add a photo to the item
- dropdown is tackled [in a different issue](https://github.com/liqd/a4-meinberlin/pull/5581), so it looks broken right now:
**Tasks**
=> [8039] redesign item detail

changelog/_8015.md, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_moderate_form.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/moderator_form.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_checkbox_field.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_field.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_field_select.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_moderate_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_moderate_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_moderate_form.html, meinberlin/assets/scss/components/_ckeditor.scss, meinberlin/assets/scss/style_dashboard.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/_form.scss, meinberlin/assets/scss/styles_user_facing/_utility.scss
update moderation form according to styleguide. 
created a reusable snippet called `moderator_form.html` and added to contrib
create a proposal on i.e [http://localhost:8003/projekte/module/participatory-budgeting-3-phase/](http://localhost:8003/projekte/module/participatory-budgeting-3-phase/)
=> [#8015] re-design moderation form

changelog/_8186.md, meinberlin/assets/scss/components_user_facing/_a4-poll.scss, meinberlin/assets/scss/style_dashboard.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/_variables.scss
Style overwrites for the poll module
Dependencies: https://github.com/liqd/adhocracy4/pull/1640
testing: create a poll module (i.e https://meinberlin-design-dev.liqd.net/projekte/digital-participation-poll-for-mitte/)
**Tasks**
=> [#8161] poll redesign

meinberlin/assets/scss/components/_poll.scss
fixes https://github.com/liqd/a4-meinberlin/issues/5616
**Tasks**
=> [#5616] reduce slider arrow size

changelog/_1112.md, requirements/dev.txt
=> requirements/dev: fix incorrect version pin of djlint

Makefile, changelog/7899.md, meinberlin/apps/bplan/forms.py, meinberlin/apps/bplan/templates/meinberlin_bplan/statement_create_form.html, meinberlin/apps/captcha/assets/captcheck.js, tests/bplan/test_views_integration.py
add captcha to bplan statement form and disable djlint rule which clashes sometimes with html quotes
testing: in the organisation dashboard, create a bplan / bebauungsplan. After creating it you can find the embed code at the bottom of the page ("Code zum Einbetten des Projekts"). Copy the url from the `src` attribute of the iframce and open it in a new tab (e.g. `http://127.0.0.1:8003/embed/projects/test/` if you called your bplan test)
**Tasks**
=> [7899] add captcha to bplan statement form

changelog/_0001.md, meinberlin/apps/dev/management/commands/create_comments.py
Add a management command to create fake comments on an idea
testing: create an idea collection module, add an idea, get the id/pk from the django admin (i.e. http://127.0.0.1:8003/django-admin/meinberlin_ideas/idea/). To create one comment as the admin user run `python manage.py create_comments --user 1 --idea <the id of the idea you just looked up> --count 1`
**Tasks**
=> add management command to create fake comments

changelog/8163.md, meinberlin/apps/extprojects/api.py, meinberlin/apps/extprojects/signals.py, meinberlin/apps/plans/api.py, meinberlin/apps/plans/models.py, meinberlin/apps/plans/signals.py, meinberlin/apps/projects/api.py, meinberlin/apps/projects/signals.py, meinberlin/apps/projects/tasks.py, requirements/base.txt, tests/plans/test_views_integration.py, tests/projects/test_api_caching.py, tests/projects/test_tasks_caching.py
add missing bits to include external projects and plans so the performance boost of the cache isn't lost
**Tasks**
=> [8163] extend caching task to external projects and plans

meinberlin/apps/projects/signals.py, tests/projects/test_tasks_caching.py
- add module publish and unpublish signals to refresh the cache
- add project_component_updated signal to refresh the cache
fixes #5684
while the phase signal I added reset the cache, it did it before the module was published in the project, so the project was not included in the active ones.
**Tasks**
=> caching: fix some cases in which the cache wasn't refreshed correctly

meinberlin/assets/scss/components_user_facing/_pill.scss
apply base text-color to all pill elements
| Before      | After |
| ----------- | ----------- |
| ![pill-before](https://github.com/user-attachments/assets/d1f5c0c4-a9e1-4bd2-a006-ea3205667eac)      | ![pill-after](https://github.com/user-attachments/assets/0dc31a48-25aa-4a0c-94f8-eca2cda36a21)      |
issue:
=> a11y issue fix: pill text color not accessible

changelog/_8422.md, meinberlin/apps/budgeting/templates/meinberlin_budgeting/includes/proposal_form.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_submit_actions.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_submit_flex_end.html, meinberlin/apps/ideas/templates/meinberlin_ideas/includes/idea_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/includes/proposal_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_form.html, meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-follow.scss
- created reusable submit for form submit on module forms
- adapted module form styles with grey background.
- moved follow to a4 folder
=> contrib/templates: create reusable form_submit_actions.html

changelog/_8424.md, meinberlin/assets/scss/components_user_facing/_button.scss, meinberlin/assets/scss/components_user_facing/_narrow-wrapper.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/templates/account/login.html, meinberlin/templates/account/password_reset.html, meinberlin/templates/account/signup.html
- Renamed `_account.scss` to `_narrow-wrapper.scss` to reflect its use on only a handful of account pages that implement a custom narrow container. This container has a special treatment of the button, which is full width on all viewports. 
- Updated relevant templates (`signup.html`, `login.html`, and `password_change.html`) to use the renamed styles.  
- Regarding the `secondary-cta` class, I applied it as a nested class since it's a one-off style, although it does not strictly follow BEM conventions. Not quite sure about that, maybe it belongs on utility?
- should i rather create a separate cta-wrapper and then take the variation into account there? 
Let me know if this works or if you'd like any adjustments!
=> templates/account: refactor narrow wrapper

changelog/_8466.md, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/styles_user_facing/_form.scss, meinberlin/react/livequestions/CategorySelect.jsx, meinberlin/react/livequestions/QuestionForm.jsx, meinberlin/react/livequestions/__tests__/__snapshots__/CategorySelect.jest.jsx.snap
Implements styling of Question Form in [[#8506] implementation](https://taiga.liqd.net/project/liqd-liquid-software/task/8506). Parent task: [#8466 [mB] interactive event: adding question (sev)](https://taiga.liqd.net/project/liqd-liquid-software/us/8466?milestone=417):
**Tasks**
=> [#8466] Interactive event: style question form

changelog/_8467.md, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components_user_facing/_card.scss, meinberlin/assets/scss/components_user_facing/_rating.scss, meinberlin/react/livequestions/Filters.jsx, meinberlin/react/livequestions/LikeCard.jsx, meinberlin/react/livequestions/QuestionBox.jsx, meinberlin/react/livequestions/QuestionForm.jsx, meinberlin/react/livequestions/QuestionList.jsx, meinberlin/react/livequestions/QuestionModerator.jsx, meinberlin/react/livequestions/QuestionUser.jsx
This PR:
1. Styles the `<Filters />` component and changes the filters to be submittable via a `<button />`
2. Add a new `<LikeCard />` component used in both `<QuestionModerator />` and `<QuestionUser />`
**Tasks**
=> #8467 Display questions (Filters and Like buttons)

changelog/_8467.md, meinberlin/assets/scss/components_user_facing/_card.scss, meinberlin/react/livequestions/LikeCard.jsx, meinberlin/react/livequestions/QuestionModerator.jsx
This PR removes the card title hover styling and changes the moderator button text.
**Tasks**
=> [#8467] Remove card title hover styling and change button text

changelog/_8467.md, meinberlin/react/livequestions/QuestionBox.jsx, meinberlin/react/livequestions/QuestionModerator.jsx, meinberlin/react/livequestions/StatisticsBox.jsx
This PR refactors the `QuestionModerator` component to a functional component, and also allows moderators to like alongside other users.
**Tasks**
=> [#8467] Allow moderators to like

changelog/_8547.md, meinberlin/assets/scss/components_user_facing/_live_questions.scss, meinberlin/react/livequestions/Filters.jsx, meinberlin/react/livequestions/QuestionBox.jsx
This PR adds the moderator `MultiSelect` filters, changes the existing categories filter to `MultiSelect`, and styles the "Show on Screen" link.
**Tasks**
=> [#8547] Add moderator MultiSelect filters and style show on screen link

meinberlin/fixtures/polls.json
Add new and non-nullable field `allow_unregistered_users` to poll fixture to make them work with the new poll model in a4
**Tasks**
=> meinberlin/fixtures: add allow_unregistered_users to poll fixture

meinberlin/apps/kiezradar/templates/meinberlin_kiezradar/search_profile_list.html, meinberlin/apps/kiezradar/templatetags/react_kiezradar_search_profiles.py, meinberlin/apps/kiezradar/urls.py, meinberlin/apps/kiezradar/views.py, meinberlin/config/urls.py, meinberlin/react/kiezradar/dummy.jsx, meinberlin/react/kiezradar/react_kiezradar_search_profiles_init.jsx, webpack.common.js
This basically just adds a mostly empty view under http://127.0.0.1:8003/account/search-profiles/ to allow further development for frontend.
cc @sevfurneaux
=> [#8646] search-profile: add dummy kiezradar search profile page for further frontend development

meinberlin/apps/contrib/templates/meinberlin_contrib/bo_component_library.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/alert.html, meinberlin/apps/contrib/templates/meinberlin_contrib/dashboard_component_library.html, meinberlin/assets/scss/components_dashboard/_alert.scss, meinberlin/assets/scss/components_user_facing/_alert.scss, meinberlin/assets/scss/styles_dashboard/_variables.scss, meinberlin/templates/a4images/image_upload_widget.html
fixes https://github.com/liqd/a4-meinberlin/issues/5848
- refactored alerts for both user-facing and dashboard 
- updated component library
**Example in use**
**Example in use**
=> alerts: refactor alerts and fix issues

changelog/_8605.md, meinberlin/apps/plans/serializers.py, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/plans/views.py, meinberlin/assets/scss/components_user_facing/_herounit_image_with_aside.scss, meinberlin/assets/scss/components_user_facing/_item_detail.scss, meinberlin/react/plans/react_projects_list.jsx, tests/plans/test_views_integration.py, webpack.common.js
This PR styles the plan detail page and adds the React `<ProjectsList />` component for projects.
**Tasks**
=> [#8605] Style plan detail page 

changelog/8543.md, docs/bplan_api.md, meinberlin/apps/bplan/serializers.py, tests/bplan/test_bplan_api.py
apps/bplan: remove char limit on name and description and instead truncate the input if too long
This means we won't save  the full name or description if it exceeds the limits. Otherwise we'd have to make a new model or change the char limit for all projects, not just bplans we don't want to do
**Tasks**
=> apps/bplan: remove char limit on name and description

docs/bplan_api.md, meinberlin/apps/bplan/serializers.py, tests/bplan/test_bplan_api.py
bplan/serializer: add binary=True to point JSONField as we receive a string containing (geo)json, not actual json. This came up during testing.
**Tasks**
=> bplan/serializer: add binary=True to point JSONField 

changelog/5925.md, meinberlin/assets/extra_css/_ckeditor.scss, meinberlin/config/settings/base.py
fix some issues with ckeditor content not shown correctly
- add missing <i> tag to allow italic in Bleach config
- add missing css for text sizing via ckeditor
fixes #5925
testing: add italic or text with different font size in the project information field in the dashboard then check on the project page that it is rendered correctly.
**Tasks**
=> fix some issues with ckeditor content not shown correctly

meinberlin/assets/scss/components_user_facing/_button.scss, meinberlin/assets/scss/components_user_facing/_service-panel.scss
Makes the Support button behave correctly after clicking with a lingering focus and the support box wrap the button correctly into a new line on mobile
fixes #5881, #5892 
**Tasks**
=> [#8530] css/support: fix styling for support button/box

changelog/8527.md, changelog/8572.md, meinberlin/assets/scss/components_user_facing/_alert.scss, meinberlin/assets/scss/components_user_facing/_leaflet.scss, meinberlin/assets/scss/components_user_facing/_multi-select.scss, meinberlin/assets/scss/components_user_facing/_projects-list.scss, meinberlin/assets/scss/components_user_facing/_projects_map.scss, meinberlin/assets/scss/components_user_facing/_projects_map_info.scss, meinberlin/assets/scss/components_user_facing/_projects_map_search.scss, meinberlin/assets/scss/components_user_facing/_typeahead.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/_base.scss, meinberlin/config/settings/base.py, meinberlin/react/contrib/forms/AutoComplete.jsx, meinberlin/react/contrib/forms/MultiSelect.jsx, meinberlin/react/contrib/forms/__tests__/AutoComplete.jest.jsx, meinberlin/react/contrib/forms/__tests__/MultiSelect.jest.jsx, meinberlin/react/contrib/forms/__tests__/useCombobox.jest.js, meinberlin/react/contrib/forms/useCombobox.js, meinberlin/react/contrib/useDebounce.js, meinberlin/react/projects/ProjectMarker.jsx, meinberlin/react/projects/ProjectsMap.jsx, meinberlin/react/projects/ProjectsMapInfo.jsx, meinberlin/react/projects/ProjectsMapSearch.jsx, package.json
add address search, zoom style and autocomplete component to project overview, also make map sticky instead of the list on overflow: auto
**Tasks**
=> [#8572] projects: add address search, zoom style and autocomplete component

changelog/8681.md, meinberlin/apps/account/templates/meinberlin_account/notifications.html, meinberlin/apps/account/urls.py, meinberlin/apps/account/views.py, meinberlin/assets/scss/components_user_facing/_actionable-list.scss, meinberlin/assets/scss/components_user_facing/_toggle_switch.scss, meinberlin/assets/scss/styles_user_facing/_utility.scss, meinberlin/react/account/NotificationToggle.jsx, meinberlin/react/account/NotificationsList.jsx, meinberlin/react/account/react_notifications.jsx, meinberlin/react/contrib/ToggleSwitch.jsx, tests/account/test_account_view.py, webpack.common.js
Implements a page for setting user notifications 
**Tasks**
cc @goapunk @m4ra no need to create a view for it, I already did that. I also added an example of what the data structure looks like the frontend code currently works with in `notifications.html`
=> [#8681] notifications-settings: add new notifications page

meinberlin/assets/scss/components_user_facing/_captcheck.scss, meinberlin/assets/scss/style_user_facing.scss
=> captcheck: add missing scss for captcheck styling

changelog/_0002.md, meinberlin/apps/bplan/serializers.py
`imghdr` support was deprecated in python, so this uses `python-magic` and built-in `mime` to check the filetype of images files for bplans created using the API.
Also reorders some conditionals to fix a bug where bug tile_image was being used instead of image_url.
Test with curl like so:
```
curl  -X POST http://127.0.0.1:8003/api/organisations/1/bplan/ \
--user 'admin@liqd.net':'password' \
-H "Content-Type: application/json" \
-d \
'
{
"name":"Luisenblock Ost - Bebauungsplan 1-70",
"bplan_id": "VI - 96a",
"description": "Test",
"url": "https://mein.berlin.de",
"office_worker_email": "test@example.com",
"start_date": "2019-01-01T00:00",
"end_date": "2022-01-01T00:00",
"image_url": "https://cdn.britannica.com/39/226539-050-D21D7721/Portrait-of-a-cat-with-whiskers-visible.jpg"
}
'
```
The …
=> apps/bplan: Replace imghdr with python-magic

changelog/_8661.md, meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html, meinberlin/apps/plans/views.py, meinberlin/assets/scss/components_user_facing/_control-bar.scss, meinberlin/assets/scss/components_user_facing/_search-profiles.scss, meinberlin/react/kiezradar/SearchProfile.jsx, meinberlin/react/kiezradar/use-create-search-profile.jest.js, meinberlin/react/kiezradar/use-create-search-profile.js, meinberlin/react/plans/SaveSearchProfile.jsx, meinberlin/react/plans/react_plans_map.jsx, meinberlin/react/projects/ProjectTopics.jsx, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx
This PR adds the "Save Search Profile" button.
**Tasks**
=> [#8661] Add 'Save Profile' button

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/plans/views.py, meinberlin/assets/scss/components_user_facing/_item_detail.scss, meinberlin/react/plans/react_projects_list.jsx
This PR fixes various [GitHub issues](https://github.com/liqd/a4-meinberlin/milestone/60) assigned to the plan detail page.
**Tasks**
=> [#8709] Plan Detail: fix github issues

changelog/_8813.md, meinberlin/assets/scss/components_user_facing/_kiezradar.scss, meinberlin/react/kiezradar/KiezradarList.jsx, meinberlin/react/kiezradar/Kiezradars.jsx
This PR adds a delete modal for deleting kiezradars.
**Tasks**
=> [#8813] Add kiezradar delete modal

changelog/8731.md, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_module_tile.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/status_bar.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components_user_facing/_module_tile.scss, meinberlin/assets/scss/components_user_facing/_project-tile.scss, meinberlin/assets/scss/components_user_facing/_status-bar.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/react/projects/ProjectTile.jsx, meinberlin/templates/a4modules/module_detail.html
adds new module tile, just the base style, grid and view all logic are coming in a later story. Also as per @MarleyMi  request we leave the grey subtitle out for now due to skzl feedback.
**Tasks**
=> modules: redesign module tiles on project page and module detail page

meinberlin/react/kiezradar/SearchProfile.jsx, meinberlin/react/kiezradar/use-create-search-profile.jest.js, meinberlin/react/kiezradar/use-create-search-profile.js, meinberlin/react/plans/SaveSearchProfile.jsx, meinberlin/react/projects/getDefaultState.js
This PR implements various search profile fixes based on these tickets:
- [#8768 Notifications should default to "on" when search profile is saved (Sev)](https://taiga.liqd.net/project/liqd-liquid-software/task/8768)
- [#8790 Send plans_only field to backend](https://taiga.liqd.net/project/liqd-liquid-software/task/8790)
- [#8818 fix issues](https://taiga.liqd.net/project/liqd-liquid-software/task/8818) (from [#8661 [mB] Kiezradar frontend: "save search" button on Project Overview page (sev)](https://taiga.liqd.net/project/liqd-liquid-software/us/8661?milestone=424))
**Tasks**
=> [#8768] [#8790] [#8818] Search profile fixes

meinberlin/templates/navigation_primary.html
This PR adds a kiezradar menu link.
**Tasks**
=> [#8751] Add kiezradar menu link

changelog/_8984.md, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/item_detail_dropdown.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/assets/scss/components_user_facing/_form-submit-flex-end.scss, meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-comments.scss, meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-modal.scss
Migrate from Bootstrap to custom CSS classes
dependency of https://github.com/liqd/adhocracy4/pull/1758
=> a4-modal: adapt styles to component refactor

changelog/8828.md, meinberlin/apps/account/templates/meinberlin_account/account_dashboard.html, meinberlin/assets/scss/components_user_facing/_tabnavigation.scss
Styles account dashboard navigation to look like tab navigation
**Tasks**
=> [#8828] account_dashboard: style tab navigation

meinberlin/apps/cms/templates/meinberlin_cms/email_form_page.html, meinberlin/apps/cms/templates/meinberlin_cms/email_form_page_landing.html, meinberlin/apps/projects/templates/meinberlin_projects/moderatorinvite_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/moderatorinvite_form.html, meinberlin/templates/account/password_reset_done.html, meinberlin/templates/account/password_reset_from_key.html, meinberlin/templates/account/verification_sent.html
**Description:**
I'm using `narrow-wrapper` class to address layout issues on pages with single or minimal form fields, ensuring the form fields no longer appear excessively wide. This is a temporary fix, and a follow-up plan includes creating a `base-narrow.html` or similar template to standardize the layout going forward [(see issue)](https://github.com/liqd/a4-meinberlin/issues/6034)
=> [#8748] adapt container width on cta pages

changelog/_8878.md, meinberlin/react/kiezradar/EditKiezradar.jsx, meinberlin/react/kiezradar/Kiezradar.jsx, meinberlin/react/kiezradar/KiezradarList.jsx, meinberlin/react/kiezradar/Kiezradars.jsx
This PR adds the kiezradar 5 limit exceeded alert.
**Tasks**
=> [#8751] Add kiezradar 5 limit exceeded alert

meinberlin/assets/scss/components_user_facing/_control-bar.scss, meinberlin/assets/scss/components_user_facing/_search-profiles.scss, meinberlin/react/plans/SaveSearchProfile.jsx
This PR fixes the search profile mobile alignment, based on GitHub issue [#8661 [mB] Kiezradar frontend: "save search" button on Project Overview page](https://github.com/liqd/a4-meinberlin/issues/6043).
**Tasks**
=> [#8892] Fix search profile mobile alignment

package.json, requirements/base.txt
updates a4 to https://github.com/liqd/adhocracy4/commit/35c4af85eb635a7469a399d340b5b1c0fb05b68c
=> update a4 info page

changelog/_8890.md, meinberlin/apps/kiezradar/templatetags/react_kiezradar.py, meinberlin/react/kiezradar/KiezradarMap.jsx
This PR adds the Berlin polygon boundary to the Kiezradar map.
Also closes this issue: [#8750 [mB] Kiezradar Frontend: Creating a Kiez (radius) - selec. neighborhood outside allowed geographical area](https://github.com/liqd/a4-meinberlin/issues/6045)
**Tasks**
=> [#8890] Add Kiezradar map Berlin polygon boundary

changelog/8897.md, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
Adds data for project detail box to project detail page, no styling, this is backend only.
**Tasks**
=> project-detail: add data for detail box

meinberlin/apps/projects/templates/meinberlin_projects/includes/contact_organisation.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/contact_person.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html
fixes https://github.com/liqd/a4-meinberlin/issues/6071 and https://github.com/liqd/a4-meinberlin/issues/6072
=> fix info-page issues

changelog/_8872.md, meinberlin/assets/scss/components_user_facing/_kiezradar.scss, meinberlin/assets/scss/components_user_facing/_modal.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/react/contrib/Modal.jsx, meinberlin/react/contrib/helpers.js, meinberlin/react/kiezradar/KiezradarList.jsx, meinberlin/react/kiezradar/SearchProfile.jsx, meinberlin/react/plans/SaveSearchProfile.jsx, meinberlin/react/plans/react_plans_map.jsx, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx, meinberlin/react/projects/getDefaultState.js
This PR adds a modal if user isn't logged in and saves the project overview filters on login redirect.
**Tasks**
=> [#8872] Add modal and save filters on login redirect

changelog/_6061.md, meinberlin/assets/js/blueprint-dialog.js, meinberlin/assets/js/blueprint-picker.js, meinberlin/assets/scss/components_dashboard/_blueprint-dialog.scss, meinberlin/assets/scss/style_dashboard.scss, meinberlin/templates/a4dashboard/includes/nav_modules.html, webpack.common.js
Fixes issue with body element being overwritten by Bootstrap modal classes https://github.com/liqd/a4-meinberlin/issues/6061 and https://github.com/liqd/a4-meinberlin/issues/6136
Also modernizing the modal by removing jQuery, Bootstrap and going for native HTML dialog and vanilla JS.
=> [#6061] a4dashboard: fix blueprints modal

meinberlin/apps/cms/templates/meinberlin_cms/blocks/project_teaser_block.html, meinberlin/assets/scss/components_user_facing/_project-teaser.scss
This PR fixes the project teaser spacing.
Resolves https://github.com/liqd/a4-meinberlin/issues/6132.
**Tasks**
=> Fix project teaser spacing

meinberlin/assets/scss/components_user_facing/_search-profiles.scss
This PR fixes the search profile button width when multiple filter pills are used.
Resolves #6086.
**Tasks**
=> Fix search profile button width

meinberlin/apps/dashboard/blueprints.py, meinberlin/apps/projects/models.py, meinberlin/config/settings/base.py
remove participatory budgeting (3 phases) from selection modal
fixes #6128
**Tasks**
=> dashboard: remove participatory budgeting 3 phases

meinberlin/apps/actions/serializers.py, meinberlin/react/account/Notifications.jsx, meinberlin/react/account/notification_data.js, tests/notifications/test_api.py
Adds a timestamp to the `ActionSerializer` to allow displaying the timestamp of offlineevents.
**Tasks**
=> [#8984] notifications: add offlineevent timestamp

meinberlin/apps/plans/forms.py, meinberlin/apps/plans/views.py, meinberlin/apps/projects/forms.py, meinberlin/fixtures/administrative_districts.json, meinberlin/react/contrib/ControlBarFilterPills.jsx, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/filter-projects.js, meinberlin/react/projects/getDefaultState.js, tests/plans/test_dashboard_views.py, tests/plans/test_forms.py
fixes #6147, #5976, #6014, #6015
You can install "Gesamtstädtisch" as a selection again by running `./manage.py loaddata meinberlin/fixtures/administrative_districts.json`
**Tasks**
=> filters: fix filter selections & saving as search profile

meinberlin/react/account/FeedItem.jsx
This PR fixes the timestamp duration (was saying `now` for notifications that had happened hours ago) and also pluralises minutes/hours.
**Tasks**
=> Notifications: fix timestamp duration

meinberlin/apps/account/templates/meinberlin_account/notification-settings.html, meinberlin/react/account/NotificationSettings.jsx, meinberlin/react/account/__tests__/NotificationSettings.jest.jsx, meinberlin/react/account/react_notification_settings.jsx, meinberlin/react/account/useNotifications.js
Fixes #6218, #6216
Also renamed `NotificationList` to be more explicitly named `NotificationSettings`
**Tasks**
=> notification-settings: fix error for non-admin users and master toggle issue

meinberlin/templates/a4modules/module_detail.html
=> module-detail: fix layout ids

meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/assets/scss/components_user_facing/_timeline.scss
fixes #6223, #6229
also remove event title as not specified in design or story, now only shows event type
**Tasks**
=> timeline: fix order and wording

meinberlin/apps/contrib/templates/meinberlin_contrib/components/hero.html, meinberlin/apps/projects/templates/meinberlin_projects/project_bplan_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-follow.scss, meinberlin/templates/a4modules/module_detail.html, package.json, requirements/base.txt
fixes: https://github.com/liqd/a4-meinberlin/issues/6085 and https://github.com/liqd/a4-meinberlin/issues/6084
=> fix follow issues

meinberlin/apps/contrib/templatetags/email_tags.py, meinberlin/config/settings/base.py, meinberlin/templates/email_base.html
this tries out if it's better to link to images instead of attaching them to emails
**Tasks**
=> mailings: link to images instead of attaching them in mails

meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_submit_flex_end.html, meinberlin/templates/account/email.html
fixes #5934
allauth view expects "action_add" in the post data, i suppose it got removed at one point
**Tasks**
=> email-form: fix error with adding a new email address

meinberlin/apps/kiezradar/models.py, meinberlin/apps/projects/api.py, meinberlin/apps/projects/serializers.py, meinberlin/react/projects/filter-projects.js, tests/kiezradar/test_search_profile.py, tests/projects/test_serializer.py
include filtering bplans by identifier in project search/kiezradar
fixes #6207
**Tasks**
=> project-search: add identifer to search field

meinberlin/apps/notifications/signals.py
Had an error that appeared when creating an idea, when `TEST` is not set in settings.
**Tasks**
=> actions: fix error when TEST is not set in settings.

meinberlin/apps/actions/apps.py, meinberlin/apps/actions/serializers.py, meinberlin/apps/kiezradar/matchers.py, meinberlin/apps/kiezradar/models.py, meinberlin/apps/kiezradar/serializers.py, meinberlin/apps/notifications/api.py, meinberlin/apps/notifications/emails.py, meinberlin/apps/notifications/signals.py, meinberlin/apps/notifications/tasks.py, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_new_search_profile_project.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_new_search_profile_project.en.email, meinberlin/apps/plans/signals.py, meinberlin/apps/plans/views.py, meinberlin/react/account/Notifications.jsx, meinberlin/react/account/notification_data.js, tests/kiezradar/test_full_text_search.py, tests/kiezradar/test_search_profile.py, tests/notifications/test_emails.py, tests/projects/test_insights.py
This changes the previous `get_search_profiles_for_project` logic to also match plans and updates all related code to handle notifications for when a plan is published that matches a search profile.
this fixes #6259
**Tasks**
=> notifications: add logic for plan matching to notifications for search profiles

meinberlin/apps/cms/templatetags/menu.py, meinberlin/assets/scss/components_user_facing/_header.scss, meinberlin/templates/header.html, meinberlin/templates/navigation_primary.html
This PR adds a menu notification counter.
**Tasks**
=> [#9001] Add menu notification counter

meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_actions.html, meinberlin/templates/a4modules/module_detail.html
uses `history.back` instead of hardcoded links 
**Tasks**
=> [#9000] project-actions: overhaul back button and add to other pages

meinberlin/assets/scss/components_user_facing/_projects_map.scss
This PR fixes the map tile panel spacing.
Resolves #6377.
**Tasks**
=> Fix map tile panel spacing

changelog/0000.md, meinberlin/apps/plans/serializers.py
For projects we have the status as:
> past is 2, future is 1, active is 0
this is a quick fix to change the status of plans to represent the same numbering.
**Tasks**
=> plans: change serializer to return 2 in case status = 1

changelog/0000.md, meinberlin/apps/bplan/views.py, meinberlin/apps/projects/views.py
=> bplan: add dispatch mixin to display statement form instead of project detail page

changelog/6441.md, meinberlin/apps/notifications/tasks.py, tests/notifications/test_tasks.py
There was an issue with new notifications being deleted instead of old ones due to a logic error in the task code. This fixes it.
fixes #6441
=> notifications: fix task causing it to delete new notifications instead of old ones

changelog/627.md, meinberlin/assets/scss/components_user_facing/_item_detail.scss
Fixed Dropdown in Archived Proposal
Original Github Issue: [Link](https://github.com/liqd/a4-meinberlin/issues/6275)
**Test**
- Visit an archived proposal, switch to mobile view in dev tools, click the dropdown
**Tasks**
=> St-627 Fix archived proposal dropdown

changelog/8876.md, meinberlin/apps/projects/insights.py, meinberlin/apps/projects/signals.py, tests/projects/test_insights.py
apps/projects:statistics topic/maptopic no longer get counted as ideas
**Tasks**
=> [ST-623]  apps/projects:insights changed whats get counted to ideas

changelog/622.md, meinberlin/apps/kiezradar/matchers.py, tests/kiezradar/test_search_profile.py
Fixes #6463 
Ticket: https://app.asana.com/1/1175467295883992/project/1208559589495764/task/1210636917477153?focus=true
Custom Kieze dont get Notifications for Projects without Points (Coordinates) anymore. 
**Tasks**
=> [ST-622] Custom Kieze change Notification behaviar

changelog/6290.md, meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-poll.scss
https://github.com/liqd/a4-meinberlin/issues/6290
assets/scss: Correct tab focus styling on answer navigation arrows
**Tasks**
=> [ST-626] assets/scss: Correct tab focus styling on answer navigation arrows

changelog/643.md, meinberlin/react/kiezradar/Kiezradars.jsx, meinberlin/react/kiezradar/SearchProfiles.jsx
Made wording of deletion alerts consistent
**Reproduce**:
Delete a Search Profile / Saved Search, and delete a custom Kiez
**Tasks**
=> ST643: apps/kiezradar: Make deletion alerts consistent in their wording

changelog/6432.md, meinberlin/assets/js/swiper_phases.js
Because swiper.js adds some elements via shadow DOM, and shadow DOM implementation different for ios Safari, a css class was not getting applied to pagination bullets, resulting in them being the wrong size.
Fix needed to be adding inline css to the existing injection of the element which the swiper initialization handles.
Issue reported on multi-phase participatory budgeting projects, like: https://meinberlin-design-dev.liqd.net/projekte/module/burgerinnenhaushalt-2-phasen-17/
=> [ST-624] assets/js: fix swiper bullet ios safari with inline css

changelog/634.md, meinberlin/apps/dashboard/templates/meinberlin_dashboard/module_blueprint_list_dashboard.html
Removed breadcrumbs from Module creation dialog 
**Reproduce**
Edit a project, click "Add module"
**Tasks**
=> ST-634: Remove breadcrumbs from blueprints dialog

meinberlin/assets/scss/components_user_facing/_projects-list.scss, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/ProjectsList.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx
Adds button at bottom of search results allowing user to search past projects.
There was also an existing "bug" that when all projectStatus filter pills are removed, the UI just allows this faulty search to happen (there will always be 0 results because no projectStatus is specified). I fixed that as part of this, so if someone removes the 'abgeschlossen' pill it goes back to regular search.
Kiezradar react components are already showing some tech debt. Much of the `ProjectsControlBar` state needs to be hoisted into parent `ProjectsListMapBox`. Trying to edit state from another child `ProjectsList` reveals the problems with the current approach where state lives in the control bar - it's getting to be a little spaghetti and I got this feature done without the big refactor which would be …
=> [ST-741] apps/kiezradar: add show completed projects
