liqd/a4-meinberlin

apps/users/__init__.py, apps/users/adapters.py, apps/users/admin.py, apps/users/apps.py, apps/users/migrations/0001_initial.py, apps/users/models.py, meinberlin/settings.py, meinberlin/urls.py
Test-URLs: `/accounts/login/`,`/accounts/signup/`,`/accounts/logout/`
=> Basic users

apps/cms/migrations/0003_menu.py, apps/cms/models.py, apps/cms/templatetags/menu.py, meinberlin/templates/base.html
this replaces the hard-coded menu by one that is created with wagtail.
To use, go to "snippets" in the wagtail admin and create a menu called "topnav".
=> Wagtail menu

.gitignore, Makefile, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_header.scss, meinberlin/templates/base.html, meinberlin/urls.py, package.json, webpack.config.js
This sets up webpack, similar to how it is done in https://github.com/liqd/euth_wagtail/.
I am not totally sold on webpack yet.
- Pros
- used in euth_wagtail
- good support for es6, jsx, sass, postcss and many other tools
- powerful dependency management
- Cons
- complicated
- slow
My proposal is to merge this now to get started and to switch to something else if/when we find a better solution.
=> setup webpack

.gitignore, apps/ideas/templates/meinberlin_ideas/idea_detail.html, meinberlin/assets/js/app.js, meinberlin/assets/js/dropdown.js, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_breadcrumbs.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_form.scss, meinberlin/assets/scss/components/_rating.scss, meinberlin/assets/scss/components/_resource_header.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/base.html, package.json, webpack.config.js
most of this is preliminary, but it should be fine for now.
It is not yet clear how much adhocracy4 core will dictate in terms of UI
approach.  For example, the rating template from core requires font-awesome
which I had not expected. It also uses a rather complex HTML structure,
probably because of bootstrap.
The JavaScript I wrote for the dropdown should probably be replaced, but I have
not yet found a good library.
=> idea detail styling

.gitignore, apps/ideas/templates/meinberlin_ideas/idea_detail.html, meinberlin/assets/js/app.js, meinberlin/assets/js/dropdown.js, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_breadcrumbs.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_form.scss, meinberlin/assets/scss/components/_rating.scss, meinberlin/assets/scss/components/_resource_header.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/base.html, package.json, webpack.config.js
Not much, but for me this shortens initial build time from 7s to 6s.
Also note that when using `webpack --watch`, the initial build is still slow,
but successive builds are significantly faster because the dependency tree is
cached.
=> optimize webpack performance

apps/ideas/forms.py, apps/ideas/rules.py, apps/ideas/templates/meinberlin_ideas/idea_confirm_delete.html, apps/ideas/templates/meinberlin_ideas/idea_create_form.html, apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/ideas/templates/meinberlin_ideas/idea_update_form.html, apps/ideas/templates/meinberlin_ideas/includes/idea_form.html, apps/ideas/urls.py, apps/ideas/views.py, meinberlin/assets/js/app.js, meinberlin/settings/base.py, meinberlin/templates/base.html
Allows to create, edit and delete ideas.
=> Basic idea forms

apps/ideas/models.py, apps/ideas/templates/meinberlin_ideas/idea_detail.html, meinberlin/assets/js/app.js, meinberlin/settings/base.py, meinberlin/urls.py
=> add a4 comments to idea

meinberlin/assets/scss/components/_comments.scss, meinberlin/assets/scss/components/_label.scss, meinberlin/assets/scss/style.scss
=> some comment styling

meinberlin/settings/base.py
Reflects A4 change [#19](https://github.com/liqd/adhocracy4/pull/19)
=> update comment config name

meinberlin/assets/scss/components/_rating.scss
if rating is not possible, the background should not change on hover
=> fix rating hover

apps/contrib/apps.py, apps/contrib/templates/meinberlin_contrib/includes/sort.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/ideas/views.py, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/settings/base.py
Adds sorting functionality to the idea list.
Depends on [https://github.com/liqd/adhocracy4/pull/26](https://github.com/liqd/adhocracy4/pull/26)
=> idea list sorting

.eslintrc, .polylintrc, meinberlin/assets/js/app.js, package.json, webpack.config.js
configuration copied from euth_wagtail
=> add eslint

apps/documents/api.py, apps/documents/assets/Paragraph.jsx, apps/documents/assets/ParagraphBox.jsx, apps/documents/serializers.py, apps/documents/templates/meinberlin_documents/document_form.html, apps/documents/templates/meinberlin_documents/react_paragraphs.html, apps/documents/templatetags/react_paragraphs.py, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_button.scss, meinberlin/urls.py, package.json, webpack.config.js
This adds UI to create/edit a document. The editor is implemented as a react app.
Note that the editor is not avilable in a special edit view. Instead, it replaces the document detail view in the `create_document` phase.
The code is very similar to what is used in euth_wagtail. I mostly adapted the UI and did some minor refactoring to increase readability. I also tried to reduce flickering by only reloading ckeditor in certain cases (see a4fc734). @slomo, @vellip what do you think about the approach?
=> Document edit UI

.stylelintrc.json, meinberlin/assets/scss/_base.scss, package.json
I looked throught the stylelint options and added some that looked useful.
=> stricter CSS linting

apps/contrib/templates/meinberlin_contrib/includes/sort.html, apps/dashboard/templates/meinberlin_dashboard/dashboard_base.html, apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/users/templates/meinberlin_users/indicator.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_rating.scss
I did two pull request to core that change HTML:
- https://github.com/liqd/adhocracy4/pull/25 (ratings, already merged)
- https://github.com/liqd/adhocracy4/pull/23 (comments, not yet merged)
Both require adjustments in our CSS, which is done in this pull-request.
Note that I added the `dropdown-item` class from bootstrap4 in 0cb42db. This is not yet used (because it would also need to be added in core) but may allow us to simplify the code in the future.
=> Adapt to (proposed) HTML changes in core

apps/contrib/templates/meinberlin_contrib/includes/sort.html, apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, apps/dashboard/templates/meinberlin_dashboard/dashboard_base.html, apps/dashboard/templates/meinberlin_dashboard/includes/blueprint_list_tile.html, apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/users/templates/meinberlin_users/indicator.html, meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/components/_dropdown.scss
just some small changes that were quick to do. more is coming.
=> dashboard style improvements

.stylelintrc.json, apps/dashboard/templates/meinberlin_dashboard/includes/phase_form.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_info.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_participate.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_result.html, apps/dashboard/templates/meinberlin_dashboard/project_create_form.html, apps/dashboard/templates/meinberlin_dashboard/project_update_form.html, apps/documents/assets/Paragraph.jsx, apps/documents/assets/ParagraphBox.jsx, apps/ideas/templates/meinberlin_ideas/includes/idea_form.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_label.scss, meinberlin/assets/scss/components/_pagination.scss, meinberlin/assets/scss/components/_rating.scss, meinberlin/assets/scss/style.scss
Originally I only wanted to add some styling to forms. But I stumbled upon a lot of code that needed refactoring. So this pull request got a bit messy. Sorry.
=> Form groups / refactoring

meinberlin/assets/scss/components/_tabs.scss
=> avoid styling ckeditor tabs

meinberlin/templates/account/base.html, meinberlin/templates/base.html
https://github.com/liqd/a4-meinberlin/pull/40 broke the login and other account pages. I fixed by overwriting the account base template.
I am not sure whether `super_base.html` is the best idea, but it works for now.
=> Fix login/register layout

apps/documents/assets/Paragraph.jsx, apps/documents/assets/ParagraphBox.jsx
@slomo maybe some of these changes can be ported to euth_wagtail?
=> Improve error reporting in document edit app

apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/components/_tile.scss, meinberlin/assets/scss/style.scss
It just came to my mind that using flexbox here might actually work quite well, so I quickly implemented a frist version.
=> implement same-height tiles

.stylelintrc.json, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/components/_button.scss, package.json
=> use stylelint standard config

.gitignore, meinberlin/settings/base.py, meinberlin/urls.py
Should fix #48, but need to test on server to be sure.
=> Ckeditor images

apps/projects/templates/a4projects/includes/project_list_tile.html, apps/projects/templates/a4projects/project_list.html, apps/projects/urls.py, apps/projects/views.py, meinberlin/assets/scss/_layout.scss, meinberlin/urls.py
This adds a very simple project list.
Since the project-detail view is already in core, it may be a good idea to move the project-list view to core, too. But I guess we can first see what we have to add to it here and move it later if it still seems like a good idea.
=> simple project list

meinberlin/assets/scss/components/_portal_header.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/base.html, meinberlin/templates/portal_header.html
This adds the portal header (aka "light blue berlin header"). I modeeled it close after the one on http://www.berlin.de/politik-verwaltung-buerger/, copying most of the CSS from there. The name "portal header" also comes from the code on berlin.de.
=> Add portal header

.polylintrc, package.json
fix polylint.rc to support commits without activated virtual env
=> change polylint.rc 

apps/ideas/forms.py, apps/ideas/migrations/0002_idea_category.py, apps/ideas/models.py, apps/ideas/templates/meinberlin_ideas/includes/idea_form.html, apps/ideas/views.py, meinberlin/settings/base.py
depends on: https://github.com/liqd/adhocracy4/pull/37
=> Select categories for ideas

apps/contrib/templates/meinberlin_contrib/includes/filter_and_sort.html, apps/ideas/models.py, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/ideas/views.py, requirements/base.txt
Requires: https://github.com/liqd/adhocracy4/pull/39
Open issues:
- The filtering/sorting parameters  do not work with pagination and will be fixed separately
- form needs to be styled
- Do not display empty filter (e.g. no categories)
=> Filter ideas by category

meinberlin/assets/scss/_layout.scss
=> add clearfix to wrapper

meinberlin/assets/scss/_variables.scss
better distinguished from brand-secondary
=> change brand-danger color

apps/ideas/templates/meinberlin_ideas/idea_detail.html, apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_category.scss, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_resource_header.scss, meinberlin/assets/scss/style.scss
see https://github.com/liqd/a4-meinberlin/pull/77#issuecomment-283002124
=> style category

apps/contrib/templates/meinberlin_contrib/includes/filter_and_sort.html, meinberlin/assets/scss/components/_filter_bar.scss
this uses a grad based two-column layout for small screens and a simple inline layout on large screens (if wrapping occurs in this mode, it may look at bit broken but is still usable).
The code is a bit hacky but not too much (I hope).
=> responsive filter UI

apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, meinberlin/assets/scss/components/_rating.scss
there have been some changes to ratings, so the list items needed to be adapted.
=> Fix rating in list item

apps/contrib/templates/meinberlin_contrib/includes/form_checkbox_field.html, apps/dashboard/forms.py, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_result.html, meinberlin/assets/scss/_form.scss
=> Add archive setting to dashboard

meinberlin/assets/scss/components/_alert.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_hero_unit.scss, meinberlin/templates/base.html
fixes #82
We thought about making it more noticable by use of color, but did not have a good idea yet. This might come in a second step.
=> change alert styling

apps/embed/apps.py, apps/embed/templates/meinberlin_embed/embed.html, apps/embed/urls.py, apps/embed/views.py, meinberlin/settings/base.py, meinberlin/static/embed.css, meinberlin/static/embed.js, meinberlin/urls.py
This adds the basic structure for embedding. It is mostly based on 2017-01-tb-embed.
Not that the JavaScript is only a first version demonstrating the general mechanism. Many edge-cases are not yet handled (see FIXMEs).
=> initial embedding

meinberlin/templates/email_base.html
=> adapt email base template

apps/cms/templates/meinberlin_cms/email_form_page.html, apps/cms/templates/meinberlin_cms/email_form_page_landing.html, apps/contrib/templates/meinberlin_contrib/includes/form_field.html, meinberlin/assets/scss/_form.scss, meinberlin/settings/base.py, requirements/base.txt
I went trough all field types available from the wagtail UI and made sure that they are styled properly.
=> improve email form templates

apps/embed/views.py, docs/embed.md, meinberlin/static/embed.js
This adds documentation for embedding. It describes the current approach and its impact on the overal application as well as the background knowledge we aquired through time. Feedback is very welcome, especially from @slomo and @MagdaN.
=> Document embedding

meinberlin/assets/scss/components/_filter_bar.scss
see https://github.com/liqd/a4-meinberlin/pull/98#discussion_r105117491
=> fix filter bar ordering position on mobile

meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_hero_unit.scss, meinberlin/assets/scss/components/_portal_header.scss, meinberlin/assets/scss/components/_resource_header.scss
=> improve resource header

docs/embed.md
=> document restriction on using the `safe` filter

meinberlin/assets/scss/components/_alert.scss, meinberlin/static/embed.js
first commit was supposed to be named "add test", duh.
=> implement warning for 3rd party cookies disabled

apps/users/templates/meinberlin_users/indicator.html, meinberlin/templates/header.html
checked with https://validator.w3.org/unicorn/
=> fix html validation errors

meinberlin/static/embed.js
=> fix error when parsing onmessage JSON

Makefile, package.json
to be more in line with other a4 projects
=> add make lint target

Makefile
The `watch` target starts a dev server and rebuilds js and css files
with webpack on changes.
=> Add watch target that rebuilds assets on change

apps/documents/assets/ParagraphBox.jsx, apps/documents/templates/meinberlin_documents/react_paragraphs.html, apps/documents/templatetags/react_paragraphs.py
this fixes an XSS vulnaraibility
See also https://github.com/liqd/adhocracy4/pull/61
=> pass parameters to javascript by data attributes

apps/budgeting/forms.py, apps/budgeting/rules.py, apps/budgeting/templates/meinberlin_budgeting/proposal_detail.html, apps/budgeting/templates/meinberlin_budgeting/proposal_moderate_form.html, apps/budgeting/urls.py, apps/budgeting/views.py
This adds a very basic moderator form
=> Add moderator feedback form

meinberlin/settings/base.py, meinberlin/urls.py
Reflects: https://github.com/liqd/adhocracy4/pull/56
Merge when core is merged.
=> Use API for generic foreign keys

apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components/_comments.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_list.scss, meinberlin/assets/scss/components/_portal_header.scss, meinberlin/assets/scss/components/_resource_header.scss, meinberlin/assets/scss/style.scss
see individual commit messages
=> some small UI adjustments

apps/dashboard/views.py
Fixes permission check for editing projects of other organisations.
=> Filter projects by organisation for update view

apps/ideas/views.py
Making queryset customization with filters consistent.
=> Customize queryset in view instead of filter

apps/dashboard/templates/meinberlin_dashboard/email.html, apps/dashboard/templates/meinberlin_dashboard/password.html, meinberlin/assets/scss/components/_multiform.scss, meinberlin/assets/scss/style.scss
=> style account settings

apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tablist.html
Even though they are valid html, I don't think that's something we need.
=> remove number sign from ids

.gitignore, Makefile, meinberlin/settings/base.py
- add make rules
- Use dedicated test database
=> improve test setup

apps/dashboard/mixins.py, apps/dashboard/views.py
=> moderator refactoring

apps/account/apps.py, apps/account/forms.py, apps/account/templates/meinberlin_account/account_dashboard.html, apps/account/templates/meinberlin_account/email.html, apps/account/templates/meinberlin_account/password.html, apps/account/templates/meinberlin_account/profile.html, apps/account/urls.py, apps/account/views.py, apps/dashboard/forms.py, apps/dashboard/templates/meinberlin_dashboard/base_dashboard.html, apps/dashboard/urls.py, apps/dashboard/views.py, apps/users/templates/meinberlin_users/indicator.html, meinberlin/settings/base.py, meinberlin/urls.py
Also fixes the active menu item task taiga#844
=> Move user settings to account app

apps/cms/emails.py, apps/cms/migrations/0006_auto_20170412_1529.py, apps/cms/models.py
Needed for the user feedback form.
=> send frombuilder form results as text

meinberlin/assets/scss/components/_fixed_side.scss, meinberlin/assets/scss/style.scss, meinberlin/templates/base.html
note that I hardcoded the path /feedback/
=> add feedback button

requirements/dev.txt
=> pin pydocstyle

requirements/dev.txt
fake-factory has been renamed to Faker. Adapt to the name change and add the correct dependency
=> Update fake-factory to Faker

apps/maps/management/commands/import_geodata.py, apps/maps/migrations/0002_auto_20170420_1313.py, apps/maps/migrations/0003_auto_20170420_1321.py, apps/maps/models.py
based on https://github.com/liqd/adhocracy3/blob/master/src/adhocracy_meinberlin/adhocracy_meinberlin/scripts/ad_import_geodata.py
=> Script to import berlin geo data

meinberlin/settings/dev.py, meinberlin/urls.py
The required steps to include the toolbar changes with the version bumped by pyup
=> Fix inclusion of the django debug toolbar

apps/documents/models.py, apps/documents/serializers.py, apps/documents/validators.py, tests/conftest.py, tests/documents/conftest.py, tests/documents/factories.py, tests/documents/test_document_api.py, tests/documents/test_document_models.py, tests/documents/test_document_views.py, tests/factories.py
- add validatos as in (https://github.com/liqd/a4-opin/pull/788/commits/7e2ddee720ffcc03c28931a8e6ac865500ca1c2d)
- copy document tests from a4-opin
=> Allow only one document per project

apps/dashboard/forms.py, apps/dashboard/mixins.py
Unfortunately this does not prevent from removing start/end dates from already published projects. Is this required?
=> Prevent projects containing phases without dates from publishing

meinberlin/assets/scss/_shame.scss
To make it look like in the design.
=> add map min-height

apps/budgeting/views.py, apps/mapideas/views.py
Extend  `super()get_queryset` instead of the `qs` property of filter
=> Refactor queryset of list view

apps/projects/views.py
Fixes https://github.com/liqd/a4-meinberlin/issues/243
=> Exclude draft projects from project list

meinberlin/assets/scss/components/_phases.scss
fixes #250.
Note that this fixes only the vertical spacing and does not do any other styling changes.
=> Fix horizontal spacing in phase-list

apps/dashboard/filtersets.py, apps/projects/views.py
Depends on https://github.com/liqd/adhocracy4/pull/81
=> Filter archived projects per default

apps/documents/api.py, apps/documents/assets/ParagraphBox.jsx, apps/documents/rules.py, apps/documents/serializers.py, apps/documents/views.py, meinberlin/urls.py, tests/documents/test_document_api.py
Depends on https://github.com/liqd/adhocracy4/pull/80
Changes document API URL to: `/api/modules/<module_slug>/documents/`
@vellip, @xi:
Need to adjust the js/react code to use the new URL.
=> Fix document permissions

apps/polls/apps.py, apps/polls/assets/Polls.jsx, apps/polls/templates/meinberlin_polls/poll_detail.html, apps/polls/templatetags/react_polls.py, apps/polls/urls.py, apps/polls/views.py, meinberlin/assets/js/app.js, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_poll.scss, meinberlin/assets/scss/style.scss, meinberlin/assets/scss/utility.scss, meinberlin/settings/base.py, meinberlin/urls.py
this implements a react component and styling for the poll detail view. It currently uses hardcoded sample data as the API and models are not ready yet.
=> poll detail component

.gitignore, webpack.config.js
=> have separate bundles for leaflet

apps/polls/admin.py, apps/polls/assets/Polls.jsx, apps/polls/migrations/0002_poll_weight.py, apps/polls/migrations/0003_auto_20170426_1716.py, apps/polls/models.py, apps/polls/phases.py, apps/polls/templates/meinberlin_polls/poll_list.html, apps/polls/templatetags/react_polls.py, apps/polls/views.py
this replaces the sample data with real data from the model. Note that `object` in the poll detail view is currently not defined, so it does not yet work.
=> poll: pass real data to react

.gitignore, apps/embed/templates/meinberlin_embed/embed.html, meinberlin/templates/base.html, webpack.config.js
See https://github.com/liqd/a4-opin/pull/693
=> Remove clash between adhocracy4 library names

meinberlin/assets/scss/components/_embed-layout.scss
=> change embed shell styling

apps/dashboard/blueprints.py, apps/polls/phases.py
=> Remove comment phase from polls

meinberlin/assets/scss/components/_resource_header.scss
=> fix blue-ish tinted resource images

apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, meinberlin/assets/scss/components/_tile.scss
=> show image in project tiles

apps/users/hashers.py, meinberlin/settings/base.py
Needed to migrate A2 users to A4.
=> Add a2 password hasher

apps/contrib/templates/meinberlin_contrib/item_detail.html, apps/topicprio/templates/meinberlin_topicprio/topic_detail.html
this is also used in core (comments)
=> use ellipsis-h instead of ellipsis-v

meinberlin/assets/scss/components/_button.scss, meinberlin/templates/base.html
=> define button--attached-top

apps/polls/assets/ChoiceForm.jsx, apps/polls/assets/PollManagement.jsx, apps/polls/assets/QuestionForm.jsx, meinberlin/assets/scss/components/_commenting.scss
still to do:
-   choice input and delete button should be in a single line
-   choice field should not have a (visible) label
=> improve poll management styling

apps/budgeting/templates/meinberlin_budgeting/proposal_create_form.html, apps/budgeting/templates/meinberlin_budgeting/proposal_moderate_form.html, apps/budgeting/templates/meinberlin_budgeting/proposal_update_form.html, apps/contrib/templates/meinberlin_contrib/item_detail.html, apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_create_breadcrumbs.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_update_breadcrumbs.html, apps/documents/templates/meinberlin_documents/paragraph_detail.html, apps/ideas/templates/meinberlin_ideas/idea_create_form.html, apps/ideas/templates/meinberlin_ideas/idea_update_form.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_create_form.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_update_form.html, apps/polls/templates/meinberlin_polls/poll_management_form.html, apps/topicprio/templates/meinberlin_topicprio/topic_detail.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_create_form.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_list.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_update_form.html
to distinguish it from other navigations when using landmarks
=> add label to breadcrumbs navigation

meinberlin/assets/scss/_variables.scss
=> update body colour

meinberlin/assets/scss/components/_dropdown.scss
Two ideas I had to improve dropdown styling. I am not totally conviced myself.
=> dropdown styling

apps/polls/assets/Question.jsx, apps/polls/templatetags/react_polls.py
this can probably be refactored to be more generic, but I went with a simple solution for now.
=> link to login on poll without authentication

apps/dashboard/forms.py, apps/dashboard/templates/meinberlin_dashboard/external_project_create_form.html, apps/dashboard/templates/meinberlin_dashboard/external_project_update_form.html, apps/dashboard/templates/meinberlin_dashboard/includes/external_project_form.html
=> Enable date picker for external projects

apps/polls/assets/Question.jsx, meinberlin/assets/scss/components/_poll.scss
=> smaller poll ui adjustments

apps/documents/models.py, apps/notifications/emails.py, apps/notifications/signals.py, apps/notifications/templates/meinberlin_notifications/emails/notify_creator.en.email, apps/notifications/templates/meinberlin_notifications/emails/notify_followers_new_item.en.email, apps/notifications/templates/meinberlin_notifications/emails/notify_followers_over_soon.en.email, apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.en.email, apps/notifications/templatetags/verbose_name.py, meinberlin/settings/base.py
=> Add first draft for notification mails based on opin

apps/account/forms.py, apps/account/templates/meinberlin_account/profile.html, apps/documents/models.py, apps/notifications/emails.py, apps/notifications/signals.py, apps/notifications/templates/meinberlin_notifications/emails/notify_creator.en.email, apps/notifications/templates/meinberlin_notifications/emails/notify_followers_new_item.en.email, apps/notifications/templates/meinberlin_notifications/emails/notify_followers_over_soon.en.email, apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.en.email, apps/notifications/templatetags/verbose_name.py, apps/users/migrations/0002_user_get_notifications.py, apps/users/models.py, meinberlin/settings/base.py
=> Add get_notifications setting to user model

apps/bplan/management/commands/bplan_auto_unpublish.py
To be used with a cronjob to unpublish finished bplan projects.
=> Bplan auto unpublish command

apps/polls/assets/Question.jsx, apps/polls/templatetags/react_polls.py
@kleingeist this still is possible via API, I presume. I wasn't too sure where to do that. Either put it in an issue or fix if you find time.
=> avoid voting for ended projects

apps/dashboard/templates/meinberlin_dashboard/base_dashboard.html, meinberlin/assets/scss/components/_dashboard_nav.scss
=> style dashboard nav

apps/polls/templates/meinberlin_polls/poll_404.html, apps/polls/views.py
If the modules Poll has not been created yet a custom 404 page with a condititonal link to the dashboard is shown
=> Add poll 404 page

apps/contrib/static/js/formset.js
=> add document ready to formset js

apps/dashboard/templates/meinberlin_dashboard/project_list.html
=> Add pagination to dashboard project list.

apps/dashboard/templates/meinberlin_dashboard/project_moderators.html
=> Add "back to dashboard" link to the moderators edit view.

meinberlin/templates/404.html, meinberlin/templates/500.html, meinberlin/templates/base_errors.html
=> improve error page

apps/polls/migrations/0003_choice_order.py
fixup to https://github.com/liqd/a4-meinberlin/pull/382
=> add missing poll migration

apps/account/templates/meinberlin_account/account_dashboard.html
=> adapt account settings to changes in #321

meinberlin/templates/email_base.html
Just a little cleanup and text alignment unification
=> smaller email style adjustments

apps/contrib/templates/meinberlin_contrib/item_detail.html, apps/topicprio/templates/meinberlin_topicprio/topic_detail.html
avoids that the dropdown is outside of the screen
fixup to #330
=> fix item action styling

apps/budgeting/templates/meinberlin_budgeting/proposal_confirm_delete.html, apps/budgeting/templates/meinberlin_budgeting/proposal_create_form.html, apps/budgeting/templates/meinberlin_budgeting/proposal_moderate_form.html, apps/budgeting/templates/meinberlin_budgeting/proposal_update_form.html, apps/ideas/templates/meinberlin_ideas/idea_confirm_delete.html, apps/ideas/templates/meinberlin_ideas/idea_create_form.html, apps/ideas/templates/meinberlin_ideas/idea_update_form.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_confirm_delete.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_create_form.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_update_form.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_confirm_delete.html
edit/create form and delete confirm should have same width as detail
=> limit form width

apps/cms/migrations/0007_simplepage.py, apps/cms/models.py, apps/cms/templates/meinberlin_cms/simple_page.html, meinberlin/assets/scss/components/_simple_page.scss, meinberlin/assets/scss/style.scss
basically a copy from tempelhof
=> add simple pages

apps/cms/templates/meinberlin_cms/blocks/projects_block.html, meinberlin/assets/scss/components/_blocks.scss
=> add "show all" button to projects block

apps/projects/templates/meinberlin_projects/project_detail.html
=> add edit button on project detail

apps/dashboard/templates/meinberlin_dashboard/includes/project_list_item.html, apps/polls/templates/meinberlin_polls/base_management.html, apps/polls/templates/meinberlin_polls/poll_management_form.html
=> change dashboard button order

apps/dashboard/templates/meinberlin_dashboard/project_moderators.html, apps/polls/assets/ChoiceForm.jsx, meinberlin/assets/scss/_form.scss
To have an input and an action next to each other.
=> input action element

meinberlin/templates/account/email_confirm.html, meinberlin/templates/account/login.html, meinberlin/templates/account/logout.html, meinberlin/templates/account/password_reset.html, meinberlin/templates/account/password_reset_from_key.html, meinberlin/templates/account/signup.html
=> allauth templates

apps/cms/templates/meinberlin_cms/blocks/cta_block.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_participate.html, apps/dashboard/templates/meinberlin_dashboard/project_moderators.html, apps/polls/assets/Question.jsx, apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_alert.scss, meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_comments.scss, meinberlin/assets/scss/components/_datepicker.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_label.scss, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_phases.scss, meinberlin/assets/scss/components/_poll.scss, meinberlin/assets/scss/components/_project_header.scss, meinberlin/assets/scss/components/_radio.scss, meinberlin/assets/scss/components/_tile.scss, meinberlin/templates/base.html
This takes care of #289 by switching brand-primary and brand-secondary. These colours and their usage should be unified with this.
=> colour variables

meinberlin/assets/scss/components/_commenting.scss
=> increase commenting title font-size

apps/polls/assets/Question.jsx, meinberlin/assets/js/app.js, meinberlin/static/embed.js
=> implement custom API to get current href

apps/polls/assets/Question.jsx
=> Fixup color variables

meinberlin/static/embed.js
fixes #420
@vellip: Was there any reason to use the general handler?
=> embed: only handle ajax errors from navigation

apps/budgeting/views.py, apps/ideas/views.py, apps/mapideas/views.py, apps/topicprio/views.py
Depends on liqd/adhocracy4#98
Fixes #403
=> Use paging aware filtersets.

apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_list_item.html, apps/topicprio/templates/meinberlin_topicprio/includes/topic_list_item.html
=> consistent list item labels

apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, apps/topicprio/templates/meinberlin_topicprio/topic_list.html, meinberlin/assets/scss/components/_filter_bar.scss
fixes #166 
This only does the top portion of it, I think the pagination is fine where it is for now. `margin-bottom` as well as `position: relative` work fine here, I don't think the additional space coming with `position: relative` is a problem here.
=> 2017 05 pv filterbar overlap

apps/polls/assets/ChoiceForm.jsx, meinberlin/assets/scss/_form.scss
Not a perfectly clean solution, but works for now.
Note that the grid is %-based, so nested grids will not necessarily align to the global grid. (They will have the right gutters, though).
=> limit poll choice width

apps/budgeting/templates/meinberlin_budgeting/includes/proposal_list_item.html, apps/contrib/static/js/Alert.jsx, apps/contrib/templates/meinberlin_contrib/includes/inline_form.html, apps/contrib/templates/meinberlin_contrib/item_detail.html, apps/contrib/templates/meinberlin_contrib/widgets/dropdown_link.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_participate.html, apps/dashboard/templates/meinberlin_dashboard/project_moderators.html, apps/documents/templates/meinberlin_documents/document_detail.html, apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, apps/kiezkasse/templates/meinberlin_kiezkasse/includes/proposal_list_item.html, apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_list_item.html, apps/polls/assets/ChoiceForm.jsx, apps/projects/templates/meinberlin_projects/includes/phase_indicator.html, apps/topicprio/templates/meinberlin_topicprio/includes/topic_list_item.html, apps/topicprio/templates/meinberlin_topicprio/topic_detail.html, meinberlin/static/embed.js, meinberlin/templates/a4images/image_upload_widget.html
=> use more consistent title/aria-label

apps/polls/assets/Question.jsx, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_mixins.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_poll.scss, meinberlin/assets/scss/components/_radio.scss
Fixes remarks mentioned in https://tree.taiga.io/project/ggr-meinberlinteam/task/969.
=> poll detail fixup

apps/bplan/serializers.py, tests/bplan/test_bplan_api.py
=> Validate bplan image downloaded in API serializer

apps/notifications/signals.py
=> Remove autofollow function for organisation initiators

apps/embed/middleware.py
=> encode x-ajax-path header

apps/dashboard/templates/meinberlin_dashboard/project_list.html, apps/projects/templates/meinberlin_projects/project_list.html
fixes #464
I also changed the dashboard project list fallback text since I think "No projects created" is not applicable when there's a filter on.
=> project list fallback texts

apps/budgeting/migrations/0009_remove_feedback_phase.py, apps/budgeting/phases.py, apps/dashboard/blueprints.py, locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po
This also removes every existing feedback phase from the database
ToDo:
=> Remove feedback phase from budgeting

locale/de/LC_MESSAGES/django.po
=> Fix translation

apps/projects/views.py
=> sort filters

meinberlin/assets/scss/components/_footer.scss
=> grey background below footer

apps/users/templates/meinberlin_users/user_detail.html, apps/users/views.py
=> rm participated projects from user profile

apps/cms/templates/meinberlin_cms/blocks/projects_block.html, apps/cms/templates/meinberlin_cms/home_page.html, apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, apps/dashboard/templates/meinberlin_dashboard/bplan_project_create_form.html, apps/dashboard/templates/meinberlin_dashboard/bplan_project_update_form.html, apps/dashboard/templates/meinberlin_dashboard/external_project_create_form.html, apps/dashboard/templates/meinberlin_dashboard/external_project_update_form.html, apps/dashboard/templates/meinberlin_dashboard/project_create_form.html, apps/dashboard/templates/meinberlin_dashboard/project_update_form.html, apps/polls/templates/meinberlin_polls/poll_management_form.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_confirm_delete.html, meinberlin/assets/scss/components/_hero_unit.scss
=> improve heading structure

apps/actions/templates/meinberlin_actions/blocks/platform_activity_block.html
fixes merge between #529 and #534
=> adapt platform activities block heading

meinberlin/settings/dev.py, meinberlin/settings/production.py
Easier for integration with salt deployment
=> Allow additional apps to be a list

apps/actions/templates/meinberlin_actions/blocks/platform_activity_block.html, locale/de/LC_MESSAGES/django.po, meinberlin/assets/scss/components/_action.scss
it may be necessary to define `get_absolute_url()` on some more models
=> link to object in action

apps/actions/models.py, apps/actions/templates/meinberlin_actions/blocks/platform_activity_block.html, locale/de/LC_MESSAGES/django.po
note that some of these actions do not exist yet
=> update action icons/formulations

apps/polls/rules.py, apps/topicprio/rules.py
=> Prevent access to items before the project has started

apps/contrib/emails.py
Depends on liqd/adhocracy4#106
=> Adapt Email translation to a4 core changes

apps/actions/templates/meinberlin_actions/blocks/platform_activity_block.html
this change was requested by @damusp:
> This looks rather odd. Also, the quote is too short to ever get any meaning from it.
=> rm truncated comment from activity stream

apps/servicekonto/templates/meinberlin_servicekonto/login.html, meinberlin/templates/account/base.html, meinberlin/templates/account/login.html, meinberlin/templates/socialaccount/connections.html
see https://github.com/liqd/a4-meinberlin/pull/410
=> fix account titles

locale/de/LC_MESSAGES/django.po
=> translate "remove" as "entfernen"

apps/budgeting/templates/meinberlin_budgeting/includes/proposal_list_item.html, apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, apps/cms/templates/meinberlin_cms/blocks/projects_block.html, apps/contrib/templatetags/contrib_tags.py, apps/dashboard/templates/meinberlin_dashboard/blueprint_list.html, apps/dashboard/templates/meinberlin_dashboard/includes/blueprint_list_tile.html, apps/dashboard/templates/meinberlin_dashboard/includes/external_project_list_item.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_list_item.html, apps/dashboard/templates/meinberlin_dashboard/project_list.html, apps/ideas/templates/meinberlin_ideas/idea_list.html, apps/ideas/templates/meinberlin_ideas/includes/idea_list_item.html, apps/kiezkasse/templates/meinberlin_kiezkasse/includes/proposal_list_item.html, apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_list_item.html, apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, apps/projects/templates/meinberlin_projects/project_list.html, apps/topicprio/templates/meinberlin_topicprio/includes/topic_list_item.html, apps/topicprio/templates/meinberlin_topicprio/includes/topic_mgmt_list_item.html, apps/topicprio/templates/meinberlin_topicprio/topic_list.html, apps/topicprio/templates/meinberlin_topicprio/topic_mgmt_list.html, meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/utility.scss
=> use structural list HTML elements

apps/projects/templates/meinberlin_projects/project_detail.html
this breaks some ARIA relations (aria-labelledby)
=> rm leading # from ids

meinberlin/assets/scss/utility.scss, meinberlin/templates/account/login.html
fixes #548
@damusp what do you think?
=> Re-Style login form

apps/documents/assets/ChapterNav.jsx, apps/documents/assets/ChapterNavItem.jsx, apps/documents/assets/DocumentManagement.jsx, meinberlin/assets/scss/components/_commenting.scss
=> Mark the currently edited Chapter in the TOC

apps/documents/assets/DocumentManagement.jsx, apps/polls/assets/ChoiceForm.jsx, apps/polls/assets/PollManagement.jsx, apps/polls/assets/QuestionForm.jsx
If the value label is undefined (calling `getNewChoice()` without a parameter) the input field is initially uncontrolled.
For controlled components see:
https://facebook.github.io/react/docs/forms.html#controlled-components
=> Use controlled components

apps/documents/admin.py, apps/offlineevents/admin.py, apps/polls/admin.py
=> Make creators readonly in django admin

apps/dashboard/forms.py, apps/dashboard/templates/meinberlin_dashboard/includes/external_project_form.html, apps/dashboard/templates/meinberlin_dashboard/includes/project_form_tab_info.html, apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, meinberlin/settings/base.py
Depends on: https://github.com/liqd/adhocracy4/pull/118
=> Use project tile image

tests/ideas/rules/test_rules_add.py, tests/ideas/rules/test_rules_change.py, tests/ideas/rules/test_rules_comment.py, tests/ideas/rules/test_rules_rate.py, tests/ideas/rules/test_rules_view.py
Depends on:
https://github.com/liqd/adhocracy4/pull/116
=> Fix rules tests

apps/users/decorators.py, meinberlin/settings/base.py, meinberlin/urls.py, tests/users/test_decorators.py
- fixup for django-ckeditor update
- restrict upload permissions
=> Ckeditor upload permissions

apps/mapideas/views.py
MapIdeas have not ModeratorFeedback
=> Fix MapIdea export

meinberlin/assets/scss/_base.scss
=> change button font

apps/actions/templates/meinberlin_actions/blocks/platform_activity_block.html, locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, package.json
=> remove profile link from activity stream

apps/documents/assets/ChapterForm.jsx, apps/documents/assets/DocumentManagement.jsx
see #587
The solution looks a bit hacky to me, but it is directly taken from official docs: https://facebook.github.io/react/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components
=> jumping to the chapter title on edit

apps/bplan/migrations/0004_add_verbose_name.py, apps/bplan/models.py, apps/dashboard/forms.py, apps/offlineevents/forms.py, locale/de/LC_MESSAGES/django.po
=> fix some i18n issues

apps/contrib/widgets.py
=> prevent doubly id's from datetimepicker

apps/contrib/views.py, apps/dashboard/mixins.py, apps/dashboard/templates/meinberlin_dashboard/includes/project_list_item.html, apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_confirm_delete.html, apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_create_form.html, apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_list.html, apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_update_form.html, apps/offlineevents/urls.py, apps/offlineevents/views.py
offline events had been forgotten to be adapted to the ProjectContextDispatcher due to parallel mergings.
=> Adapt offlineevents to ProjectContextDispatcher

apps/projects/templates/meinberlin_projects/includes/phase_indicator.html, meinberlin/assets/scss/components/_phases.scss
We git the feedback that with the current design users do neither understand that the timeline is a timeline nor that the entries can be clicked. This new design is supposed to improve that.
Note that the conditions for `is-active` and `is-selected` do not yet work as intended.
=> change timeline styling

meinberlin/assets/scss/components/_tile.scss
=> Improve style of tile images

meinberlin/apps/dashboard/templates/meinberlin_dashboard/includes/removeable_user_list.html, meinberlin/apps/users/fields.py
=> improve validity of HTML

meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html
see https://github.com/liqd/a4-meinberlin/pull/646#discussion_r129511859
=> Fixup 019aac2: Also add selected page text to module case

docs/bplan_api.md
just some typos and inconsistencies
Generally I think this is well written documentation that should be easy to understand.
=> tweak bplan API docs

meinberlin/apps/polls/assets/Question.jsx, meinberlin/assets/scss/components/_poll.scss
=> pollbar animation

meinberlin/apps/cms/emails.py
=> Send wagtail form mails synchronously

meinberlin/apps/bplan/views.py, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/budgeting/views.py, meinberlin/apps/contrib/filters.py, meinberlin/apps/documents/views.py, meinberlin/apps/extprojects/views.py, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_list.html, meinberlin/apps/ideas/views.py, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, meinberlin/apps/kiezkasse/views.py, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/mapideas/views.py, meinberlin/apps/polls/templates/meinberlin_polls/poll_404.html, meinberlin/apps/polls/views.py, meinberlin/apps/topicprio/views.py
I trivially replaced `project.last_active_module`. All these changes look very reasonable to me. I did not do extensive testing though. (Mostly because I expect further changes and I think testing bigger chunks is less work).
=> [multimod] rm last_active_module

meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html
Note that the project short description will be re-introduced to the UI in a later pull request.
=> [multimod] adapt timeline

meinberlin/apps/cms/emails.py, meinberlin/apps/cms/models.py
=> Send wagtail form email asynchronously

meinberlin/apps/dashboard2/apps.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_list.html, meinberlin/apps/dashboard2/urls.py, meinberlin/apps/dashboard2/views.py, meinberlin/config/settings/base.py, meinberlin/config/urls.py
This just adds the new app and copies the initial view (project-list) and templates.
=> dashboard2

meinberlin/apps/dashboard2/blueprints.py, meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/mixins.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/blueprint_list.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/blueprint_list_tile.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_create_form.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_list.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_update_form.html, meinberlin/apps/dashboard2/urls.py, meinberlin/apps/dashboard2/views.py
A project is created with basic information (name, desc, img).
Afterwards it may be edited from the advanced dashboard2.0.
This commit introduces the basic create form and a simple edit form.
Futhermore it introduces a4dashboard namespaced urls.
=> Add basic create project form

meinberlin/assets/scss/components/_tabs.scss
This new styling will be used in both the dashboard and project detail.
I am not yet sure about the exact states and mobile styling, so considers this incomplete.
=> change tab styling

meinberlin/apps/account/templates/meinberlin_account/account_dashboard.html, meinberlin/apps/dashboard/templates/meinberlin_dashboard/base_dashboard.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard.html, meinberlin/assets/scss/components/_dashboard_nav.scss
This changes the styling of the dashboard navigation towards. Note that the current contents of that navigation will be moved to tabs in a different pull request. This component will then be used to break the monolithic project editing into several views. But all that will be done later. For now I only updated the styling.
=> change dashboard-nav styling

meinberlin/apps/dashboard2/__init__.py, meinberlin/apps/dashboard2/apps.py, meinberlin/apps/dashboard2/components.py, meinberlin/apps/dashboard2/contents.py, meinberlin/apps/dashboard2/dashboard.py, meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard_project.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_form_project.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_basic_form.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_information_form.html, meinberlin/apps/dashboard2/urls.py, meinberlin/apps/dashboard2/views.py
The registry is named "contents" for the sake of consistency with phases (and modules)
=> Add basic component registry and dispatcher

meinberlin/apps/dashboard2/__init__.py, meinberlin/apps/dashboard2/components.py, meinberlin/apps/dashboard2/contents.py, meinberlin/apps/dashboard2/dashboard.py, meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/mixins.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard_project.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_form_module.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/module_basic_form.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/module_phases_form.html, meinberlin/apps/dashboard2/urls.py, meinberlin/apps/dashboard2/views.py
Fixes notes from PR #692 
Missing:
=> Add ModuleComponentDispatcher

meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_list.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_item_detail.scss, meinberlin/assets/scss/components/_project_header.scss, meinberlin/assets/scss/components/_tabs.scss
this pull request changes some layout and styling. It also brings back the project short description.
=> change project detail styling

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard_project.html, meinberlin/assets/scss/components/_button.scss, meinberlin/templates/meinberlin_dashboard2/base_dashboard.html
I am not totally convinced of this styling. The reduced font size is strange since this is basically the heading for the page. But I guess we can live with it for now.
=> Cleanup dashboard tab styling

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_form_module.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_form_project.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_create_form.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_update_form.html, meinberlin/assets/scss/utility.scss
There may be more instances where this is helpful. We can adapt them one by one.
=> align first headings to top

meinberlin/apps/dashboard/mixins.py
Fixes the issue with error if a project with a module with settings was duplicated
=> Duplicate module settings if present

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_create_form.html
=> fix project create view

meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_label.scss, meinberlin/assets/scss/components/_tile.scss
=> further improve print styling

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_create_form.html, meinberlin/apps/dashboard2/views.py
- Create module settings on project create
- Redirect to bleuprint list on cancel
=> Create project fixes

meinberlin/templates/a4images/image_upload_widget.html
follow-up to https://github.com/liqd/adhocracy4/pull/168
=> improve image upload

meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/views.py
=> Dashboard2 fixes

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/blueprint_list.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_list.html, meinberlin/apps/dashboard2/views.py, meinberlin/assets/scss/components/_dashboard_nav.scss
This merely adds a nav to the project list in dashboard. We could still do the same for blueprint list and highlight the currently active one (which doesn't work for blueprint list because it's a button now).
=> add nav to project list

meinberlin/apps/dashboard/templates/meinberlin_dashboard/includes/project_list_item.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html
fixes parts of #515 
most was already done for the new dashboard anyway.
=> 2017 08 pv headings

meinberlin/apps/maps/templates/meinberlin_maps/map_choose_polygon_with_preset_widget.html
=> remove invalid rows attr

meinberlin/apps/dashboard2/mixins.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html, meinberlin/apps/dashboard2/views.py, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_list_item.scss
Copied publicate button and mixin to dashboard2.
Also fixes #733 
CSS of dropdown menu is broken.
=> Dashboard2 duplicate

meinberlin/apps/documents/views.py
Looks ugly. But is excel :see_no_evil:
=> Add document with comments export

meinberlin/assets/scss/components/_select-item.scss, meinberlin/assets/scss/style.scss
depends on https://github.com/liqd/adhocracy4/pull/164 but merging won't break anything.
=> style select item

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_form_module.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_form_project.html
This improves dashboard2 document titles. It closes #517.
=> improve dashboard doc titles

meinberlin/templates/a4images/image_upload_widget.html
=> fallback tiny image for image upload without picture

meinberlin/apps/documents/assets/ChapterNav.jsx, meinberlin/apps/documents/assets/ChapterNavItem.jsx, meinberlin/assets/scss/components/_document.scss
=> text review issues

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/project_create_form.html
My proposal for #769
closes #769
=> add text for create project ux

meinberlin/apps/exports/dashboard.py
required for accessibility: http://testen.bitv-test.de/index.php?a=di&iid=94
=> announce file type to user

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html, meinberlin/assets/scss/components/_list_item.scss
I refactored the new features introduces in #735. The focus was in responsivness.
=> refactor list-item--has-image

meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/base_dashboard_project.html
it was strange that there was no way to go to the project, especially directly after publishing.
=> preview link in project edit

meinberlin/apps/actions/templates/meinberlin_actions/includes/action.html
Also fixes #648. Note that the bug only occured after 12:00
=> fix action time format

meinberlin/apps/actions/templates/meinberlin_actions/includes/action.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html, meinberlin/templates/a4filters/widgets/free_text_filter.html
=> rm role="presentation" from forms

meinberlin/apps/contrib/templates/meinberlin_contrib/includes/filter_and_sort.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/progress.html, meinberlin/apps/polls/assets/ChoiceForm.jsx, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_list_tile.html, meinberlin/templates/base.html
these are some accessibility improvements I found when testing with orca and voice over.
=> a11y improvements

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/contrib/static/js/ajax_modal.js, meinberlin/apps/maptopicprio/phases.py, meinberlin/apps/polls/dashboard.py
Translation for "maptopicprio" is still missing:
```
msgid "Filter bar "
msgstr ""
msgid "Place Prioritization"
msgstr ""
msgid "Comment and prioritize places located on a map."
msgstr ""
msgid "Places"
msgstr ""
msgid "Locate the place on a map"
msgstr ""
msgid "Place label"
msgstr ""
msgid "Prioritize and comment places located on a map."
msgstr ""
msgid "place prioritization"
msgstr ""
msgid "Confirm Place Deletion"
msgstr ""
msgid "Are you sure you want to delete the place?"
msgstr ""
msgid "Add a new place"
msgstr ""
msgid "Add Place"
msgstr ""
msgid "Edit place"
msgstr ""
msgid "Places with comments"
msgstr ""
msgid "The place has been deleted"
msgstr ""
```
=> Add translation

locale/de/LC_MESSAGES/django.po
- Fixes
- maptopic prio translations
=> Translations

meinberlin/apps/embed/templates/meinberlin_embed/embed.html
fixes #818
the same was added to base.html in 6ed1f4c87
=> add language attribute to embed.html

meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/components/_hero_unit.scss, meinberlin/assets/scss/components/_project_header.scss
We have had a second breakpoint for a while now, but only used it in few cases. This uses this second breakpoint to do some optimisations for medium sized screen (and potentially embeds).
=> use second breakpoint

package.json
exactly the same as the old one, but under our control
=> use our fork of datepicker

meinberlin/assets/scss/components/_hero_unit.scss
fixes #790
see https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview
=> work around layout bug in IE

meinberlin/config/settings/base.py
=> set ckeditor title

meinberlin/apps/documents/assets/ChapterForm.jsx, meinberlin/apps/documents/assets/DocumentManagement.jsx, meinberlin/apps/documents/assets/ParagraphForm.jsx, meinberlin/apps/polls/assets/ChoiceForm.jsx, meinberlin/apps/polls/assets/PollManagement.jsx, meinberlin/apps/polls/assets/QuestionForm.jsx
=> Focus on input elements in react

locale/de/LC_MESSAGES/django.po, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/module_categories_form.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_list.html
=> add description to offlineevent and category components

locale/de/LC_MESSAGES/djangojs.po
fixes #832
depends on https://github.com/liqd/adhocracy4/pull/189
=> translate follow button

meinberlin/apps/documents/templatetags/react_documents.py, meinberlin/apps/documents/views.py, tests/documents/test_document_views.py
Fixes documents in general and #537
=> Redirect first chapter to project detail

meinberlin/apps/documents/assets/ChapterForm.jsx, meinberlin/apps/documents/assets/ChapterNav.jsx, meinberlin/apps/documents/assets/ChapterNavItem.jsx, meinberlin/apps/documents/assets/DocumentManagement.jsx, meinberlin/apps/documents/assets/ParagraphForm.jsx, meinberlin/apps/polls/assets/ChoiceForm.jsx, meinberlin/apps/polls/assets/PollManagement.jsx, meinberlin/apps/polls/assets/QuestionForm.jsx
=> Use react stateless components for poll forms

meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_create_form.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_dashboard_list.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_list.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_update_form.html
=> Fix topicprio dashboard templates

meinberlin/apps/bplan/management/commands/bplan_auto_archive.py, meinberlin/apps/bplan/phases.py, meinberlin/apps/bplan/rules.py, meinberlin/apps/bplan/templates/meinberlin_bplan/bplan_finished.html, meinberlin/apps/bplan/urls.py, meinberlin/apps/bplan/views.py, meinberlin/apps/projects/views.py, tests/bplan/rules/test_rules_add_statement.py
Show information text when the bplan project is over
=> Bplan archiving

meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_list_item.html, meinberlin/templates/meinberlin_dashboard2/includes/project_list_item.html
=> skip background url if empty

meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_hero_unit.scss
This styling is optimized for a mostly white background image. See a draft on https://meinberlin-stage.liqd.net/
=> change hero unit styling

meinberlin/apps/dashboard/__init__.py, meinberlin/apps/projectcontainers/dashboard.py, meinberlin/apps/projectcontainers/forms.py
I am not totally sure if the ContainerInformationComponent works correctly like this.
=> overwrite form wording for containers

meinberlin/assets/scss/components/_datepicker.scss
=> bump specificity

meinberlin/apps/dashboard2/forms.py, meinberlin/apps/dashboard2/templates/meinberlin_dashboard2/includes/project_basic_form.html
fixes #868
copied from https://github.com/liqd/a4-opin/pull/874
=> use radio buttons for private/public setting

meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html
if participation is not possible
fixes #905
=> show datetime instead of date in timeline

meinberlin/apps/ideas/views.py, meinberlin/apps/maptopicprio/views.py, meinberlin/apps/topicprio/views.py
Fixes #917
Partly a quick fix, as the permission object is going to be changed to project in the dashboard mixin.
=> Fix topic/place dashboard permissions

meinberlin/apps/maps/static/meinberlin_maps/map_choose_polygon_with_preset.js
this is required to trigger the unload warning. Fixes #918
=> trigger change event when changing a polygon

meinberlin/templates/a4forms/datetime_input.html
=> overwrite datetime template

meinberlin/apps/cms/templates/meinberlin_cms/blocks/projects_block.html
Fixes #235
A cleaner fix would be in the block directly, but fixing template was simpler.
=> Filter deleted, archived and private projects from wagtail block

meinberlin/apps/documents/admin.py, meinberlin/apps/maps/admin.py, meinberlin/apps/newsletters/admin.py, meinberlin/apps/offlineevents/admin.py, meinberlin/apps/polls/admin.py
Depends on: https://github.com/liqd/adhocracy4/pull/203
=> Use core project filter in django-admin

meinberlin/templates/portal_header.html
I fetched the upstream portal header and this is the only thing that had changed.
=> use https for partal links

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_over_soon.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_over_soon.en.email, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html
- in the phase information in the timeline
- in the project ending soon notification
Fixes #959
=> Show participation end time

meinberlin/apps/maptopicprio/models.py
Point needs to be defined after item_ptr, as its pk is required by the json
field to convert the string to json.
=> Fix maptopicprio field order

meinberlin/apps/polls/assets/QuestionForm.jsx
see https://github.com/liqd/a4-meinberlin/pull/966#issuecomment-342183615
@fuzzylogic2000 what do you think?
=> change wording of multiple choice checkbox

tests/factories.py
=> Make testuser username unique

meinberlin/assets/scss/components/_radio.scss
=> style disabled radio buttons

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
Reverts https://github.com/liqd/a4-meinberlin/pull/756
... as is breaks offline-event navigation.
=> Always activate participation tab first

meinberlin/apps/polls/api.py, meinberlin/apps/polls/assets/Question.jsx, meinberlin/apps/polls/models.py, meinberlin/apps/polls/serializers.py, meinberlin/apps/polls/templates/meinberlin_polls/poll_detail.html, meinberlin/apps/polls/templatetags/react_polls.py, meinberlin/apps/polls/views.py
the counting does not yet work
=> add multiple polling to api and ui

meinberlin/assets/js/app.js
This reverts commit 349d3012642701a72007cddbab8d218f465b2aa4.
see https://github.com/liqd/adhocracy4/pull/207
=> Revert "revert core adaption"

meinberlin/assets/js/plans_map.jsx, package.json, webpack.config.js
The clusters are basically working.
If many clusters are on the same place, the may be spiderfied onclick when the highest zoom level is selected.
=> Enable clustering on plans

meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/includes/offlineevent_list_item.html
similar things have already been done in https://github.com/liqd/a4-meinberlin/pull/973
=> make dashboard offlineevent list items consistent with dashboard project list items

meinberlin/apps/notifications/emails.py, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_initiators_project_created.de.email
=> Fix project context for other project types in initiator notifications

meinberlin/test/factories/__init__.py
=> Generate unique emails for tests

meinberlin/apps/adminlog/dashboard.py
Fixes https://github.com/liqd/a4-meinberlin/issues/1012
=> Fix adminlog component highlighting 

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/plans/views.py, meinberlin/assets/js/plans_map.jsx, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/components/_map.scss, meinberlin/assets/scss/utility.scss
extend UI based on the new fields available from #1010
=> Plans detail view

meinberlin/apps/maps/static/meinberlin_maps/map_choose_polygon_with_preset.js
=> disable circlemarker in leaflet draw

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
I know this is a lot of HTML. This is simply how we do edit links in the
item-detail UI.
I am not completely sure which permission needs to be checked here.
=> add edit link to plan detail

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/polls/assets/Question.jsx
The design says to write 'Stimme ändern' if user already voted.
I also refactored the footer generation a bit and hope to make it more readable?!
=> add 'change vote' on poll if user already voted

meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_list_item.scss
~~Styling still missing~~
UI can still be improved, but I propose to do that separately:
=> add plan filters

meinberlin/apps/users/fields.py
Extract emails of the form `<foo@bar.org>`
Fixes https://github.com/liqd/a4-meinberlin/issues/1026
=> Extend email regex

meinberlin/apps/documents/exports.py, meinberlin/apps/exports/views.py, meinberlin/apps/plans/urls.py, meinberlin/apps/plans/views.py
currently there is no button in the ui to export. 
for testing navigate  to `/vorhaben/export/format/xslx/` 
exports are available for every user that may view the vorhaben list: which is currently everyone
=> Plans export

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/dashboard/blueprints.py
Fixes https://github.com/liqd/a4-meinberlin/issues/1027
=> Fix agenda setting blueprint description

package.json
=> fix(package): update copy-webpack-plugin to version 4.2.3

meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_map.scss
I am not super happy with the implementation because their many little unlovely details:
- the dropdown functionality comes from bootstrap which in turn uses jquery. It seems to work fine inside of the react component, but that's far from nice.
- I did some subtle CSS changes that might have an impact somewhere else.
- `.select-item` uses a bigger font size which makes #1040 even worse.
=> add status icon legend

meinberlin/apps/plans/assets/plans_map.jsx
`<select>`s are not styled correctly.
=> Replace participation <select> filter by dropdown

meinberlin/apps/users/fields.py
As it is difficult to guess the correct encoding of a
file, email addresses are restricted to contain only ascii
letters.
This works for every encoding which is a superset of
ascii like utf-8 and latin-1. Non ascii chars are simply ignored.
=> Import emails from files only if ascii encoded

locale/de/LC_MESSAGES/django.po
see also https://github.com/liqd/a4-product/pull/139
=> de translation adjustments

meinberlin/apps/bplan/serializers.py, requirements/base.txt
- limit downlaod size
- add file extension, if missing
Fixes: https://github.com/liqd/a4-meinberlin/issues/1022
=> Enhance bplan tile image download

locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_notification.de.email, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/submitter_confirmation.de.email, meinberlin/apps/initiators/templates/meinberlin_initiators/emails/initiator_request.de.email, meinberlin/apps/initiators/templates/meinberlin_initiators/emails/initiator_request.en.email, meinberlin/apps/newsletters/templates/meinberlin_newsletters/emails/newsletter_email.de.email, meinberlin/apps/newsletters/templates/meinberlin_newsletters/emails/newsletter_email.en.email, meinberlin/apps/notifications/management/commands/send_test_emails.py, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_new_item.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_new_item.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_over_soon.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_over_soon.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.en.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_moderator.de.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_moderator.en.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_participant.de.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_participant.en.email, meinberlin/templates/a4reports/emails/report_creator.de.email, meinberlin/templates/a4reports/emails/report_moderators.de.email, meinberlin/templates/account/email/email_confirmation.de.email, meinberlin/templates/account/email/email_confirmation.en.email, meinberlin/templates/account/email/email_confirmation_signup.de.email, meinberlin/templates/account/email/email_confirmation_signup.en.email, meinberlin/templates/account/email/password_reset_key.de.email, meinberlin/templates/account/email/password_reset_key.en.email, meinberlin/templates/email_base.html, meinberlin/templates/email_base.txt
@hmkay we could fix the emails in the course of this PR
=> Fix some email wordings

package.json
=> fix(package): update webpack to version 3.9.1

meinberlin/apps/notifications/management/commands/send_test_emails.py, meinberlin/apps/users/adapters.py
depends on liqd/adhocracy4#211
=> Adapt to SyncEmailMixin changes

meinberlin/apps/users/adapters.py, meinberlin/templates/account/email_confirm.html
The changes are from AE and add the next parameter to the confirmation link in the email.
=> redirect on registration

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_datepicker.scss, meinberlin/assets/scss/components/_docs_block.scss, meinberlin/assets/scss/components/_project_header.scss, meinberlin/assets/scss/components/_radio.scss
some small UI fixes i found while working on https://github.com/liqd/a4-product/pull/149
=> small UI fixes

meinberlin/apps/contrib/staticfiles.py, meinberlin/apps/contrib/widgets.py, meinberlin/apps/maps/widgets.py, meinberlin/config/settings/build.py, meinberlin/config/settings/production.py
fixes #948 
Is like https://github.com/liqd/a4-opin/pull/1008, but we should try it either here in meinberlin or in opin first to see if it works.
Still has to be done to really make it work: the build-settings.
=> 2017 12 ka redo cache busting

meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/assets/scss/components/_doc_toc.scss, meinberlin/assets/scss/components/_document.scss, meinberlin/assets/scss/style.scss
facilitates styling in a4-product
=> refactor document styling

meinberlin/apps/plans/assets/plans_map.jsx
also filter for organisation name and category
=> extend plans freetext filter

meinberlin/apps/plans/views.py
Note that the sorting can currently not be done in sql due to https://github.com/liqd/adhocracy4/issues/218
=> sort list items by last modified date

meinberlin/apps/polls/assets/Question.jsx
depends on https://github.com/liqd/adhocracy4/pull/220
=> use getLoginUrl from adhocracy4

package.json
=> fix(package): update shariff to version 2.1.1

meinberlin/apps/users/admin.py
Makes it easier to find users from raw_id field
=> display id of user in django admin and add id to searchfields

meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/components/_comments.scss
While working on this the comment styling was refactored a little to
keep it in one place as was discussed with @fuzzylogic2000
=> Style comment answer button

meinberlin/apps/plans/models.py
=> don't allow 'Berlin' as option in district FK field of plan

package.json
=> fix(package): update leaflet-draw to version 1.0.2

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/assets/scss/components/_item_detail.scss, meinberlin/assets/scss/components/_timeline.scss
Meta gets has same font-size as label, as discussed with @CarolingerSeilchenspringer and Sandy.
=> smaller font-size for item detail meta

.polylintrc, meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html, meinberlin/apps/plans/views.py
also adds the district and a link to the project to the export
=> Add export button to vorhaben list 

meinberlin/assets/scss/components/_dropdown.scss
fixes https://github.com/liqd/a4-product/issues/321
=> fix bet.in user dropdown

package.json
=> fix(package): update postcss-loader to version 2.1.3

package.json
=> chore(package): update markdownlint-cli to version 0.8.1

.travis.yml
Reverts liqd/a4-meinberlin#1294
=> Revert "use npm build from old webpack target"

meinberlin/apps/activities/templates/meinberlin_activities/activity_detail.html, meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/assets/scss/components/_accordion.scss, meinberlin/assets/scss/components/_module.scss
=> Pm 2018 05 style activties detail

locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/apps/plans/views.py, meinberlin/assets/scss/components/_list_item.scss
the retrieval of the status string in the view feels a bit clumsy, maybe there is a more elegant way to do that?
=> Mn 2018 05 update plans list

meinberlin/assets/scss/components/_map.scss
=> Added ellipsis for maps pop up

meinberlin/apps/documents/exports.py, meinberlin/apps/exports/mixins.py
Manual tests still done by me (irae)
The following comments get into the csv:
=> Rewrite document export to new specification

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/assets/scss/components/_hero_unit.scss
I have done an indent check, hope its ok! The following components I have not added:
category-formset__form - Cannot locate a use of it
simple_page - Cannot locate a use of it
select2 -Only referenced in js files
lr_bar - Only referenced in import doc
select_dropdown - Only referenced in import doc
map - javascript
=> addition of rest of components, added one tag to hero

locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/documents/exports.py
Ok, just translating a few fields proved to be a bit more difficult than initially expected...
=> Ka 2018 06 make document export translatable

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/assets/scss/components/_item_detail_2.scss
added class and styled in components to match styling from idea image
=> adding image tag and formatting

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
separate dropdown and lr-bar__right classes into 2 divs due to styling on lr-bar__right
=> dropdown fix

meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html, meinberlin/assets/scss/components/_list_item.scss
change background colour to lighter gray
=> Pm 2018 06 list item fixes#1463

meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html
=> Pm 2018 06 ie11 moderator button fixes#1456

meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html
fixes #1456 
i pulled master onto branch and redid changes and made new commit and pull request, hopefully that should work?
=> adding span to stop button collaps fixes#1456

meinberlin/apps/budgeting/dashboard.py, meinberlin/apps/budgeting/exports.py, meinberlin/apps/budgeting/models.py, meinberlin/apps/budgeting/views.py, meinberlin/apps/exports/templates/meinberlin_exports/export_dashboard.html, meinberlin/apps/exports/views.py, meinberlin/apps/ideas/exports.py, meinberlin/apps/ideas/models.py, meinberlin/apps/kiezkasse/exports.py, meinberlin/apps/kiezkasse/models.py, meinberlin/apps/mapideas/exports.py, meinberlin/apps/mapideas/models.py, meinberlin/apps/maptopicprio/exports.py, meinberlin/apps/maptopicprio/models.py, meinberlin/apps/polls/dashboard.py, meinberlin/apps/polls/exports.py, meinberlin/apps/polls/views.py, meinberlin/apps/topicprio/exports.py, meinberlin/apps/topicprio/models.py, meinberlin/assets/scss/components/_export_dashboard.scss, meinberlin/assets/scss/style.scss
initial structure in place, needs text updating and possibly changes if the amount of texts decreases.
Are we happy with using strong tag? its's the easiest way to style differently within table cell that I know of.
=> Pm 2018 07 style export dashboard page

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/exports/templates/meinberlin_exports/export_dashboard.html
This updates the wording for the export, deals with the a11y-thing for the export and adds translations for the export, the reporting and the project contact (the last might still have strings to change in the dashboard)
=> Ka 2018 07 wording export

meinberlin/apps/moderatorremark/assets/idea_remarks.js
I didn't yet test if it actually breaks moderator remarks. Where to test it?
=> fix TypeError: t is undefined. Fixes #1519

meinberlin/config/settings/base.py, meinberlin/config/whitenoise.py
Reverts liqd/a4-meinberlin#1522
=> Revert "reorder middlewares and use whitenoise middleware instead of its own wsgi"

meinberlin/apps/contrib/sitemaps/adhocracy4_sitemap.py, meinberlin/config/urls.py, meinberlin/templates/robots.txt
Add a simple robots.txt. Can be overwritten by salt.
Edit: hm, seems like urls.py needs to get fixed....
=> add robots.txt

locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/contrib/django_standard_messages.py
=> Mn 2018 09 fix translations again

meinberlin/templates/a4filters/widgets/dropdown_link.html
fixes #1535 fixes #1345
class names are already on child div, checked all dropdowns I could think of and didn't effect their placement 
Not sure why checks failed?
=> removing un-needed class name to fix button

meinberlin/apps/projects/templates/meinberlin_projects/participantinvite_detail.html
=> add next parameter to reegister url

meinberlin/apps/plans/templates/meinberlin_plans/project_plans_form.html, meinberlin/assets/scss/_form.scss
=> display only error for field

meinberlin/apps/projects/admin.py, meinberlin/config/settings/base.py, package.json, requirements/base.txt
depends on https://github.com/liqd/adhocracy4/pull/286/files
=> Ka 2018 10 add location and topic to projects

meinberlin/assets/scss/components/_comments.scss
=> tiny issue fix to stop word overflow on comments 

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
=> Pm 2018 10 vorhaben detail table

meinberlin/templates/newsletter_base.html
this pull request might fix #1637 but as I am not sure how to test, i'm not sure it does? any suggestions?
=> changing max height to max width

meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/apps/plans/views.py
I removed the filter by zoom functionality, also when I click a list item, no marker is shown and in the other way around the list does not scroll to the item in the list when a marker is clicked. I added a popup for the case that the marker is clicked.
=> Mn 2018 11 fix map

meinberlin/config/settings/dev.py
Update dev logging again to make it more expressive
=> dev: show more logging output by default

meinberlin/apps/polls/validators.py
https://stackoverflow.com/questions/306313/is-operator-behaves-unexpectedly-with-integers
=> compare integers by value not reference

meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/assets/scss/components/_storefront.scss, meinberlin/assets/scss/utility.scss
little adjustments made for full screen size
=> Pm 2018 12 storefront tidy

meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/assets/scss/components/_storefront.scss, meinberlin/assets/scss/utility.scss
I think I still don't fully understand flexbox but it's looking fine on mobile and tablet
=> Pm 2018 12 mobile storefront

meinberlin/apps/cms/models/storefronts.py
I wasn't quite sure which projects we said we wanted to count for the storefront anymore. So I counted the ones with active or future phases.
@CarolingerSeilchenspringer Do we also want to add the active plans to the count or did we decide that we didn't want to do that?
=> Ka 2018 12 project count

meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_tabs.scss, meinberlin/templates/header.html
=> Pm 2018 12 header chrome

meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_header.scss, meinberlin/templates/header.html
fixes #1718
Have not added translation for home
=> Pm 2018 12 mobile dropdowns

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/assets/scss/components/_map.scss, meinberlin/assets/scss/components/_switch.scss
need to look into ipad pro size, it's too big to be a tablet with our current breakpoints.
=> Pm 2018 12 map issues

meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/utility.scss, package.json
=> Ka 2018 12 update font awesome

meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_storefront.scss, meinberlin/assets/scss/utility.scss
=> use rem for breakpoints

meinberlin/apps/users/templates/meinberlin_users/indicator.html
=> add spaces between login and register on userindicator

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/views.py, meinberlin/config/settings/base.py
The first commit is the one actually adding the image and copyright, the second one is only a tiny little bit of rewriting. So, if you want to know what happened, read the first one. And if you need the image in another size or something else different, let me know!
=> Ka 2019 01 add images to project tiles

meinberlin/assets/js/app.js
=> social media sharing - shariff - disable g+ and change info link

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_status_bar.scss
i tried to comment on stuff that wasn't clear, if you have time to show me where it's not clear or badly organised when you go through it I would appriciate it! :)
=> Pm 2019 1 vertical listitems

meinberlin/apps/plans/assets/ListMapBox.jsx
=> always display list on mobile when filter is set

package.json
Reverts liqd/a4-meinberlin#1769
=> Revert "Update dependency leaflet to v1.4.0"

package.json
Reverts liqd/a4-meinberlin#1678
=> Revert "Update dependency webpack to v4.28.4"

meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html, meinberlin/apps/users/fields.py
quick issue fix after chat with Caro yesterday
=> fixes #1351

meinberlin/apps/cms/templates/meinberlin_cms/blocks/infographic_block.html, meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_dialogue_box.scss, meinberlin/assets/scss/components/_storefront.scss
=> Pm 2019 01 infographic whitespace

meinberlin/apps/plans/models.py, meinberlin/apps/plans/serializers.py, meinberlin/apps/plans/views.py
fixes #1806 
fixes #1805
@fuzzylogic2000 instead of using the property we could also migrate the tablename to administrative_district. What is better?
=> Mn 2019 01 refactor list

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/serializers.py
=> checking for projectcontainer attr to get project count for container tile

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx
changes two things:
1. when you select a filter the url in the browser changes (so that it can be copied or reloaded)
2. when you select a district the map zooms to the district
=> Mn 2019 01 some improvements on map

.eslintrc, meinberlin/apps/contrib/assets/Alert.jsx, meinberlin/apps/documents/assets/ChapterForm.jsx, meinberlin/apps/documents/assets/ParagraphForm.jsx, meinberlin/apps/plans/assets/MapListSwitch.jsx, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/polls/assets/ChoiceForm.jsx, meinberlin/apps/polls/assets/Question.jsx, meinberlin/apps/polls/assets/QuestionForm.jsx, meinberlin/assets/scss/components/_input_group.scss, meinberlin/assets/scss/components/_switch.scss, package.json
I found this https://github.com/evcohen/eslint-plugin-jsx-a11y in here http://simplyaccessible.com/article/react-a11y/ and thought it makes sense to add the jsx a11y linter. You can see that it does make sense when you try a make lint after the first commit (and a make install). There are two more erroring files, which I left out in the gardening for now.
I am not sure if and how we should also add this to our project(s). https://github.com/reactjs/react-a11y
=> Ka 2019 01 react a11y

meinberlin/assets/scss/components/_switch.scss
I think this is fixed now? 
i striped out a lot of unneeded code and positioned elements from the right as that doesn't change no matter the position of the label text, I think that was the problem (i hope)
=> position fix for map switch

meinberlin/apps/plans/assets/FilterRadio.jsx, meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/MapListSwitch.jsx, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_radio.scss, meinberlin/assets/scss/components/_switch.scss
still to do 
Anything smaller than 580px is a problem
=> add wrapping divs for structure and styling, add initial styling

meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/apps/plans/assets/FilterOptions.jsx, meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/ListMapBox.jsx
I think, I forgot to sort the organisations by name! It is currently working, but sorted by number of associated projects. I propose we still merge and fix that later?!
=> Ka 2019 01 organisation filter

meinberlin/apps/plans/assets/PlansList.jsx
=> increasing char count for testing purposes

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_map.scss, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_switch.scss
also partial fix for #1854
fixes #1852 (shared problems with above issue)
=> Pm 2019 01 issue fixes

meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/views.py, meinberlin/assets/scss/style.scss, package.json, webpack.common.js
First version of autocomplete for organisations. I was not sure where to add it. Maybe putting it besides the searchinput would look ok. Also I had to add twitter bootstrap form styles to the css because the library depends on it but I think it does not break anything.
=> Mn 2019 01 organisations typeahead

meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/assets/scss/components/_filter_bar.scss
…sizes
finishes fixes for following 
fixes #1854
fixes #1854
fixes #1851
=> Pm 2019 01 filter font size spacing

meinberlin/apps/plans/assets/MapTeaserBox.jsx
=> make no slected district -1 and not undefined

meinberlin/apps/cms/templates/meinberlin_cms/blocks/map_teaser_block.html, meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/assets/scss/components/_storefront.scss, meinberlin/assets/scss/utility.scss
fixes #1948 
fixes #1947 
fixes #1922
=> Ka 2018 02 landing page and storefront

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/contrib/django_standard_messages.py, meinberlin/apps/plans/serializers.py, meinberlin/apps/plans/templatetags/react_map_teaser.py, meinberlin/apps/plans/views.py, meinberlin/apps/projects/dashboard.py, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
fixes #1913 fixes #1929 fixes #1935 fixes 1938 fixes #1951
=> wording changes and translations

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/assets/scss/components/_maplist.scss
was there a reason we didn't want to do it like this? its seems to work but I feel it's a little messy but i'm not sure how else I would fix it
=> Pm 2019 02 clickable tile

meinberlin/apps/plans/serializers.py
fixes #1904 
Please also read the discussion in that issue and discuss with me and @CarolingerSeilchenspringer
=> Ka 2019 02 participation status

meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/assets/scss/components/_storefront.scss, meinberlin/assets/scss/utility.scss
=> making blue tile clickable to project overview

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/serializers.py, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/plans/views.py, meinberlin/apps/projectcontainers/models.py, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/includes/container_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, meinberlin/assets/scss/components/_item_detail_2.scss
mainly does story 1745 from the current sprint, but also 
fixes #1976 
fixes #1957 
fixes #1903
=> Ka 2019 02 use new project tiles in django templates

meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/Toggles.jsx, meinberlin/assets/scss/components/_switch.scss, meinberlin/assets/scss/components/_typeahead.scss
general filter pull request for following issues 
fixes #1921
fixes  #1909
partial fix for #1923 - still needs translation of new string
=> Pm 2019 02 secondary filter

meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/assets/scss/components/_map.scss
hopefully fixes #1891
fixes #1861
=> Pm 2019 02 mobile map

meinberlin/assets/js/app.js
=> link to our own shariff info page

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> Ka 2019 02 translations

meinberlin/apps/cms/templates/meinberlin_cms/blocks/docs_block.html, meinberlin/apps/cms/templates/meinberlin_cms/blocks/map_teaser_block.html, meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_blocks.scss
fixes  #1911 
Also removing l-center-8 from accordions as had issues on other parts of site
=> adding transaprent background behind text

meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_filter_bar.scss
between 1040 and 1078 it's not good but i already wasted too much time trying to fix it for such a small error width.
fixes #1853
=> updating margin for primary filter

meinberlin/apps/dashboard/__init__.py, meinberlin/assets/scss/components/_maplist.scss
fixes #1967 
fixes #1984 
fixes #1983
=> Ka 2019 02 dashboard for external

meinberlin/apps/plans/assets/Toggles.jsx, meinberlin/assets/scss/components/_switch.scss
=> working fix for removing label when nothing selected

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx
we might also need to set dragging but map guys online said this should work
=> adding tap false only to mobile to fix scrolling

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, meinberlin/assets/scss/components/_breadcrumbs.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_project_header.scss
=> small styling issues

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_status_bar.scss
=> Pm 2019 02 list elements

meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_status_bar.scss, meinberlin/assets/scss/components/_storefront.scss
=> Pm 2019 02 storefront adjustments

meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/assets/scss/components/_storefront.scss
some quick update for storefront little fixes for responsive
=> Pm 2019 02 storefront fix

meinberlin/apps/plans/serializers.py, meinberlin/assets/scss/components/_maplist.scss, meinberlin/config/settings/base.py
=> Ka 2019 02 image cropping

meinberlin/apps/plans/assets/FilterSecondary.jsx, meinberlin/apps/plans/assets/Toggles.jsx
fixes #2018 
and maybe fixes the IE-issue (for title search)
=> shorten organisation title in organisation filter tag

meinberlin/assets/scss/components/_accordion.scss
=> increasing right padding to stop overlap

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/assets/PopUp.jsx
=> open external links blank

meinberlin/apps/plans/serializers.py, requirements/base.txt, requirements/prod.txt
=> Project overview performance

meinberlin/templates/email_base.txt
=> email: Fix one redirect. Makes mail-tester.com even happier

meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/apps/plans/assets/FilterOptions.jsx, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/Toggles.jsx, meinberlin/assets/scss/_layout.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_switch.scss
bit annoying having to add - margin but i think it's better than trying to remove just the outer margins on the tiles?
=> Pm 2019 02 list width

meinberlin/templates/a4categories/includes/module_categories_form.html, meinberlin/templates/a4dashboard/includes/form_field.html, meinberlin/templates/a4dashboard/includes/module_areasettings_form.html, meinberlin/templates/a4dashboard/includes/module_basic_form.html, meinberlin/templates/a4dashboard/includes/module_phases_form.html, meinberlin/templates/a4dashboard/includes/progress.html, meinberlin/templates/a4dashboard/includes/project_information_contact_form.html, meinberlin/templates/a4dashboard/includes/project_information_form.html, meinberlin/templates/a4dashboard/includes/project_result_form.html, meinberlin/templates/a4forms/includes/form_checkbox_field.html, meinberlin/templates/a4forms/includes/form_field.html, meinberlin/templates/a4forms/includes/form_field_with_addon.html, meinberlin/templates/a4forms/includes/inline_form.html, meinberlin/templates/a4forms/multiple_input.html, meinberlin/templates/a4labels/includes/module_labels_form.html, meinberlin/templates/a4maps/map_choose_polygon_widget.html, meinberlin/templates/a4modules/module_detail.html, meinberlin/templates/a4polls/poll_404.html, meinberlin/templates/a4polls/poll_dashboard.html, meinberlin/templates/a4polls/poll_detail.html
after this pr has been merged we can remove mb specific styling from a4 and replace classes by twitter bootstrap4 classes
=> Mn 2019 02 overwrite all a4 templates

meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/assets/scss/components/_storefront.scss
hopefully fix #2061 once and for all!!!!!
=> fix for overlapping titles

webpack.prod.js
That should speed up building a bit
=> webpack.prod.js: Uglify in parallel

meinberlin/apps/plans/assets/ListMapBox.jsx
=> Mn 2019 03 fix ie11 issues

meinberlin/apps/projects/forms.py
=> fix empty label

meinberlin/apps/cms/models/storefronts.py, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/assets/scss/utility.scss
=> adding if and class to only display horizontal images on lg screens

meinberlin/templates/portal_header.html
=> changing wording in heading

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/Toggles.jsx, meinberlin/assets/scss/components/_map.scss, meinberlin/assets/scss/components/_switch.scss
need to display non when secondary filter open
=> adding total count to switch filter label and responsive styling

Makefile, package.json, webpack.common.js, webpack.dev.js, webpack.prod.js
- faster `make install` by using the dev config and only applying css minimization in the prod config 
- stop using `post-css`
- some cleanup
=> Webpack: Several optimizations

meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx
=> display zoom button on the topright corner on desktop

locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> fix translations

meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_shame.scss
=> Pm 2019 03 link fixes

meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/components/_tabs.scss
fixes  #2139
untested but should fix #2138 - browserstack local not currently working
=> adding bold to h3 on mobile as it is same size as base currently

locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/newsletters/forms.py, meinberlin/apps/newsletters/templates/meinberlin_newsletters/restricted_newsletter_dashboard_form.html
=> Mn 2019 04 fix newsletter form for group member

meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/container_list.html
=> only display allowed containers in containers list

meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js, meinberlin/apps/maps/templates/meinberlin_maps/map_choose_polygon_with_preset_widget.html, meinberlin/apps/maps/widgets.py, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/apps/plans/assets/plans_map.jsx, meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html, meinberlin/apps/plans/views.py, meinberlin/templates/a4maps/map_choose_point_widget.html, meinberlin/templates/a4maps/map_choose_polygon_widget.html
depends on https://github.com/liqd/adhocracy4/pull/332
token needs to be added as 'MAP_SERVICE_TOKEN' to local settings
=> add token everywhere maps are used and allow plans map with image tiles

meinberlin/apps/projectcontainers/forms.py, meinberlin/apps/projectcontainers/views.py, tests/projectcontainers/dashboard_components/test_views_project_container_projects.py
=> filter projects that are allowed to be edited by user

meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_maplist.scss, meinberlin/assets/scss/components/_portal_header.scss, meinberlin/assets/scss/components/_status_bar.scss
fixes #2016
Also fixes colour issue on ended banner, was not in issues but was discussed in meeting with Sandy and Caro
=> Pm 2019 04 container

meinberlin/assets/js/app.js, meinberlin/assets/js/embed.js
=> Mn 2019 04 fix comments in embed
