liqd/a4-meinberlin

meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_detail.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js, meinberlin/apps/maps/widgets.py, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_detail.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_list.html, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html, package.json, requirements/base.txt, webpack.common.js
Here I try to simplify the map setup by using ES6 imports and individual Webpack endpoints
=> Updates and cleanup around maps

webpack.common.js
=> fix the getLoginUrl

meinberlin/assets/js/app.js, requirements/base.txt
Not quite ready...see https://github.com/django-ckeditor/django-ckeditor/issues/346 for context
Edit: check here https://meinberlin-dev.liqd.net/dashboard/projects/blalal/information/
=> Update ckeditor to 5.7.0

meinberlin/apps/plans/admin.py, meinberlin/apps/plans/forms.py, meinberlin/apps/plans/models.py, meinberlin/test/factories/plans.py, tests/conftest.py, tests/organisations/test_admin.py
=> Mn 2019 allow to change plan group in admin

locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
=> Ka 2019 05 wording changes

meinberlin/apps/projects/serializers.py, package.json, requirements/base.txt
depends on: https://github.com/liqd/adhocracy4/pull/349
=> apps/projects/serializer: use phase that ends next as active phase

meinberlin/apps/cms/templates/meinberlin_cms/blocks/projects_block.html, meinberlin/assets/scss/components/_storefront.scss
fixes #2215
Oh and temp fix for project block which should be removed
=> stats arrow: changing position css for IE conpatability

meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/assets/scss/components/_filter_bar.scss
created background div to track clicks away from filter with function to close filters
fixes #1997
=> Filter: close filter when click away

meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_alert.scss
=> Alerts: darkening warning colour so can be seen easier

meinberlin/apps/contrib/widgets.py, meinberlin/apps/maps/widgets.py
fixes https://github.com/liqd/a4-meinberlin/issues/2275
=> apps: Add newly required argument 'renderer' to widgets

meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/plans/assets/PopUp.jsx
This was my attempt at doing the story
Slightly messed up with the commits but it is working
=> WIP #2058 status bar: first attempt at logic to change text on status bar

meinberlin/apps/offlineevents/rules.py
=> apps/offlineevents: adapt rules to work with groups

.polylintrc
=> remove .polylintrc

meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/includes/offlineevent_form.html
This was the remark of @rittermo . We change it here as well before porting the changes to a+.
=> apps/offlineevents/form: switch title and type in template

.coveragerc, meinberlin/assets/scss/_base.scss, requirements/dev.txt
as it broke the sticky map
fixes #2303
bonus: some random cleanup
=>  assets/scss: Remove overly generic overflow rule

.eslintrc
I got weird errors, this fixes it for me
=> ci: Fix commit hook linting

meinberlin/apps/projects/templatetags/meinberlin_project_tags.py
Not such a great solution, but works.
To test, add something like 
`<p>Count: {% get_num_entries module %}</p>`
somewhere here: https://github.com/liqd/a4-meinberlin/blob/43a482e5e2d332c59872ba32e7f73bc96bce1e6d/meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html#L184
=> apps/projects: templatetag to count user generated contributions

meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/budgeting/views.py, meinberlin/apps/contrib/mixins.py, meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/apps/documents/views.py, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_list.html, meinberlin/apps/ideas/views.py, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, meinberlin/apps/kiezkasse/views.py, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/mapideas/views.py, meinberlin/apps/polls/templates/meinberlin_polls/poll_detail.html, meinberlin/apps/polls/views.py, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/views.py, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_list.html, meinberlin/apps/topicprio/views.py, meinberlin/templates/a4modules/module_detail.html
still styling of module detail needed
=> Mn 2019 06 add modules detail views

.eslintrc, meinberlin/apps/contrib/static/js/ajax_modal.js, meinberlin/apps/contrib/static/js/unload_warning.js, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/apps/plans/assets/plans_map.jsx, package.json, webpack.common.js
and some ES6 conversion, as that made it easier.
Based on this tutorial: https://medium.com/@rossbulat/using-cookies-in-react-redux-and-react-router-4-f5f6079905dc
Hopefully doesn't break anything jquery related in other places...
=>  apps/plans: Remember closing the infobox on sticky map 

meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/apps/polls/templates/meinberlin_polls/poll_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components/_project_header.scss, meinberlin/assets/scss/utility.scss, meinberlin/templates/a4modules/module_detail.html, meinberlin/templates/a4polls/poll_detail.html
This will hopefully help with issue #2336
Also removed new back button from module view as it was too confusing to have breadcrumbs used everywhere else and then suddenly a back buttons but we need to review our breadcrumb wording as mentioned in issue #2339
=> Pm 2019 07 design fixes mod deet

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/templatetags/meinberlin_project_tags.py
=> Ka 2019 07 count all contributions

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/components/_participation_tile.scss, requirements/dev.txt
installed pydocstyle==3.0.0 
re-commited with another fix
added pydocstyle==3.0.0 to rquirments
still failing tests?
=> Pm 2019 07 module tile issues

locale/de/LC_MESSAGES/django.po
=> wording: update wording of German translations

meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/apps/projects/serializers.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, package.json, requirements/base.txt
depends on  https://github.com/liqd/adhocracy4/pull/356
=> apps/projects: use module running logic from a4 for project status bars

meinberlin/apps/documents/views.py, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, tests/documents/test_document_views.py
=> Timeline issues

meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_list.html, meinberlin/apps/maptopicprio/views.py, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/views.py, requirements/dev.txt
=> Mn 2019 module cluster fixes

.eslintrc, meinberlin/apps/contrib/static/js/ajax_modal.js, meinberlin/apps/contrib/static/js/unload_warning.js, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/apps/plans/assets/plans_map.jsx, package.json, webpack.common.js
Reverts liqd/a4-meinberlin#2310
=> Revert " apps/plans: Remember closing the infobox on sticky map "

meinberlin/apps/projects/views.py
=> apps/projects: add additional unique sorting

locale/de/LC_MESSAGES/django.po, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/templates/a4modules/module_detail.html
=> Pm 2019 07 fixes

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_timeline-carousel.html, meinberlin/assets/scss/components/_participation_tile.scss, meinberlin/assets/scss/components/_timeline-carousel.scss
=> Pm 2019 07 styling issue

meinberlin/apps/budgeting/exports.py, meinberlin/apps/documents/exports.py, meinberlin/apps/ideas/exports.py, meinberlin/apps/kiezkasse/exports.py, meinberlin/apps/mapideas/exports.py, meinberlin/apps/maptopicprio/exports.py, meinberlin/apps/polls/exports.py, meinberlin/apps/topicprio/exports.py
=> apps: allow group members to export

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_module_tile.html, meinberlin/templates/a4modules/module_detail.html
fixes #2404 and pluralizes the contributions on the module tile
=> Ka 2019 07 translations

locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/templates/a4modules/module_detail.html
=> Pm 2019 07 translation

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, package.json, requirements/base.txt
Depending on https://github.com/liqd/adhocracy4/pull/370
=> use a4 module cleanup

meinberlin/apps/documents/models.py, meinberlin/apps/documents/views.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_timeline-carousel.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
=> apps/documents: Overwrtie extends property

meinberlin/apps/organisations/forms.py
=> Group widget: changing default widget for group selection for orgs

meinberlin/apps/ideas/views.py, meinberlin/apps/notifications/emails.py, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.en.email, meinberlin/templates/email_base.html
The linter is broken, but I#ve seen that @rmader checked it in some other project. Will check that!
=> apps/notifications: add notification for moderator feedback

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> Ka 2019 09 translations

meinberlin/apps/plans/assets/FilterButton.jsx, meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/Toggles.jsx
We previously just silenced some linting warnings. Properly fix
them instead, were possible.
=> assets: Properly fix some linting issues

meinberlin/apps/offlineevents/management/commands/create_offlineevent_system_actions.py, tests/offlineevents/test_commands.py
Add tests because we ought to. Also resent notifications if an event got rescheduled far into the future.
=> offlineevent notification tests

meinberlin/apps/bplan/forms.py
fixes #2528
This seems to fix it?
=> apps/bplan: add start and end date to form so it saves

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, package.json, requirements/base.txt
fixes https://github.com/liqd/a4-product/issues/376 before we forget what the translation is meant to be.
=> Ka 2019 10 update a4

meinberlin/assets/js/app.js, meinberlin/assets/js/embed.js
Display timeline in embed view again
=> Mn 2019 10 fix timeline in embed

meinberlin/apps/dashboard/forms.py, meinberlin/apps/dashboard/urls.py, meinberlin/apps/dashboard/views.py, meinberlin/templates/a4dashboard/base_dashboard_project.html, meinberlin/templates/a4dashboard/project_create_form.html, meinberlin/templates/a4dashboard/project_list.html, package.json, requirements/base.txt
depends on: https://github.com/liqd/adhocracy4/pull/411
still missing:
- only publish when all required fields are filled in
- all the module-logic to only show and take into account published modules
- styling
=> Ka 2019 10 dashboard project create

meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/apps/documents/views.py
=> Mn 2019 10 dashboard preview

.travis.yml, meinberlin/config/settings/travis.py, meinberlin/test/factories/bplan.py, meinberlin/test/factories/budgeting.py, meinberlin/test/factories/documents.py, meinberlin/test/factories/extprojects.py, meinberlin/test/factories/ideas.py, meinberlin/test/factories/kiezkasse.py, meinberlin/test/factories/mapideas.py, meinberlin/test/factories/maps.py, meinberlin/test/factories/maptopicprio.py, meinberlin/test/factories/newsletters.py, meinberlin/test/factories/offlineevents.py, meinberlin/test/factories/plans.py, meinberlin/test/factories/polls.py, package.json, requirements/base.txt, tests/bplan/test_bplan_api.py, tests/helpers.py
As we use it for our production system.
=> ci: Use postgres instead of sqlite

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> Ka 2019 11 translations

package.json, requirements/base.txt, webpack.common.js
=> Small cleanups

locale/de_DE/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po
=> Mn 2019 11 dashboard wording changes

meinberlin/apps/bplan/templates/meinberlin_bplan/bplan_create_dashboard.html, meinberlin/apps/extprojects/templates/meinberlin_extprojects/external_project_create_dashboard.html, meinberlin/templates/a4dashboard/project_create_form.html
=> templates/dashboard: Remove help text

meinberlin/templates/a4dashboard/base_dashboard_project.html, meinberlin/templates/a4dashboard/includes/progress.html
fixes #2671
fixes #2688
fixes #2675
=> templates/dashboard: Only load modal once

meinberlin/apps/bplan/templates/meinberlin_bplan/bplan_create_dashboard.html, meinberlin/apps/extprojects/templates/meinberlin_extprojects/external_project_create_dashboard.html, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/container_create_dashboard.html, meinberlin/templates/a4dashboard/project_create_form.html
=> templates: Update wording of save buttons in dashboard

meinberlin/apps/contrib/static/js/unload_warning.js, meinberlin/templates/a4dashboard/base_dashboard_project.html
=> Mn 2019 12 fixes

package.json, requirements/base.txt, tests/extprojects/dashboard_components/test_views_project_extproject.py, tests/extprojects/dashboard_components/test_views_project_topics.py
adds a test for #2709 and will fix it with https://github.com/liqd/adhocracy4/pull/429
fixes #2709
=> tests/extprojects: add test for project_type

package.json, requirements/base.txt
=> settings: Update A4

meinberlin/assets/scss/components/_dashboard_nav.scss
=> caret size and rotation on click

meinberlin/apps/dashboard/views.py, meinberlin/assets/js/app.js, meinberlin/templates/a4dashboard/base_dashboard_project.html
=> Mn 2019 12 dashboard fixes

tests/extprojects/dashboard_components/test_views_extproject_point.py, tests/projectcontainers/dashboard_components/test_views_container_point.py
for some reason the tests failed on my local machine
=> tests: compare dict entries except for string comparison

meinberlin/apps/embed/assets/embed.js, meinberlin/apps/embed/templates/meinberlin_embed/embed.html
Fixes https://github.com/liqd/a4-meinberlin/issues/2779
=> apps/embed: Use CSRF token for logout

meinberlin/apps/contrib/widgets.py, meinberlin/apps/embed/assets/embed.js, meinberlin/apps/embed/assets/popup-close.js, meinberlin/apps/embed/templates/meinberlin_embed/embed.html, meinberlin/apps/embed/templates/meinberlin_embed/login_popup_close.html, meinberlin/apps/plans/assets/ListMapBox.jsx, meinberlin/apps/plans/assets/PlansMap.jsx, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_maplist.scss, webpack.common.js
This reduces the loaded js size a bit and fixes some bugs (and hopefully does not introduce new ones), including:
* login via model when embedded did not have a next parameter, so popup would not close
* select2 did not work (broken container project selection)
* some css behaving weirdly
=> more js cleanup

requirements/base.txt, webpack.common.js
Otherwise we get crashes when running with production settings.
=> webpack: Add some missing webpack endpoints

meinberlin/apps/maps/assets/map_choose_polygon_with_preset.js
Fixes https://github.com/liqd/a4-meinberlin/issues/2823
=> apps/maps/assets: Fix import of FileSaver

meinberlin/apps/mapideas/forms.py
=> settings: update path from a4

meinberlin/assets/scss/components/_dashboard_nav.scss, meinberlin/assets/scss/components/_progress.scss, meinberlin/templates/a4dashboard/includes/progress_line_in_progress.html
@fuzzylogic2000 ok so most of my styling stuff i scrapped anyway so figured would just put it all in same pull request, it's working and not making loads of spans so yey?!
=> Pm 2020 03 dashboard styling

meinberlin/templates/account/login.html, meinberlin/templates/account/signup.html
Reverts liqd/a4-meinberlin#2652
=> Revert "templates/sign_up: add click tracking to login and signup with if to …"

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_event_upcomming.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_phase_over_soon.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_followers_phase_started.de.email, meinberlin/templates/a4reports/emails/report_moderators.de.email, meinberlin/templates/a4reports/emails/report_moderators.en.email, meinberlin/templates/account/email/email_confirmation.de.email
=> Ks 2020 03 email wording

meinberlin/apps/users/apps.py, meinberlin/apps/users/emails.py, meinberlin/apps/users/signals.py, meinberlin/apps/users/templates/meinberlin_users/emails/welcome.de.email, meinberlin/apps/users/templates/meinberlin_users/emails/welcome.en.email
Adds welcoming mail that is sent once user confirmed her/his e-mail (allauth signal email_confirm)
=> apps/users: add receiver to send email on email_cofirm

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.en.email, meinberlin/templates/a4reports/emails/report_moderators.de.email, meinberlin/templates/a4reports/emails/report_moderators.en.email
=> Ks 2020 03 change date format in mails

meinberlin/apps/embed/assets/embed.js, package.json, webpack.common.js
This makes the changes from https://github.com/liqd/a4-meinberlin/pull/2880 work on IE11...
=> Fix IE11 event handling

meinberlin/apps/account/forms.py
Fixes https://github.com/liqd/a4-meinberlin/issues/2813 (well, at least prevents new cases to pop up)
=> apps/account/forms: Check username for case insensitive uniqueness

meinberlin/apps/contrib/sitemaps/static_sitemap.py, meinberlin/apps/organisations/models.py
Closes https://sentry.liqd.net/sentry/meinberlin-prod/issues/815/
This was forgotten in https://github.com/liqd/a4-meinberlin/pull/2453 ;)
=> Prefix 'plan-list' reverse queries

meinberlin/apps/bplan/templates/meinberlin_bplan/emails/submitter_confirmation.de.email
=> apps/bplan: wording change subject of submit confirmation email

meinberlin/apps/contrib/management/commands/errored_task_notification.py
This is necessary after 836db701db1963
=> apps/contrib: Update background task import

meinberlin/apps/mapideas/forms.py, meinberlin/apps/maps/templates/meinberlin_maps/map_choose_polygon_with_preset_widget.html, meinberlin/apps/plans/forms.py, meinberlin/apps/projects/forms.py, meinberlin/assets/js/app.js, package.json, requirements/base.txt
Cleanups for our `app.js` and use select2 in more places.
Depends on: https://github.com/liqd/adhocracy4/pull/550
Related: https://github.com/liqd/a4-meinberlin/issues/2935
=> Dropdown select fixes

meinberlin/apps/captcha/__init__.py, meinberlin/apps/captcha/apps.py, meinberlin/apps/captcha/assets/captcheck.js, meinberlin/apps/captcha/fields.py, meinberlin/apps/captcha/mixins.py, meinberlin/apps/captcha/templates/meinberlin_captcha/captcheck_captcha_widget.html, meinberlin/apps/captcha/widgets.py, meinberlin/apps/users/forms.py, meinberlin/config/settings/base.py, meinberlin/config/settings/test.py, meinberlin/templates/account/signup.html, tests/users/test_signup.py, tests/users/test_views.py, webpack.common.js
This is a simple port from a+/enquete. Does not implement wagtail
form support and misses wordings.
If we didn't need wagtail support we'd mostly be done here :/
=> apps/captcha: Add app and set it up for signup

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/platformemails/templates/meinberlin_platformemails/emails/platform_email.de.email, meinberlin/apps/platformemails/templates/meinberlin_platformemails/emails/platform_email.en.email
fixes  #2966 except the organisation.name with the small b in meinberlin which I can't find?!
=> Pm 2020 05 platform email issue

meinberlin/config/settings/base.py
should I change this in base? it is the correct name so i thought yes but i'm not sure?! WAGTAIL_SITE_NAME is only used in platform mails so it should break anything
fixes #2966
=> meinberlin to meinBerlin

meinberlin/apps/bplan/emails.py
=> bplan/emails: remove attachments from bplan office worker notification

meinberlin/templates/email_base.html
This might fix it but as I cannot replicate it then I don't know?!
=> email_base; add margin auto to help centering on resize fixes #2932

meinberlin/apps/bplan/emails.py, meinberlin/apps/bplan/signals.py, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_update_confirmation.de.email, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_update_confirmation.en.email
I hope it works how we think it does with the changes sent by the api, I didn't figure out how to test that?!
=> bplan/email: add templates and signal and new email class

package.json
Reverts liqd/a4-meinberlin#3015
=> Revert "fix(deps): update dependency copy-webpack-plugin to v6.0.3"

meinberlin/test/factories/bplan.py, tests/bplan/dashboard_components/test_views_bplan_basic.py, tests/bplan/dashboard_components/test_views_bplan_list.py, tests/bplan/test_bplan_api.py, tests/bplan/test_views_integration.py
I wanted to write more tests and test the models, but couldn't get a statement factory working. It complained about the missing external project. :(
=> more tests for bplans

meinberlin/apps/notifications/management/commands/send_test_emails.py
@fuzzylogic2000 this was my just copy over test but I think it currently just checks if there is a bplan, i need to add the parts where it checks if it updates the bplan, also how the does this reduce test coverage?! its a test?! errr
=> apps/notifications/send_test_emails: add new email to test emails

meinberlin/apps/cms/templates/meinberlin_cms/docs_page.html, meinberlin/apps/cms/templates/meinberlin_cms/home_page.html, meinberlin/apps/cms/templates/meinberlin_cms/simple_page.html, meinberlin/apps/cms/templates/meinberlin_cms/streamfield_simple_page.html, meinberlin/apps/embed/templates/meinberlin_embed/embed.html, meinberlin/apps/livequestions/assets/Filters.jsx, meinberlin/apps/livequestions/assets/InfoBox.jsx, meinberlin/apps/livequestions/assets/PresentBox.jsx, meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/livequestions/assets/QuestionModerator.jsx, meinberlin/apps/livequestions/assets/QuestionPresent.jsx, meinberlin/apps/livequestions/assets/QuestionUser.jsx, meinberlin/apps/livequestions/assets/StatisticsBox.jsx, meinberlin/apps/livequestions/templates/meinberlin_livequestions/question_present_list.html, meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/apps/plans/assets/FilterRadio.jsx, meinberlin/assets/images/icon_liveq_infografik_phone.svg, meinberlin/assets/images/icon_liveq_infografik_question.svg, meinberlin/assets/images/icon_liveq_infografik_thumb.svg, meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components/_tile.scss, meinberlin/assets/scss/utility.scss, meinberlin/templates/base.html
this is the stuff that was lost in my last pull request
=> Pm 2020 09 styling livequestions recovery

meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_accordion.scss, meinberlin/assets/scss/components/_ck_embed.scss
this will sort the weird nested div stuff, its a bit messy, sorry!
=> app.js: add class to the iframe when added via ckeditor, update styling

tests/livequestions/test_livequestion_templatetags.py
=> tests/livequestions: test for templatetags

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/livequestions/phases.py, meinberlin/apps/livequestions/templates/meinberlin_livequestions/question_present_list.html, meinberlin/apps/projects/templatetags/meinberlin_project_tags.py
fixes  #3142
fixes #3141
fixes #3143
and partly #3144
=> Ks 2020 09 issue fixing

meinberlin/apps/dashboard/blueprints.py, meinberlin/apps/livequestions/assets/Filters.jsx, meinberlin/apps/livequestions/assets/InfoBox.jsx, meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/livequestions/assets/QuestionModerator.jsx, meinberlin/apps/livequestions/assets/QuestionUser.jsx, meinberlin/apps/livequestions/assets/StatisticsBox.jsx, meinberlin/apps/livequestions/templates/meinberlin_livequestions/question_present_list.html, meinberlin/assets/images/blueprints/interactive-event.svg, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/utility.scss
ok there was an unexpected js hole that i fell into but this should be everything :)
Also still want to do a code tidy but feel that would be better done monday morning
=> livequestions styling issue

package.json, requirements/base.txt
=> deps: update a4

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components/_tabs.scss, webpack.common.js
I don't know is loading the video embed with adhocracy4 is correct but it works as it's loading before any of the map css, I wonder if it would be best to have it own entry point? @fuzzylogic2000 @rmader @Rineee what do you think?
=> Pm 2020 10 video format issues

package.json
Reverts liqd/a4-meinberlin#3191
=> Revert "fix(deps): update dependency webpack to v5"

webpack.common.js
Makes loading stuff slightly faster
=> webpack: Use optimized static files for dsgvo-embed

webpack.common.js
Reverts liqd/a4-meinberlin#3198
waiting for new dist file in dsgvo
=> reverting the revert "webpack: Use optimized static files for dsgvo-embed""

package.json
Reverts liqd/a4-meinberlin#3103
fix popover on safari fixes #3201
=> Revert "fix(deps): update dependency leaflet to v1.7.1"

meinberlin/apps/livequestions/assets/Filters.jsx, meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/livequestions/assets/QuestionForm.jsx, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components/_select2.scss, meinberlin/assets/scss/style.scss
Ok the last commit adds a scroll to the question however the question is added a bit too slowly, not sure if there's anything we can do about that? 
@Rineee found the js package that skins select elements which I had totally forgotten about :D so should be less stress about that! :)
=> Pm 2020 12 styling issues

renovate.json
=> renovate.json: allow minor updates to auto merge

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
@phillimorland That was my attempt to fix #3394. Not successfull there. Can we have a look together? I would like to know how to fix it!
=> WIP: apps/plans: make title break on detail page

locale/de_DE/LC_MESSAGES/django.po
Removed this from the other PR, so we can merge independently
fixes #3408
=> locale: fix spelling typo

meinberlin/apps/plans/assets/PlansList.jsx
See https://web.dev/uses-passive-event-listeners/
=> app/plans/assets: Use passive scroll listener

webpack.common.js
Reverts liqd/a4-meinberlin#3415
because of #3422 :( Let's have another go next week!
=> Revert "webpack: Explicitly declare chunk dependencies"

meinberlin/assets/scss/components/_timeline-carousel.scss
=> assets/timeline-carousel: add overflow hidden for small screens

meinberlin/assets/scss/components/_timeline-carousel.scss
Reverts liqd/a4-meinberlin#3427
Sorry!
=> Revert "assets/timeline-carousel: add overflow hidden for small screens"

locale/de_DE/LC_MESSAGES/django.po, meinberlin/apps/budgeting/forms.py, meinberlin/apps/ideas/forms.py, meinberlin/apps/kiezkasse/forms.py, meinberlin/apps/livequestions/assets/QuestionBox.jsx, meinberlin/apps/mapideas/forms.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/topicprio/forms.py, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components/_select2.scss, meinberlin/templates/a4modules/module_detail.html
have added select2 to other category widgets for consistency
=> Pm 2021 03 release style issues

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/templates/a4dashboard/includes/module_phases_form.html
Hm, I thought there was a way to add the helptext to the form, but I couldnt find one as its all done via components and I think they dont allow helptexts? So now I just added it in the template (as done for affiliations).
=> Ks 2021 03 change phase form titles

meinberlin/apps/livequestions/models.py, meinberlin/templates/a4modules/module_detail.html
Live stream deletion is still a bit odd, but maybe a little better like this?
=> Ks 2021 02 remove livestream object when its deleted

meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/container_list_dashboard.html, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_lr_bar.scss, meinberlin/assets/scss/utility.scss
Using flag can_add_project to show enabled or disabled button
Along with hint/note on the left side (incl. exclamation icon)
Taiga task 4082
=> Make container feature inactive

meinberlin/apps/plans/assets/PlansList.jsx
Reverts liqd/a4-meinberlin#3420
fixes #3583
=> Revert "WIP plans/assets: Render project tiles on demand"

.github/workflows/django.yml
Add a django workflow for building and deploying via github actions.
=> add github actions replacement for travis

meinberlin/apps/projects/templatetags/meinberlin_project_tags.py, meinberlin/assets/js/app.js, meinberlin/config/settings/base.py, package.json, requirements/base.txt
Depending! Only merge when the react for the polls is all in a4!
=> apps/polls: use react from a4

meinberlin/apps/polls/exports.py, package.json, requirements/base.txt
=> Ks 2021 07 change order of questions in exports

meinberlin/assets/scss/components/_poll.scss, package.json, requirements/base.txt
contains the hash to the related a4 commit
=> apps/poll/editview: updating class names to a4

meinberlin/assets/scss/components/_poll.scss, package.json, requirements/base.txt
=> styling for new poll

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
Wasnt sure about translation of error message, but left a note for Caro inside story..
=> Ks 2021 07 translations

meinberlin/apps/plans/exports.py
US #4523 plans: add new info in export
=> created and modified fields in exported plans

meinberlin/apps/plans/exports.py, tests/plans/test_export.py
Maybe there are too many tests in the test, because some of it should be tested in a4. But with these we do also notice if something breaks there!
=> Kl 2021 08 plan export test

meinberlin/apps/plans/templates/meinberlin_plans/plan_dashboard_list.html, meinberlin/apps/plans/views.py
I put the small change into the second commit, so that @sabinammm can look at the first commit to also add the filter to the Bplans and external projects.
=> apps/plans: add free text filter for dashboard list

meinberlin/apps/bplan/views.py, meinberlin/apps/extprojects/views.py
Task add filter for bplans and external projects
=> Sm 2021 08 freetext filter

meinberlin/apps/plans/exports.py, tests/plans/test_export.py
Closes part of #3793, the other one needs to be fixed in a4.
=> Sm 2021 08 issue export time difference

meinberlin/apps/plans/forms.py
@fuzzylogic2000 thanks for the help. I'm still confused about the dashboard vs other forms. Maybe we can talk about it when you get the chance.
=> changed contact address form field

meinberlin/assets/scss/components/_item_detail.scss
=> maps/menu: three dots menu above maps

meinberlin/apps/bplan/templates/meinberlin_bplan/bplan_list_dashboard.html, meinberlin/apps/extprojects/templates/meinberlin_extprojects/extproject_list_dashboard.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_dashboard_list.html, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/container_list_dashboard.html, meinberlin/assets/scss/components/_lr_bar.scss, meinberlin/templates/a4dashboard/project_list.html
=> dashboard/buttons: making buttons wrap and expand correctly on mobile

Makefile, README.md, meinberlin/config/settings/dev.py
Reverts liqd/a4-meinberlin#3817
=> Revert "dev: add option to use postgresql in dev environment"

locale/de_DE/LC_MESSAGES/django.po
=> apps/plans/templates: fixed spelling mistake in plan form

requirements/prod.txt
=> requirements/prod: use hiredis to silence redis-py warnings

meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx, meinberlin/apps/budgeting/assets/helpers.js, meinberlin/apps/budgeting/assets/react_proposals.jsx, meinberlin/apps/budgeting/templatetags/react_proposals.py, meinberlin/assets/js/app.js, meinberlin/assets/scss/components/_list_item.scss
To mount the react list, please add the following lines to `meinberlin_budgeting/proposal_list.html`:
`{% load react_proposals %}`
`{% react_proposals view.module %}`
=> budgeting/proposals/list: add react list

meinberlin/apps/budgeting/phases.py, meinberlin/apps/dashboard/blueprints.py
@Rineee 
This now contains the new module in the blueprints, but is still missing the right icon, which I think we can add later, right?
=> meinberlin/apps/dashboard: added new participatory budget to dashboard

babel.config.js, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalList.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/__snapshots__/BudgetingProposalList.jest.jsx.snap
This is just testing when there are no items
=> [#4987] apps/budgeting/__tests__: add snapshot for budgeting list without items

meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalListItem.jest.jsx, meinberlin/apps/budgeting/serializers.py
add modified to serializer
using new modified filed to distinguish in frontend
desctructured proposal to p
fixes #4042
=> apps/budgeting/proposal-list-item: showing modified or created date

meinberlin/apps/budgeting/api.py
Alright, this is the filter info. 
@khamui Can you do with that list or do you need another format? The icons for example might be better in a dict? Or does that not matter for React anyway?
And @Rineee I hope, you don't hate it too much...
=> apps/budgeting: add filter info and choices to proposal API

meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/FilterBar.jsx, meinberlin/apps/budgeting/assets/FilterBarDropdown.jsx, meinberlin/apps/budgeting/assets/FilterBarListMapSwitch.jsx, meinberlin/apps/budgeting/assets/__tests__/__snapshots__/BudgetingProposalList.jest.jsx.snap, meinberlin/assets/scss/components/_control-bar.scss
=> Kt 2021 11 proposal filter bar

Makefile, meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx, meinberlin/apps/cms/templates/meinberlin_cms/blocks/richtext_block.html, meinberlin/apps/cms/templates/meinberlin_cms/includes/storefronts.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_shame.scss, meinberlin/assets/scss/components/_blocks.scss, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_poll.scss, meinberlin/assets/scss/utility.scss, package.json, requirements/base.txt
relies on: https://github.com/liqd/adhocracy4/pull/923
=> Release frontend issues including poll

meinberlin/config/settings/base.py
Reverts liqd/a4-meinberlin#4091
=> Revert "settings/base.py: reconfig embed provider to fix #4071"

meinberlin/config/settings/base.py
Reverts liqd/a4-meinberlin#4081
=> Revert "settings/base.py: updated ck config to incl iframely public endpoint …"

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/includes/container_detail.html
=> apps/projectcontainers/tabs: using data-bs-toggle

meinberlin/apps/budgeting/assets/VoteButton.jsx, meinberlin/apps/budgeting/predicates.py, meinberlin/apps/budgeting/rules.py, meinberlin/apps/votes/api.py, meinberlin/apps/votes/models.py, meinberlin/test/factories/votes.py, tests/budgeting/conftest.py, tests/budgeting/rules/test_rules_vote.py, tests/budgeting/test_views_integration.py, tests/votes/conftest.py, tests/votes/test_token_vote_api.py, tests/votes/test_votes_models.py
The tests for proposal api/serializers are still missing, I started with it, but not finished yet.. 
Sorry, I got a bit crazy with the tests for the voting api, but decided to rather write a new test for every user role as it was too annoying with the token saved in the session when doing the login/logout procedure..
=> Ks 2021 12 votes tests

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
Stumbled across this when checking the plans..
=> Ks 2022 01 plans detail tiny fix

meinberlin/apps/projects/admin.py, package.json, requirements/base.txt
Depends on a4 PR[ #992](https://github.com/liqd/adhocracy4/pull/992)
=> [#5404] apps/projects: show editable project slug field in django-form

.github/workflows/django.yml
* use ubuntu 20.04
* use python 3.8
* use postgresql 3.8
=> ci: upgrade container to ubuntu 20.04

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_item_detail_2.scss
=> apps/plans: add participation field info to plan detail

tests/users/test_models.py
This test was updated to test initiator righs as discussed in #4135
=> tests/users: add testing of initator rights in other organisations

meinberlin/config/settings/dev.py, meinberlin/config/settings/production.py
needs to be merged together with changes in admin
=> config: set ckeditor provider from local.py

tests/projects/rules/test_rules_add_change_delete.py
Regarding Issue #4135
Added test to show that initiators in one organisation only have initator rights in another organisation, if they are group members of the specific project.
=> tests/projects/rules: added test to show initiator vs group member rights

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/assets/scss/_variables.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_item_detail_2.scss, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components/_radio.scss
might also fix #4200 - needs testing on BS
=> Pm 2022 03 issues a11y

package.json
Reverts liqd/a4-meinberlin#4181
fixes #4207
=> Revert "fix(deps): update dependency @fortawesome/fontawesome-free to v6"

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, package.json, requirements/base.txt
=> Kl 2022 03 update a4 translate

package.json, requirements/base.txt
=> debs: update a4 for comment issues

meinberlin/templates/portal_header.html
Regarding US 5629 [mB] change header wording
=> [#5629] meinberlin/templates: updated header to latest berlin.de version

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html
=> plan/detail/translations: fixing read less and make translations

package.json, requirements/base.txt
=> debs: update a4 for comments in poll issue

meinberlin/templates/account/email/unknown_account.de.email, meinberlin/templates/account/email/unknown_account.en.email
=> account: unknown account mail wording update

meinberlin/apps/newsletters/templates/meinberlin_newsletters/emails/newsletter_email.de.email, meinberlin/apps/newsletters/templates/meinberlin_newsletters/emails/newsletter_email.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_initiators_project_created.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_initiators_project_created.en.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.en.email, meinberlin/apps/notifications/templatetags/verbose_name.py, meinberlin/apps/platformemails/templates/meinberlin_platformemails/emails/platform_email.de.email, meinberlin/apps/platformemails/templates/meinberlin_platformemails/emails/platform_email.en.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_moderator.de.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_moderator.en.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_participant.de.email, meinberlin/apps/projects/templates/meinberlin_projects/emails/invite_participant.en.email
like second part of https://github.com/liqd/adhocracy-plus/pull/1797
to remember adding the tests, I added an issue.
=> apps/notifications: remove unused template tag

meinberlin/apps/newsletters/forms.py
like third commit https://github.com/liqd/adhocracy-plus/pull/1800/commits
=> apps/newsletters: make clean more robust

meinberlin/apps/votes/dashboard.py, meinberlin/apps/votes/templates/meinberlin_votes/voting_dashboard.html, meinberlin/apps/votes/views.py, tests/votes/test_dashboard_token.py
@phillimorland Could you have a look at the template? There is the table-stuff from the export in, but also a form, that is a bit out of place and a sentence about the number, which is not in the design. But let's leave the sentence and then ask if the wording is alright or were to actually put that number. But for the table and the form could you make the template nicer and make the generate button be on the left like in the design?
@Rineee I do create the tokens in a bit of a weird way because I didn't want to use the batch create as the docs say that that doesn't use the save from the model and that is what we want to use to make sure the token is unique. 
https://docs.djangoproject.com/en/4.1/ref/models/querysets/#bulk-create
What do you think?
=> [5044] Kl 2022 09 dashboard token export

meinberlin/apps/budgeting/dashboard.py, meinberlin/apps/budgeting/serializers.py, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_detail.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/documents/dashboard.py, meinberlin/apps/ideas/dashboard.py, meinberlin/apps/kiezkasse/dashboard.py, meinberlin/apps/livequestions/dashboard.py, meinberlin/apps/mapideas/dashboard.py, meinberlin/apps/maptopicprio/dashboard.py, meinberlin/apps/topicprio/dashboard.py, tests/budgeting/test_proposals_serializer.py
I could not find anything else to fix, also looked into templates.. we will probably find more later!
=> Ks 2022 09 module type fixes

tests/budgeting/dashboard_components/test_dashboard_components_budgeting.py, tests/documents/dashboard_components/test_dashboard_components_documents.py, tests/ideas/dashboard_components/test_dashboard_components_ideas.py, tests/kiezkasse/dashboard_components/test_dashboard_components_kiezkasse.py, tests/livequestions/dashboard_components/test_dashboard_components_livequestions.py, tests/maptopicprio/dashboard_components/test_dashboard_components_maptopics.py, tests/topicprio/dashboard_components/test_dashboard_components_topics.py, tests/votes/dashboard_components/test_dashboard_components_votes.py
Could not find a more elegant way to test this :woman_shrugging:
=> tests: test dashboard components

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/Pagination.jsx, meinberlin/apps/budgeting/assets/PaginationButton.jsx, meinberlin/apps/budgeting/assets/__tests__/Pagination.jest.jsx, meinberlin/assets/scss/components/_pagination.scss, tests/budgeting/test_proposals_api.py, tests/budgeting/test_proposals_serializer.py
=> Pm 2022 09 pagination js basic

webpack.common.js
analog to https://github.com/liqd/adhocracy-plus/pull/1950
=> webpack: only export a4 into this

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/livequestions/assets/Filters.jsx, meinberlin/apps/livequestions/assets/InfoBox.jsx, meinberlin/apps/projectcontainers/templates/meinberlin_projectcontainers/container_list_dashboard.html, meinberlin/assets/scss/_base.scss, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_a4-comments.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_embed_layout.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_footer.scss, meinberlin/assets/scss/components/_input_group.scss, meinberlin/assets/scss/components/_label.scss, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components/_rating.scss, meinberlin/assets/scss/components/_select2.scss, meinberlin/assets/scss/components/_timeline.scss, package.json
Mostly fixes https://github.com/liqd/a4-meinberlin/issues/4515
fixes https://github.com/liqd/a4-meinberlin/issues/4521
=> [updates] fixes from style lib removal

__mocks__/djangoMock.js, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalListItem.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/ControlBarSearch.jest.jsx, meinberlin/apps/documents/assets/__tests__/ChapterForm.jest.jsx, meinberlin/apps/documents/assets/__tests__/__snapshots__/ChapterNavItem.jest.jsx.snap, meinberlin/apps/livequestions/assets/__tests__/__snapshots__/CatergorySelect.jest.jsx.snap
* make gettext and pgettext return the original string
* fix tests
=> tests: modify django mock

locale/de_DE/LC_MESSAGES/django.po
Translations update from [LIQD Weblate](https://trans.liqd.net) for [meinBerlin/main](https://trans.liqd.net/projects/meinberlin/main/).
It also includes following components:
* [meinBerlin/js](https://trans.liqd.net/projects/meinberlin/js/)
Current translation status:
=> Translations update from LIQD Weblate

__mocks__/djangoMock.js, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/assets/ControlBar.jsx, meinberlin/apps/budgeting/assets/ControlBarDropdown.jsx, meinberlin/apps/budgeting/assets/ControlBarListMapSwitch.jsx, meinberlin/apps/budgeting/assets/Pagination.jsx, meinberlin/apps/budgeting/assets/__tests__/BudgetingProposalList.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/ControlBar.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/ControlBarDropdown.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/ControlBarListMapSwitch.jest.jsx, meinberlin/apps/budgeting/assets/__tests__/Pagination.jest.jsx, meinberlin/apps/budgeting/assets/react_proposals_init.jsx, meinberlin/assets/scss/components/_pagination.scss, package.json
@Rineee i implemented the entire filter logic by using `react-router` and i think it solves all our problems. Currently in WIP because pagination is broken.
But all other concerns regarding the filters are much easier now with the router hooks `useSearchParams` to extract query words from the url and to fetch with `useLocation`, so url and fetch-url are the same!
It might make our other PR obsolete #4553 .
issues:
fixes #4568 
fixes #4570 
fixes #4550
fixes #4522
=> filters via router

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/votes/templates/meinberlin_votes/token_export_dashboard.html, meinberlin/apps/votes/templates/meinberlin_votes/token_generation_dashboard.html
=> voting: fix some spelling issues

renovate.json
=> renovate: wagtail < 4.2

meinberlin/apps/budgeting/assets/ControlBarSearchTerm.jsx, meinberlin/apps/budgeting/assets/VoteButton.jsx, meinberlin/apps/contrib/assets/CheckboxBtn.jsx, meinberlin/apps/contrib/assets/PillBtn.jsx, meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/map_filter_and_sort.html, meinberlin/apps/livequestions/assets/Filters.jsx, meinberlin/apps/livequestions/assets/InfoBox.jsx, meinberlin/apps/livequestions/assets/QuestionModerator.jsx, meinberlin/apps/moderatorremark/templates/meinberlin_moderatorremark/includes/popover_remark.html, meinberlin/apps/plans/assets/FilterNav.jsx, meinberlin/apps/plans/assets/FilterRadio.jsx, meinberlin/apps/plans/assets/Toggles.jsx, meinberlin/assets/scss/_mixins.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_filter_bar.scss, meinberlin/assets/scss/components/_live_questions.scss, meinberlin/assets/scss/components/_radio.scss, meinberlin/assets/scss/components/_switch.scss
accessibility clean up and more fixes from old library swap
=> [issues] filter_bar, switch: update styling to filter buttons fixes #4608

Makefile, locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/templates/a4labels/includes/module_labels_form.html
=> fix labels helptext

meinberlin/apps/contrib/templates/meinberlin_contrib/component_library.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_detail.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_detail.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_detail.html, meinberlin/templates/a4modules/includes/module_detail_phase.html, meinberlin/templates/a4modules/module_detail.html
adding more semantic markup to help with sr
=> Pm 2022 11 semantic html

meinberlin/apps/documents/assets/DocumentManagement.jsx, meinberlin/templates/a4dashboard/base_dashboard_project.html, package.json, requirements/base.txt
depending on this PR:
https://github.com/liqd/adhocracy4/pull/1290
closes #4628
=> a4/dashboard/sidebar/DocumentManagement.jsx: update dashboard

meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_list.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/proposal_list.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_list.html
=> apps/* map containing/zoom-buttons: adding role and aria-label

meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.en.email
=> apps/notifications: show moderator status in email

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/assets/ControlBar.jsx, meinberlin/apps/budgeting/assets/ControlBarDropdown.jsx, meinberlin/apps/budgeting/filters.py, meinberlin/apps/budgeting/views.py, meinberlin/apps/contrib/filters.py, meinberlin/apps/moderationtasks/filters.py, tests/budgeting/test_proposals_api_filtering.py
Different issues I tried to fix, see commit messages.. the 2nd is solving that invalid filter choices throw an error (now they are just ignored) and adds default ordering which actually wasnt working before.. I also switched from many different filter backends for the model fields to one filterset that gathers all the model field filters.
=> Ks 2023 01 filter issues

meinberlin/apps/documents/assets/ChapterForm.jsx, meinberlin/assets/scss/_form.scss, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_commenting.scss, meinberlin/assets/scss/components/_dropdown.scss, meinberlin/assets/scss/components/_header.scss, meinberlin/assets/scss/components/_poll.scss, meinberlin/assets/scss/components/_select_dropdown.scss, meinberlin/assets/scss/components/_tabs.scss, meinberlin/assets/scss/utility.scss, meinberlin/templates/a4dashboard/base_dashboard.html, meinberlin/templates/a4images/image_upload_widget.html, package.json, requirements/base.txt
when testing polls I found issues with the buttons and that led to finding some dropdowns being width of the page so it's a bit all over the place, sorry!
=> [issues] Poll styling issues and dep updates

Makefile, locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
* don't keep obsolete translations
* update translations
=> Jd 2023 01 no obsolete translations

meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/assets/BudgetingProposalList.jsx, meinberlin/apps/budgeting/models.py, meinberlin/apps/budgeting/predicates.py, meinberlin/apps/budgeting/rules.py, meinberlin/apps/budgeting/views.py, meinberlin/apps/votes/admin.py, tests/budgeting/rules/test_rules_view_support.py, tests/budgeting/test_proposals_api_filtering.py, tests/budgeting/test_proposals_api_pagination.py, tests/budgeting/test_proposals_serializer.py
=> Ks 2023 03 annotate vote count

meinberlin/apps/ideas/views.py
Hopefully this finally fixes all missing annotations :see_no_evil:
=> apps/ideas/views: add all missing annotations in AbstractIdeaListView

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, package.json, requirements/base.txt
weren't so many new strings after all, that should be fine and early enough in the prod release
=> Kl 2023 02 update and tag a4

meinberlin/apps/budgeting/assets/VoteButton.jsx, meinberlin/apps/budgeting/views.py, meinberlin/apps/votes/middleware.py, meinberlin/config/settings/base.py, tests/budgeting/test_views_integration.py, tests/votes/test_voting_token_middleware.py
Will also write tests, but wanted to check first if this is good?
=> [6962] end session automatically

locale/de_DE/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_create_form.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_update_form.html
I will merge that myself as only wording changes. And we want the new string to be translated before release.
=> Kl 2023 02 wording prop form

meinberlin/apps/budgeting/dashboard.py, meinberlin/apps/budgeting/exports.py, meinberlin/apps/budgeting/views.py, tests/budgeting/dashboard_components/test_dashboard_components_budgeting.py, tests/budgeting/test_exports.py, tests/budgeting/test_views_integration.py
Showing the active module menu item is currently not yet working..
=> [7144] budgeting: change export for pb3

meinberlin/assets/scss/_base.scss
=> scss: make address fields non-italic

changelog/0001.md, changelog/README.md
=> [CHANGELOG] add new changelog folder and system

changelog/5204.md, meinberlin/test/factories/__init__.py, meinberlin/test/factories/livequestions.py, package.json, requirements/base.txt, tests/bplan/test_forms.py, tests/budgeting/rules/test_rules_support.py, tests/budgeting/test_proposals_api_filtering.py, tests/conftest.py, tests/ideas/test_forms.py, tests/ideas/views/test_idea_list.py, tests/plans/test_forms.py, tests/plans/test_serializer.py, tests/projects/test_serializer.py
This needs https://github.com/liqd/adhocracy4/pull/1447
=> Ks 2023 07 adding tests

changelog/5174.md, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/map_filter_and_sort.html, meinberlin/apps/plans/assets/PlansList.jsx, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html, meinberlin/assets/scss/components/_button.scss, meinberlin/assets/scss/components/_control-bar.scss, meinberlin/templates/a4dashboard/includes/project_list_item.html, package.json, requirements/base.txt
a4: https://github.com/liqd/adhocracy4/pull/1455
=> [7421 7412 issues] story related issues

package.json
Reverts liqd/a4-meinberlin#5122
=> Revert "fix(deps): update dependency bootstrap to v5.3.1"

changelog/7618.md, meinberlin/assets/scss/components/_follow.scss, meinberlin/assets/scss/utility.scss, package.json, requirements/base.txt
https://github.com/liqd/adhocracy4/pull/1500
=> [7618/7701] assets/follow: update classes with a4 prefix

.gitignore, changelog/3333.md
=> gitignore: add pyenv-version

changelog/7618.md, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html
=> [7618] projects/templates: always show follow button

changelog/1234.md, meinberlin/config/settings/production.py
=> settigns/production: add celerybeat periodic footer update

package.json, requirements/base.txt
…nt, deps: update a4 hash
**Tasks**
=> fix incorrect a4 hash

meinberlin/assets/scss/components/_button.scss
…the Berlin online version of teh style guide
**Tasks**
=> REDESIGN [fix] remove uneeded class extension 

changelog/0000.md, meinberlin/apps/livequestions/templates/meinberlin_livequestions/livestream_dashboard_form.html, meinberlin/templates/a4categories/includes/module_categories_form.html, meinberlin/templates/a4dashboard/base_form_module.html, meinberlin/templates/a4labels/includes/module_labels_form.html
=> REDESIGN [issue] ensure style sheets are loaded on all pages fixes dashboard

meinberlin/templates/500.html
=> fix logo.png name in 500 page

meinberlin/apps/cms/templates/meinberlin_cms/blocks/map_teaser_block.html
=> apps/cms: add missing static tag

meinberlin/apps/cms/templates/meinberlin_cms/blocks/map_teaser_block.html, meinberlin/apps/cms/templates/meinberlin_cms/home_page.html
=> fix map teaser js include

changelog/7770.md, meinberlin/apps/budgeting/serializers.py, meinberlin/assets/scss/components/_list_item.scss, meinberlin/assets/scss/components/_moderator_status.scss, meinberlin/assets/scss/style_bo.scss, meinberlin/react/budgeting/BudgetingProposalListItem.jsx, meinberlin/react/contrib/ListItemBadges.jsx, meinberlin/react/contrib/ModeratorStatus.jsx, meinberlin/react/contrib/__tests__/ListItemBadges.jest.jsx, meinberlin/react/contrib/__tests__/ModeratorStatus.jest.jsx, package.json
=> apps/budgeting: create moderator status component

.gitignore
=> gitiginore: fix pyenv version

changelog/7833.md, meinberlin/apps/budgeting/api.py, meinberlin/apps/budgeting/filters.py, meinberlin/apps/budgeting/serializers.py, meinberlin/apps/contrib/api.py, meinberlin/apps/contrib/filters.py, meinberlin/apps/ideas/api.py, meinberlin/apps/ideas/filters.py, meinberlin/apps/ideas/serializers.py, meinberlin/config/urls.py, tests/ideas/conftest.py, tests/ideas/test_ideas_api.py, tests/ideas/test_ideas_api_filtering.py, tests/ideas/test_ideas_api_pagination.py
=> [7833] add IdeaViewSet 

meinberlin/apps/ideas/api.py, meinberlin/apps/ideas/serializers.py, tests/ideas/test_ideas_api_filtering.py
=> apps/ideas: fix relative imports and test

webpack.dev.js
=> webpack-dev: update devtool config for better source maps

changelog/7828.md, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_list.html, meinberlin/apps/ideas/templatetags/react_ideas.py, meinberlin/react/ideas/IdeaList.jsx, meinberlin/react/ideas/__tests__/IdeaList.jest.jsx, meinberlin/react/ideas/react_ideas_init.jsx, webpack.common.js
=> [7828] create idea list react component

meinberlin/apps/contrib/migrations/0001_drop_background_task_table.py
=> apps/contrib: fix broken background-tasks migration

changelog/_3333.md, meinberlin/apps/contrib/mixins.py, meinberlin/apps/ideas/api.py, meinberlin/apps/mapideas/api.py, meinberlin/apps/mapideas/serializers.py, meinberlin/config/urls.py, tests/mapideas/test_map_ideas_api.py
=> mapidea api

meinberlin/apps/topicprio/api.py, tests/mapideas/test_map_ideas_api.py
=> apps/topicprio: add missing permissions to api

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/templates/a4modules/module_detail.html, package.json, requirements/base.txt, webpack.common.js
needs https://github.com/liqd/adhocracy4/pull/1506
=> [#6703] disable iframes to prevent videos from loading if js is disabled

changelog/7829.md, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_list.html, meinberlin/apps/mapideas/templatetags/react_mapideas.py, meinberlin/react/mapideas/MapIdeaList.jsx, meinberlin/react/mapideas/__tests__/MapIdeaList.jest.jsx, meinberlin/react/mapideas/react_mapideas_init.jsx, webpack.common.js
=> [7829] add map idea list in react

changelog/7274.md, docs/ckeditor.md, meinberlin/apps/budgeting/templates/meinberlin_budgeting/includes/proposal_form.html, meinberlin/apps/ideas/templates/meinberlin_ideas/idea_moderate_form.html, meinberlin/apps/ideas/templates/meinberlin_ideas/includes/idea_form.html, meinberlin/apps/kiezkasse/templates/meinberlin_kiezkasse/includes/proposal_form.html, meinberlin/apps/livequestions/templates/meinberlin_livequestions/livestream_dashboard_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/includes/mapidea_form.html, meinberlin/apps/mapideas/templates/meinberlin_mapideas/mapidea_moderate_form.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/includes/maptopic_form.html, meinberlin/apps/newsletters/templates/meinberlin_newsletters/newsletter_dashboard_form.html, meinberlin/apps/newsletters/templates/meinberlin_newsletters/restricted_newsletter_dashboard_form.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/includes/offlineevent_form.html, meinberlin/apps/plans/templates/meinberlin_plans/includes/plan_form.html, meinberlin/apps/platformemails/templates/meinberlin_platformemails/platformemail_form.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/includes/topic_form.html, meinberlin/assets/scss/_form.scss, meinberlin/templates/a4dashboard/base_form_project.html, package.json, requirements/base.txt
=> fix ckeditor forms

meinberlin/apps/bplan/tasks.py
=> apps/bplan: add missing brackets to set()

changelog/7778.md, docs/project_topics.md, meinberlin/apps/contrib/enums.py, meinberlin/apps/plans/exports.py, meinberlin/apps/plans/models.py, meinberlin/apps/plans/serializers.py, meinberlin/apps/plans/views.py, meinberlin/apps/projects/migrations/0005_topics.py, meinberlin/apps/projects/serializers.py, meinberlin/config/settings/base.py, package.json, requirements/base.txt, tests/plans/test_export.py
=> Move topics to enum class

meinberlin/apps/plans/migrations/0059_migrate_topics_to_m2m_topics.py
=> plans/migrations: fix topic migration for plans

meinberlin/apps/bplan/tasks.py
=> apps/bplan: fix wrong import for Topic model

Makefile, changelog/5275.md, docs/linting.md, meinberlin/templates/base.html, package.json, requirements/dev.txt
=> deps: add html linter for django templates to ensure consistency 

changelog/_6555.md, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/apps/livequestions/templates/meinberlin_livequestions/question_module_detail.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_detail.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/topicprio/templates/meinberlin_topicprio/topic_detail.html
wrap all ckeditor content in a separate div with class=ck-content so the styles won't affect other content
**Tasks**
=> Jd 2024 01 ckeditor class isolation

Makefile
=> Makefile: update the html linting to remove contradictory rules

changelog/7634.md, requirements/base.txt
=> [7634] upgrade to wagtail 5.2

changelog/2224.md, docs/api_caching.md, meinberlin/apps/dev/apps.py, meinberlin/apps/dev/management/commands/devtools.py, meinberlin/config/settings/dev.py
Added the management command `devtools` for creating fake data for testing API performance.
For testing locally, we can run the command from the root directory.
Usage examples:
```
$ ./manage.py devtools
$ ./manage.py devtools --projects 0
$ ./manage.py devtools --plans 550
$ ./manage.py devtools --ext-projects 100
```
**Tasks**
=> adds dev app and devtools command

Makefile, locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> [7898] update translation files

meinberlin/apps/dev/management/commands/devtools.py
=> devtools: fix query for fake plans,extprojects

meinberlin/apps/bplan/tasks.py
fixes https://sentry.liqd.net/organizations/liqd/issues/3580/
Testing: create a development bplan in dasbboard (with a valid identifier ? ->  `1 - 1`)
**Tasks**
=> apps/bplan: remove topics from updated_fields

package.json, requirements/base.txt
Update a4 to get the fix for the DashboardComponentDeleteSignalMixin
**Tasks**
=> update a4 hash

meinberlin/apps/maptopicprio/views.py, meinberlin/apps/offlineevents/views.py, meinberlin/apps/topicprio/views.py, tests/maptopicprio/dashboard_components/test_views_module_maptopics.py, tests/offlineevents/dashboard_components/test_views_project_offlineevents.py, tests/topicprio/views/test_topic_create.py, tests/topicprio/views/test_topic_delete.py, tests/topicprio/views/test_topic_update.py
module_component_updated signals
Add checks for the project_component_updated and module_component_updated signals. This should help to discover the usage of them and find bugs
requires https://github.com/liqd/adhocracy4/pull/1533 to work
**Tasks**
=> tests: add checks for project_component_updated and

changelog/5451.md, changelog/_6666.md, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_notification.de.email, meinberlin/apps/bplan/templates/meinberlin_bplan/emails/submitter_confirmation.de.email, tests/bplan/test_views_integration.py, tests/helpers.py
=> fix bplan statement formatting

package.json
This reverts commit 82846a1faa23c6994702b802bad1406e6b79657b. bootstrap v5.3 has some bigger changes, we'll want a story for that
**Tasks**
=> Revert "fix(deps): update dependency bootstrap to v5.3.2"

requirements/base.txt
=> requirements/base.txt: move back to upstream django-autoslug

changelog/2225.md, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_field.html
=> remove allauth password reset help_text

changelog/2225.md, locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/templates/account/password_reset_done.html
=> fix template reset done

package.json, renovate.json
=> Jd 2024 02 renovate bootstrap

renovate.json
=> renovate: disable updates for bootstrap for now

meinberlin/assets/scss/components_user_facing/_herounit_image_with_aside.scss
fix https://github.com/liqd/a4-meinberlin/issues/5401 
added a negative margin on child element in order to fix inheritance issue.
=> fix issue #5401

package.json, requirements/base.txt
update a4 so the new comment form works correctly
**Tasks**
=> Jd 2024 03 update a4

CHANGELOG.md, changelog/_1111.md
=> release v2402.1.2

CHANGELOG.md, changelog/_1111.md
=> release v2402.1.3

meinberlin/config/settings/base.py
=> settings/base: allow .doc upload in ckeditor

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> update translations for dev/redesign

package.json, requirements/base.txt
=> update a4 to include map fix

CHANGELOG.md, changelog/5600.md, changelog/_1111.md, package.json, requirements/base.txt
=> fix category save issue and bump release

changelog/_1112.md, package.json, requirements/base.txt, requirements/dev.txt
update a4, needed to do some js updates before rebasing the dev branch (and make the tests stop failing on our dev branch)
**Tasks**
=> Jd 2024 06 update a4

meinberlin/assets/scss/components_user_facing/_a4-poll.scss
a couple of tiny issues I've encountered on staging after merging
=> fix poll redesign issues

changelog/8163.md, meinberlin/apps/projects/api.py, meinberlin/apps/projects/tasks.py, meinberlin/config/settings/production.py, tests/projects/test_api_caching.py, tests/projects/test_tasks_caching.py
=> [8163] add public projects queryset

meinberlin/apps/projects/tasks.py, tests/projects/test_tasks_caching.py
=> projects/tasks: use unfiltered queryset for project serializer

.stylelintrc.json, changelog/_8232.md, meinberlin/assets/extra_css/_swiper.scss, meinberlin/assets/scss/components_user_facing/_a4-poll.scss, meinberlin/assets/scss/components_user_facing/_alert.scss, meinberlin/assets/scss/components_user_facing/_herounit_image_with_aside.scss, meinberlin/assets/scss/components_user_facing/_moderator_feedback.scss, meinberlin/assets/scss/components_user_facing/_moderator_notes.scss, meinberlin/assets/scss/components_user_facing/_phase_info.scss, meinberlin/assets/scss/components_user_facing/_pill.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/_variables.scss, meinberlin/assets/scss/styles_user_facing/variables/_breakpoints.scss, meinberlin/assets/scss/styles_user_facing/variables/_colors.scss, meinberlin/assets/scss/styles_user_facing/variables/_fonts.scss, meinberlin/assets/scss/styles_user_facing/variables/_spacing.scss
streamline and organize the user-facing variables
=> [#8232] update user facing variables

docs/api_caching.md
Add a mermaid graph to visualize the cache flow
**Tasks**
=> docs: add mermaid graph for caching strategy

tests/projects/test_tasks_caching.py
=> tests: add test for module publish signal to reset cache

meinberlin/assets/scss/components_dashboard/_list_item.scss
fix the readability of copyright on dashboard
=> list_item.scss: improve image copyright readability

meinberlin/react/contrib/contexts/FetchItemsProvider.jsx
=> FetchItemsProvider.jsx: fix JS crashing due to possibly unsupported function

meinberlin/assets/scss/components_user_facing/_item_detail.scss
=> item_detail.scss: fix wrong colors and stretched images

changelog/8447.md, meinberlin/apps/plans/templates/meinberlin_plans/plan_list.html, meinberlin/assets/images/map_pin_active.svg, meinberlin/assets/images/map_pin_default.svg, meinberlin/assets/scss/components_user_facing/_leaflet.scss, meinberlin/assets/scss/components_user_facing/_projects_list.scss, meinberlin/assets/scss/components_user_facing/_projects_map.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/assets/scss/styles_user_facing/variables/_colors.scss, meinberlin/react/contrib/map/Map.jsx, meinberlin/react/plans/PlansListMapBox.jsx, meinberlin/react/plans/PlansMap.jsx, meinberlin/react/plans/Toggles.jsx, meinberlin/react/projects/ProjectsMap.jsx
uses react leaflet for project overview and adds some rough styling/ layout
=> [#8447] project overview: convert vanilla leaflet map to react leaflet & update styling

meinberlin/react/projects/ProjectTile.jsx, meinberlin/react/projects/ProjectsList.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx
=> ProjectsListMapBox.jsx: fix error when no active phase

meinberlin/react/projects/ProjectTile.jsx
Hopefully this is enough to get the project overview on the dev server to run without errors
=> ProjectTile.jsx: fix error when project has no description

meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-comments.scss, meinberlin/assets/scss/styles_user_facing/_form.scss
fixes https://github.com/liqd/a4-meinberlin/issues/5716
**Tasks**
=> fix textarea resize

changelog/_8464.md, meinberlin/assets/scss/components_user_facing/_pill.scss, meinberlin/assets/scss/components_user_facing/_video-wall.scss, meinberlin/assets/scss/components_user_facing/ck-editor/_iframe.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/config/settings/base.py, meinberlin/templates/a4modules/module_detail.html, tests/livequestions/views/test_livequestion_detail.py, webpack.common.js
introduce styling for live-questions and improve functionalities like full-screen and showing videos even if their phase is over
=> [#8464] live-events hero

meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/templates/a4modules/module_detail.html
remove links to deleted css file, style comes from _video-wall.scss now
=> fix design dev server – remove links to deleted css file

changelog/_8467.md, meinberlin/assets/scss/components_user_facing/_card.scss, meinberlin/react/livequestions/LikeCard.jsx, meinberlin/react/livequestions/QuestionBox.jsx, meinberlin/react/livequestions/QuestionModerator.jsx
This PR styles the moderator icons.
**Tasks**
=> [#8467] Style moderator icons

package.json, requirements/base.txt
=> [8450] update a4 to mB-v2412.1

meinberlin/assets/scss/components_user_facing/_button.scss, meinberlin/assets/scss/components_user_facing/_control-bar.scss, meinberlin/assets/scss/components_user_facing/_multi-select.scss, meinberlin/assets/scss/components_user_facing/_pill.scss, meinberlin/assets/scss/components_user_facing/_project-tile.scss, meinberlin/assets/scss/components_user_facing/_projects-list.scss, meinberlin/assets/scss/components_user_facing/_projects_map.scss, meinberlin/assets/scss/components_user_facing/_typeahead.scss, meinberlin/assets/scss/styles_user_facing/_utility.scss, meinberlin/react/contrib/forms/MultiSelect.jsx, meinberlin/react/contrib/forms/__tests__/MultiSelect.jest.jsx, meinberlin/react/projects/ProjectMapOverlay.jsx, meinberlin/react/projects/ProjectTile.jsx, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx, meinberlin/react/projects/ProjectsMap.jsx, meinberlin/react/projects/filter-projects.js
closes #5764, #5770, #5772, #5765 
**Tasks**
=> [#8447] react/projects: fix remarks from design review

meinberlin/assets/scss/components/_poll.scss
styling for https://github.com/liqd/adhocracy4/pull/1726
=> a4-polls: unregistered users checkbox styles

docs/bplan_api.md, meinberlin/apps/bplan/serializers.py, requirements/base.txt, tests/bplan/test_bplan_api.py
Revert the changes for the point field back to geojson
**Tasks**
=> apps/bplan: revert changes for the point field back to geojson

changelog/_8656.md, meinberlin/assets/scss/components_user_facing/_search-profiles.scss, meinberlin/react/kiezradar/PushNotificationToggle.jsx, meinberlin/react/kiezradar/SearchProfile.jsx
This PR adds push notification toggles to the Kiez profile list view.
**Tasks**
=> [#8652] Kiez Profile List View: Add push notification toggle

changelog/8682.md, meinberlin/apps/account/forms.py, meinberlin/apps/account/templates/meinberlin_account/account_dashboard.html, meinberlin/apps/account/templates/meinberlin_account/profile.html, meinberlin/assets/scss/components_user_facing/_actionable-list.scss, meinberlin/assets/scss/components_user_facing/_pill.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/templates/account/email.html, meinberlin/templates/account/password_change.html
styling of account setting pages
**Tasks**
=> [#8682] account-settings: style according to new design

meinberlin/templates/navigation_primary.html
=> [#8668] navigation: wording changes

changelog/8573.md, meinberlin/assets/scss/components_user_facing/_project-tile.scss, meinberlin/react/projects/ProjectTile.jsx, meinberlin/react/projects/ProjectTopics.jsx
Change UI States for project tiles
**Tasks**
=> [#8573] Change UI States for project tiles

changelog/8601.md, meinberlin/templates/a4modules/module_detail.html
=> [#8601] module-detail: remove module navigation and change heading tag to h1

meinberlin/react/budgeting/SupportBox.jsx
Just some change to make the "you" bold in the text of the support box
**Tasks**
=> support-box/react: make the "you" bold in the text

changelog/8663.md, meinberlin/react/contrib/ControlBarFilterPills.jsx, meinberlin/react/contrib/__tests__/ControlBarFilterPills.jest.jsx, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx
Show search pills for every item in the filter instead of one per filter
**Tasks**
=> [#8663] project-overview/react: add search pills for every item in filters

meinberlin/assets/scss/components_user_facing/_alert.scss, meinberlin/assets/scss/components_user_facing/_multi-select.scss, meinberlin/assets/scss/styles_user_facing/_base.scss, meinberlin/react/contrib/forms/MultiSelect.jsx, meinberlin/react/contrib/forms/useCombobox.js, meinberlin/react/projects/ProjectTile.jsx
alert/scss: fix wrong classname
base/scss: fix style being overriden
multi-select/scss: prevent line wrap for any multi-select combobox
multi-select/react: add isMultiple flag
combobox: add comboboxref to handle focus
**Tasks**
=> add various fixes

meinberlin/apps/budgeting/templates/meinberlin_budgeting/includes/proposal_form.html, meinberlin/apps/budgeting/templates/meinberlin_budgeting/proposal_update_form.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/moderator_form.html, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_checkbox_field.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_create_form.html, meinberlin/apps/maptopicprio/templates/meinberlin_maptopicprio/maptopic_update_form.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_create_form.html, meinberlin/apps/offlineevents/templates/meinberlin_offlineevents/offlineevent_update_form.html, meinberlin/apps/plans/templates/meinberlin_plans/includes/plan_form.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/users_from_email_form.html, meinberlin/apps/votes/templates/meinberlin_votes/token_generation_dashboard.html, meinberlin/templates/a4dashboard/base_form_module.html, meinberlin/templates/a4dashboard/base_form_project.html, meinberlin/templates/a4forms/includes/form_checkbox_field.html
updates error messages and fixes https://github.com/liqd/a4-meinberlin/issues/5967
=> a4-images: fix image uploader issues

meinberlin/react/kiezradar/KiezradarList.jsx
This PR adds the kiezradar name in the delete modal.
**Tasks**
=> [#8751] Add kiezradar name in delete modal

meinberlin/react/contrib/map/react_choose_point_init.jsx, package.json, requirements/base.txt, webpack.common.js
fixes map namespace clash with react_maps
depends on a4 Pull Request: https://github.com/liqd/adhocracy4/pull/1766
fixes #5999 
**Tasks**
=> fix map namespaces

meinberlin/react/kiezradar/SearchProfile.jsx
Add search profile fixes, based on these GitHub issues:
- https://github.com/liqd/a4-meinberlin/issues/6012
- https://github.com/liqd/a4-meinberlin/issues/6013
**Tasks**
=> [#8836] Search profile fixes

meinberlin/apps/projects/templates/meinberlin_projects/participantinvite_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/participantinvite_form.html
fixes https://github.com/liqd/a4-meinberlin/issues/6042
=> fix: missing narrow cta pages

meinberlin/react/kiezradar/Kiezradars.jsx
This PR adds titles to kiezradar alerts.
**Tasks**
=> [#8877] [#8895] Add titles to kiezradar alerts

meinberlin/assets/scss/components_user_facing/_kiezradar.scss, meinberlin/react/kiezradar/KiezradarMap.jsx
Add kiezradar fixes, based on these GitHub issues:
- [#8750 [mB] Kiezradar Frontend: Creating a Kiez (radius) – [mobile] cannot place pin by taping on map](https://github.com/liqd/a4-meinberlin/issues/6046)
- [#8750 [mB] Kiezradar Frontend: Creating a Kiez (radius) – Tab focus on radius slider is not visible](https://github.com/liqd/a4-meinberlin/issues/6047)
**Tasks**
=> [#8890] Fix Kiezradar map issues

meinberlin/react/kiezradar/use-create-search-profile.jest.js, meinberlin/react/kiezradar/use-create-search-profile.js
This PR fixes the search profile participations index error.
**Tasks**
=> Fix search profile participations index error

package.json, requirements/base.txt
fixes https://github.com/liqd/a4-meinberlin/issues/6062
merges: https://github.com/liqd/adhocracy4/pull/1770
=> update a4: fix modal issue

changelog/8881.md, meinberlin/apps/contrib/templatetags/contrib_tags.py, meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html
Just backend implementation, no styling
**Tasks**
=> [#8881] project-info-page: add timeline html/ data

meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/templates/a4modules/module_detail.html
=> module-tiles: stretch tiles to 100% height

meinberlin/react/contrib/helpers.js, meinberlin/react/kiezradar/SearchProfile.jsx, meinberlin/react/plans/react_plans_map.jsx, meinberlin/react/projects/ProjectsControlBar.jsx, meinberlin/react/projects/ProjectsListMapBox.jsx, meinberlin/react/projects/getDefaultState.js
This PR adds URL params to the project overview.
**Tasks**
=> [#8857] Add URL params to project overview

meinberlin/apps/plans/migrations/0066_plan_geos_point.py, package.json, requirements/base.txt
=> fix plan geo migration

meinberlin/apps/contrib/templates/meinberlin_contrib/components/hero.html, meinberlin/assets/scss/components_user_facing/_hero.scss
fixes: https://github.com/liqd/a4-meinberlin/issues/6081 https://github.com/liqd/a4-meinberlin/issues/6079 https://github.com/liqd/a4-meinberlin/issues/6078 https://github.com/liqd/a4-meinberlin/issues/6076
more info: https://github.com/liqd/a4-meinberlin/issues/6076#issuecomment-2667999642
=> redesign: hero layout fixes

changelog/8898.md, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components_user_facing/_figures-box.scss, meinberlin/assets/scss/style_user_facing.scss
=> [#8898] project-detail: styling project detail box

changelog/6150.md, package.json, requirements/base.txt, tests/kiezradar/test_api_kiezradar.py, tests/kiezradar/test_kiezradar.py
fixes #6150 
*Describe your changes**
**Tasks**
=> kiezradar extra test for dict input

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html
=> fix project tile status bar

changelog/8898.md, meinberlin/apps/projects/templates/meinberlin_projects/project_actions.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_event.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html, meinberlin/apps/projects/views.py, meinberlin/assets/scss/components_user_facing/_project-actions.scss, meinberlin/assets/scss/style_user_facing.scss
=> [#8898] project-pages: add edit/back buttons

meinberlin/apps/projects/templates/meinberlin_projects/includes/timeline.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html, meinberlin/assets/scss/components_user_facing/_timeline.scss, meinberlin/assets/scss/style_user_facing.scss
**Description**
This PR implements the timeline component for the project info page. The timeline displays both modules and offline events in chronological order with appropriate styling to indicate past (completed) and future events.
=> [#8900] project information: create timeline component

meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html
=> item-detail: hide moderator feedback in some cases

meinberlin/assets/extra_css/_swiper.scss, meinberlin/assets/js/swiper_phases.js, meinberlin/assets/scss/components_user_facing/_phase_info.scss, meinberlin/templates/a4modules/includes/module_detail_phase_info.html, meinberlin/templates/a4modules/includes/module_detail_phase_swiper.html
=> phase-info: display active phase and smaller styling fixes

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_module_tile.html, meinberlin/assets/scss/components_user_facing/_module_tile.scss
Prettier module tiles :)
fixes #6029, #6119
**Tasks**
=> module-tiles: fix styling issues and truncate description

meinberlin/apps/cms/templates/meinberlin_cms/blocks/user_action_bar_block.html, meinberlin/assets/scss/components_user_facing/_user_action_bar.scss
This PR fixes the action bar button issues.
Resolves #6032.
**Tasks**
=> Fix action bar button issues

meinberlin/assets/scss/components_user_facing/_dropdown.scss
=> dropdown: prevent linebreak

meinberlin/apps/cms/templates/meinberlin_cms/blocks/info_bar_block.html, meinberlin/assets/scss/components_user_facing/_info-bar-block.scss
fixes #6095, #6097, #6050
**Tasks**
=> info-block: fix link & styling

meinberlin/apps/kiezradar/templates/meinberlin_kiezradar/search_profile_list.html, meinberlin/react/kiezradar/SearchProfiles.jsx
=> search-profile listings: fix titles

changelog/_8865.md, meinberlin/react/projects/ProjectsListMapBox.jsx, meinberlin/react/projects/filter-projects.js
This PR improves the kiezradar search.
**Tasks**
=> [#8865] Improve kiezradar search

meinberlin/assets/scss/components_user_facing/_navigation-meta.scss, meinberlin/templates/navigation_primary.html
=> [#8903] overhaul burger menu structure

changelog/_8891.md, meinberlin/apps/account/templates/meinberlin_account/notifications.html, meinberlin/apps/account/views.py, meinberlin/assets/scss/components_user_facing/_notifications.scss, meinberlin/react/account/FeedItem.jsx, meinberlin/react/account/Notifications.jsx, meinberlin/react/account/notification_data.js, meinberlin/react/account/react_notifications.jsx, meinberlin/react/contrib/helpers.js, meinberlin/react/kiezradar/SearchProfile.jsx
This PR adds search profile notifcations.
**Tasks**
=> [#8891] Add search profile notifications

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_details_summary.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_insights.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/assets/scss/components_user_facing/_figures-box.scss
Also created snippets for details summary and the insights.
**Desktop**
**Mobile**
=> templates/project_detail: style project insights

meinberlin/apps/account/templates/meinberlin_account/notifications.html, meinberlin/apps/account/views.py, meinberlin/react/account/FeedItem.jsx, meinberlin/react/account/Notifications.jsx, meinberlin/react/account/react_notifications.jsx
This PR implements the mark as read" on click of notification.
**Tasks**
=> [#8983] Notifications: implement "mark as read" on click of notification

meinberlin/react/account/Notifications.jsx, meinberlin/react/account/notification_data.js
This PR adds aggregated ratings for notifications.
**Tasks**
=> [#8985] Notifications: Add aggregated ratings

meinberlin/apps/cms/templates/meinberlin_cms/includes/hero_home.html, meinberlin/assets/scss/components_user_facing/_hero-home.scss, meinberlin/assets/scss/components_user_facing/_service-panel.scss
fixes #6196, #6199, #6200
**Tasks**
=> home-hero fixes

meinberlin/apps/bplan/serializers.py, meinberlin/apps/plans/forms.py, meinberlin/apps/plans/serializers.py, meinberlin/apps/projects/forms.py, meinberlin/apps/projects/serializers.py, package.json, requirements/base.txt, tests/conftest.py, tests/plans/test_forms.py, tests/plans/test_serializer.py, tests/projects/test_serializer.py
The dashboard settings for projects and plans wouldn't show correctly. This will fix it.
Depends on https://github.com/liqd/adhocracy4/pull/1778
**Tasks**
=> fix dashboard location not loading correctly

meinberlin/assets/scss/components_user_facing/_header.scss, meinberlin/assets/scss/style_user_facing.scss, meinberlin/templates/header.html
=> Add padding around logo

meinberlin/react/account/FeedItem.jsx
This PR fixes a on click "mark as read" potential race condition.
**Tasks**
=> Notifications: Fix "mark as read" potential race condition

meinberlin/apps/kiezradar/models.py, meinberlin/config/settings/base.py, tests/kiezradar/test_search_profile.py
=> search-profiles: fix typo in get_search_profiles_for_project

meinberlin/apps/notifications/api.py
Add `unread_count` to followed projects / search profiles.
**Tasks**
=> Notifications: Add unread_count to followed projects / search profiles

changelog/8751.md, meinberlin/apps/kiezradar/serializers.py, tests/kiezradar/test_api_kiezradar.py
=> fix kiez update

meinberlin/apps/kiezradar/models.py, tests/kiezradar/test_search_profile.py
=> [#8865] searchprofile fixes

meinberlin/assets/scss/components_user_facing/_notifications.scss
This PR fixes the notifications spacing.
Resolves #6181 and #6210.
**Tasks**
=> Notifications: fix spacing

meinberlin/react/account/FeedItem.jsx
This PR removes translation plurals.
Resolves #6210.
**Tasks**
=> Notifications: remove translation plurals

meinberlin/react/account/FeedItem.jsx, meinberlin/react/account/FeedList.jsx, meinberlin/react/account/Notifications.jsx
This PR updates the `read` state and `unreadCount` state when clicking link.
Resolves #6213.
**Tasks**
=> Notifications: on click update read count

meinberlin/apps/bplan/forms.py
=> bplan-form: remove is_archived field

changelog/6239.md, meinberlin/apps/kiezradar/models.py, tests/kiezradar/test_full_text_search.py
=> kiezradar: fix search profile full text search

meinberlin/assets/scss/components_user_facing/_narrow-wrapper.scss
=> narrow-wrapper: fix alignment of secondary cta

meinberlin/templates/header.html
=> header: add notifications page

meinberlin/react/projects/filter-projects.js
=> filter-projects: fix bug where kiez filter only worked when there also was a district filter set

meinberlin/templates/account/password_change.html
=> account: remove title from password page

meinberlin/react/kiezradar/SearchProfile.jsx, meinberlin/react/projects/getDefaultState.js
=> search-profile: fix wrong index for project state

meinberlin/apps/projects/templates/meinberlin_projects/includes/project_insights.html, meinberlin/apps/projects/templatetags/meinberlin_project_tags.py
fixes https://github.com/liqd/a4-meinberlin/issues/6225
=> fix insights button visibility

changelog/8866.md, meinberlin/apps/projects/templates/meinberlin_projects/includes/module-tile/module_insights.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/module-tile/module_tile.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_participation.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/templatetags/meinberlin_project_tags.py, meinberlin/assets/scss/components_user_facing/_module_tile.scss, meinberlin/fixtures/modules.json, meinberlin/templates/a4modules/module_detail.html, tests/projects/conftest.py, tests/projects/test_project_tags.py
Add stats to module tiles
**Tasks**
=> [#8866]: Add stats to module tiles

meinberlin/react/account/FeedItem.jsx, meinberlin/react/account/Notifications.jsx, meinberlin/react/account/notification_data.js
This PR adds project links in notifications.
**Tasks**
=> [#8994] Add project links in notifications

meinberlin/assets/scss/components_user_facing/_project-actions.scss
This PR changes the project edit link color.
Resolves #6162.
**Tasks**
=> Change project edit link color

meinberlin/assets/scss/components_user_facing/_alert.scss
This PR changes the alert spacing.
Resolves #6092.
**Tasks**
=> Change alert spacing

meinberlin/assets/scss/components_user_facing/_actionable-list.scss, meinberlin/templates/account/email.html
This PR changes the actionable list button order.
Resolves #5984.
**Tasks**
=> Change actionable list button order

meinberlin/apps/contrib/templates/meinberlin_contrib/components/info-box.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/moderator_feedback.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_event.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html, meinberlin/apps/projects/templates/meinberlin_projects/project_results.html, meinberlin/assets/scss/components_user_facing/_card.scss, meinberlin/assets/scss/components_user_facing/_info-box.scss, meinberlin/assets/scss/components_user_facing/_item_detail.scss, meinberlin/react/contrib/card/Card.jsx, meinberlin/react/contrib/card/CardStatus.jsx, meinberlin/templates/a4modules/module_detail.html
=> [#8956] style archived proposals

meinberlin/apps/contrib/templates/meinberlin_contrib/components/info-box.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/moderator_feedback.html, meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_event.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html, meinberlin/apps/projects/templates/meinberlin_projects/project_results.html, meinberlin/assets/scss/components_user_facing/_card.scss, meinberlin/assets/scss/components_user_facing/_info-box.scss, meinberlin/assets/scss/components_user_facing/_item_detail.scss, meinberlin/react/contrib/card/Card.jsx, meinberlin/react/contrib/card/CardStatus.jsx, meinberlin/templates/a4modules/module_detail.html
redo of https://github.com/liqd/a4-meinberlin/pull/6260 because of erroneous merge conflicts fix
=> budgeting: style archived proposal

meinberlin/apps/account/forms.py
This PR removes autocomplete from username field.
Resolves #5987.
**Tasks**
=> Remove autocomplete from username field

meinberlin/react/contrib/card/Card.jsx, meinberlin/react/contrib/card/CardList.jsx
fixes: https://github.com/liqd/a4-meinberlin/issues/6272
=> react/contrib/Card.jsx: fix issue with undefined children

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
Related to 
https://github.com/liqd/a4-meinberlin/pull/6232
and 
https://github.com/liqd/a4-meinberlin/issues/6316
=> Fix translations for datenschutz and all districts

changelog/6264.md, meinberlin/apps/notifications/signals.py, meinberlin/apps/notifications/tasks.py, meinberlin/config/settings/test.py, tests/notifications/test_api.py
=> fix sentry issue of db transaction

meinberlin/apps/projects/templates/meinberlin_projects/project_information.html, meinberlin/apps/projects/templates/meinberlin_projects/project_results.html
Add iframe dsgvo embed script
fixes #6300
**Tasks**
=> iframes: add dsgvo_video_embed.js where missing

meinberlin/assets/scss/components_user_facing/_map.scss, meinberlin/assets/scss/style_user_facing.scss
=> item-popup: add styling

meinberlin/apps/contrib/templates/meinberlin_contrib/item_detail.html
=> moderator-feedback: display at all times if moderator or feedback exists

docs/notifications.md, meinberlin/react/account/Notifications.jsx, meinberlin/react/account/notification_data.js
=> Add further notification types

meinberlin/assets/scss/components_user_facing/_search-profiles.scss, meinberlin/react/kiezradar/SearchProfile.jsx
=> Reorder search profile cancel button

locale/de_DE/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po, meinberlin/apps/cms/templates/meinberlin_cms/includes/hero_search.html
This PR changes the search wording.
Resolves #6293.
**Tasks**
=> Change search wording

locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po, meinberlin/apps/offlineevents/forms.py, meinberlin/apps/plans/forms.py, meinberlin/apps/projects/forms.py
=> [#9010] wordings: update dashboard wordings where possible

meinberlin/apps/kiezradar/matchers.py, tests/kiezradar/test_search_profile.py
=> search-profile: match profiles that have both a district and a kiez set

meinberlin/assets/extra_css/_ckeditor.scss, meinberlin/config/settings/base.py
=> ckeditor: adapt bleach settings, allow for custom ul/ol styles

meinberlin/assets/scss/components_user_facing/_projects_map.scss
=> plans-map: increase map search input font size to prevent zooming in on mobile

meinberlin/assets/scss/components_user_facing/_item_detail.scss
=> item-detail: interactive moderator-notes when item is archived

meinberlin/assets/scss/styles_dashboard/utility.scss, meinberlin/templates/a4dashboard/base_dashboard.html
=> dashboard: add logo with link back to home page

meinberlin/react/livequestions/QuestionPresent.jsx
=> live-event: add space to QuestionPresent

meinberlin/assets/scss/components_user_facing/_upload-wrapper.scss, meinberlin/templates/a4images/image_upload_widget.html
=> image-upload: fix markup & style for better focus visibility

meinberlin/apps/kiezradar/urls.py
=> urls: change kiezradar url to kiezauswahl

CHANGELOG.md, changelog/6351.md, changelog/8997.md
=> stage release mB-v2504.1

meinberlin/assets/scss/components_user_facing/adhocracy4/_a4-comments.scss, package.json, requirements/base.txt
fixes #6279
do not merge, depends on https://github.com/liqd/adhocracy4/pull/1785 being merged first
**Tasks**
=> comments: fix display of comment actions on mobile

meinberlin/apps/projects/signals.py
=> project-insights: adapt signals to react on delete and rating changes

package.json, requirements/base.txt
=> polls: update a4 for alert when unauthenticated

meinberlin/apps/cms/templates/meinberlin_cms/blocks/project_teaser_block.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/hero.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/plan_tile.html, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_tile.html
fix static file links so they dont start with `/` anymore.
**Tasks**
=> placeholders: fix static links

meinberlin/assets/scss/components_user_facing/_header.scss
=> header: add scroll-padding to html for sticky header

package.json, requirements/base.txt
=> a4: update to fix reporting items

meinberlin/apps/cms/templates/meinberlin_cms/email_form_page.html, meinberlin/apps/contrib/templates/meinberlin_contrib/components/hero.html, meinberlin/apps/plans/templates/meinberlin_plans/plan_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_detail.html, meinberlin/apps/projects/templates/meinberlin_projects/project_event.html, meinberlin/apps/projects/templates/meinberlin_projects/project_information.html, meinberlin/apps/projects/templates/meinberlin_projects/project_results.html
=> layout: make classes to ids and fix layout issues due to it

meinberlin/assets/scss/components_user_facing/_pill.scss
This PR uses the styleguide pill size.
Resolves #6306.
**Tasks**
=> Use styleguide pill size

meinberlin/react/account/notification_data.js
This PR fixes the notifications translations.
**Tasks**
=> Fix notifications translations

meinberlin/config/settings/base.py
change image size for hero images
**Tasks**
=> image-aliases: change hero image size to 1000x500

package.json, requirements/base.txt
updates a4 to allow scrolling inside combobox/ select boxes
**Tasks**
=> update a4 for useCombobox fix

changelog/6392.md, changelog/6394.md, changelog/6395.md, locale/de_DE/LC_MESSAGES/django.po
adding changelogs and translation fix
**Tasks**
=> changelog/translations: add changelog; fix translation issue with doubled helptext

changelog/0000.md, meinberlin/apps/plans/admin.py
=> update gis admin plans

changelog/1111.md, meinberlin/apps/plans/serializers.py, meinberlin/apps/projects/serializers.py
=> projects,plans: handle exceptions for thumbnail images

CHANGELOG.md, changelog/0000.md, changelog/1111.md, changelog/6392.md, changelog/6394.md, changelog/6395.md, package-lock.json, package.json, requirements/base.txt
=> dependencies: update a4 tag mb-v2504.2

changelog/0000.md, locale/de_DE/LC_MESSAGES/django.po, locale/de_DE/LC_MESSAGES/djangojs.po
change some wordings
**Tasks**
=> wordings: fix translation issues

meinberlin/assets/scss/components_user_facing/ck-editor/_base.scss
=> assets/scss: add fix for ckeditor image aspect ratio bug

changelog/6434.md, meinberlin/react/contrib/Pagination.jsx, meinberlin/react/contrib/PaginationButton.jsx, meinberlin/react/contrib/card/CardList.jsx
=> pagination: disable invalid pagination buttons and scroll to top after page change

.github/workflows/django.yml, changelog/6412.md, meinberlin/apps/projects/management/commands/clear_cache.py
=> added command to clear cache

changelog/6415.md, meinberlin/apps/projects/templates/meinberlin_projects/includes/plan_tile.html
=> plan-tile: remove description

changelog/6422.md, meinberlin/templates/header.html, meinberlin/templates/navigation_primary.html
=> menu: highlight kiezradar when active

changelog/6419.md, meinberlin/assets/scss/components_user_facing/_project-tile.scss
=> plan-tile: fix font weight

changelog/6429.md, meinberlin/apps/documents/templates/meinberlin_documents/chapter_detail.html, meinberlin/apps/documents/views.py
=> text-review: remove DisplayProjectOrModuleMixin, to always show module page

meinberlin/react/kiezradar/SearchProfiles.jsx
=> react/kiezradar: fix searchprofiles title

changelog/635.md, changelog/638.md, meinberlin/apps/projects/templates/meinberlin_projects/includes/project_details_summary.html, meinberlin/assets/scss/components_user_facing/_figures-box.scss, meinberlin/react/kiezradar/KiezradarList.jsx
Solves this issue: https://github.com/liqd/a4-meinberlin/issues/6437
And this: https://github.com/liqd/a4-meinberlin/issues/6416
**Tasks**
=> [ST-638] [ST-635] Frontend Change Wording + Line Wrap

changelog/773.md, meinberlin/apps/notifications/emails.py, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_new_search_profile_project.de.email, meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_new_search_profile_project.en.email, meinberlin/react/account/Notifications.jsx
Changes the the Notification View and the Email Notifications
**Tasks**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210818932680520
=> [ST-773] Notification: External Projects now show external Links

changelog/633.md, meinberlin/templates/base.html
=> ST633 move alerts up

changelog/632_2.md, meinberlin/apps/contrib/templates/meinberlin_contrib/includes/form_checkbox_field.html, meinberlin/assets/scss/styles_dashboard/_form.scss
=> ST632 styles: fix styling of checkboxes

meinberlin/react/account/notification_data.js
django needs strings in static form so they can be picked up by translator
=> apps/notifications: fix translation of notification

meinberlin/react/kiezradar/KiezradarList.jsx, meinberlin/react/kiezradar/SearchProfileButtons.jsx, meinberlin/templates/account/email.html
=> ST648 Update delete icons

changelog/707.md, meinberlin/react/contrib/map/ListMapView.jsx, package-lock.json, package.json, requirements/base.txt
=> [ST-710] New Map Split Mode

changelog/1007.md, meinberlin/assets/js/app.js, meinberlin/assets/js/navigation_primary.js, meinberlin/assets/scss/components_user_facing/_header.scss, meinberlin/templates/navigation_primary.html
**Tasks**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210856037998646
=> [1007] assets/js: Add toggle on Menu-Text 
